import { useState, useCallback, useEffect } from "react";
import {
  calculateDestinyMatrix,
  NUMBER_MEANINGS,
  SOUL_MEANINGS,
  DESTINY_EXTRAS,
  KARMIC_DEBT_MEANINGS,
  KARMIC_LESSON_MEANINGS,
} from "../../../utils/destinyMatrix";

// ─────────────────────────────────────────────────────────────
// Constants
// ─────────────────────────────────────────────────────────────
const TABS = [
  { id: "numbers",  label: "Core Numbers", icon: "🔢" },
  { id: "matrix",   label: "Matrix Grid",  icon: "🔮" },
  { id: "reading",  label: "Your Reading", icon: "📖" },
  { id: "insights", label: "Life Insights",icon: "✨" },
];

// Color per digit for the Pythagoras matrix
const DIGIT_COLORS = {
  1: "#ef4444", 2: "#f59e0b", 3: "#22c55e", 4: "#3b7bfc",
  5: "#8b5cf6", 6: "#06b6d4", 7: "#d97706", 8: "#64748b", 9: "#ec4899",
};

const CURRENT_YEAR = new Date().getFullYear();

// ─────────────────────────────────────────────────────────────
// PDF export — opens a styled print window (no external deps)
// ─────────────────────────────────────────────────────────────
function printMatrixPdf(name, dob, result) {
  const m = NUMBER_MEANINGS[result.lifePath];
  const section = (title, items) =>
    `<div class="sec"><h2>${title}</h2>${items.map(
      it => `<div class="row"><span class="lbl">${it.label}</span><span class="val">${it.value}</span></div>`
    ).join("")}</div>`;

  const html = `<!DOCTYPE html><html><head><meta charset="UTF-8">
<title>Destiny Matrix — ${name} — Tolz</title>
<style>
  body{font-family:Arial,sans-serif;max-width:600px;margin:0 auto;padding:32px;color:#1a1a2e;}
  h1{font-size:22px;margin-bottom:4px;}
  .sub{color:#888;font-size:12px;margin-bottom:26px;}
  .sec{border:1px solid #e5e5ea;border-radius:10px;padding:18px;margin-bottom:14px;}
  .sec h2{font-size:12px;font-weight:700;color:#4a4a6a;margin-bottom:10px;text-transform:uppercase;letter-spacing:.05em;}
  .row{display:flex;justify-content:space-between;padding:6px 0;border-bottom:1px solid #f3f3f5;font-size:14px;}
  .row:last-child{border-bottom:none;} .lbl{color:#888;} .val{font-weight:700;}
  .footer{margin-top:28px;text-align:center;font-size:11px;color:#aaa;}
  .tag{display:inline-block;padding:2px 8px;border-radius:99px;font-size:12px;font-weight:700;
       background:#eff6ff;color:#3b7bfc;margin:2px;}
</style></head><body>
<h1>✦ Destiny Matrix Reading</h1>
<p class="sub">For: <strong>${name}</strong> · Born: ${dob} · Generated by tolz.org · ${new Date().toLocaleDateString()}</p>

${section("Core Numerology Numbers", [
  { label: "Life Path Number", value: `${result.lifePath} — ${m?.title || ""}` },
  { label: "Destiny / Expression", value: result.destiny },
  { label: "Soul Urge / Heart's Desire", value: result.soulUrge },
  { label: "Personality Number", value: result.personality },
  { label: "Birthday Number", value: result.birthday },
  { label: "Maturity Number", value: result.maturity },
])}

${section(`Key Traits (Life Path ${result.lifePath})`, [
  { label: "Keywords", value: m?.keywords?.join(" · ") || "" },
  { label: "Strengths", value: m?.strengths?.join("; ") || "" },
  { label: "Growth Areas", value: m?.weaknesses?.join("; ") || "" },
])}

${section("Guidance", [
  { label: "Career Path", value: m?.career || "" },
  { label: "Relationships", value: m?.relationships || "" },
  { label: "Spiritual Path", value: m?.spiritual || "" },
])}

${section("Destiny & Soul", [
  { label: "Destiny Message", value: DESTINY_EXTRAS[result.destiny] || "" },
  { label: "Soul Urge Insight", value: SOUL_MEANINGS[result.soulUrge] || "" },
])}

${result.karmicDebt.length > 0 ? section("Karmic Debt", result.karmicDebt.map(n => ({
  label: KARMIC_DEBT_MEANINGS[n]?.title || `${n}`,
  value: KARMIC_DEBT_MEANINGS[n]?.guidance || "",
}))) : ""}

${result.karmicLessons.length > 0 ? section("Karmic Lessons (Missing from Name)", result.karmicLessons.map(n => ({
  label: `Missing ${n}`,
  value: KARMIC_LESSON_MEANINGS[n] || "",
}))) : ""}

${section("Lucky Numbers", [
  { label: "Your Lucky Numbers", value: result.luckyNumbers.join("  ·  ") },
])}

<div class="footer">tolz.org — Free Destiny Matrix Calculator — No Signup Required</div>
<script>window.onload=()=>window.print();<\/script>
</body></html>`;

  const w = window.open("", "_blank");
  if (!w) { alert("Please allow popups to download the PDF."); return; }
  w.document.write(html);
  w.document.close();
}

async function copyText(text) {
  try {
    await navigator.clipboard.writeText(text);
    return true;
  } catch {
    try {
      const ta = document.createElement("textarea");
      ta.value = text;
      Object.assign(ta.style, { position: "fixed", opacity: "0" });
      document.body.appendChild(ta);
      ta.select();
      document.execCommand("copy");
      document.body.removeChild(ta);
      return true;
    } catch { return false; }
  }
}

// ─────────────────────────────────────────────────────────────
// Shared style tokens
// ─────────────────────────────────────────────────────────────
const S = {
  label: {
    display: "block", fontSize: 13, fontWeight: 600,
    fontFamily: "var(--font-display)", color: "var(--text-secondary)", marginBottom: 6,
  },
  errText: { fontSize: 12, color: "var(--error)", marginTop: 4, fontFamily: "var(--font-display)" },
  card: {
    background: "var(--bg-white)", border: "1px solid var(--border)",
    borderRadius: "var(--radius-lg)", padding: "20px",
  },
  sectionTitle: {
    fontSize: 13, fontWeight: 700, fontFamily: "var(--font-display)",
    color: "var(--text-secondary)", marginBottom: 14,
    textTransform: "uppercase", letterSpacing: "0.06em",
  },
};

// ─────────────────────────────────────────────────────────────
// MatrixCell — single cell in the 3×3 Pythagoras square
// ─────────────────────────────────────────────────────────────
function MatrixCell({ num, count }) {
  const color   = DIGIT_COLORS[num];
  const isEmpty = count === 0;
  const dots    = Math.min(count, 4);

  return (
    <div
      style={{
        display: "flex", flexDirection: "column", alignItems: "center",
        justifyContent: "center", gap: 6,
        padding: "16px 8px",
        borderRadius: "var(--radius-md)",
        border: `2px ${isEmpty ? "dashed" : "solid"} ${isEmpty ? "var(--border)" : color + "55"}`,
        background: isEmpty ? "var(--bg-muted)" : `${color}0d`,
        transition: "all var(--transition)",
        cursor: "default",
      }}
    >
      {/* Number */}
      <div
        style={{
          fontSize: 28, fontWeight: 800, fontFamily: "var(--font-display)",
          color: isEmpty ? "var(--text-muted)" : color,
          lineHeight: 1, letterSpacing: "-0.02em",
          opacity: isEmpty ? 0.4 : 1,
        }}
      >
        {num}
      </div>

      {/* Count badge */}
      <div
        style={{
          fontSize: 11, fontWeight: 700, fontFamily: "var(--font-display)",
          color: isEmpty ? "var(--text-muted)" : color,
          background: isEmpty ? "transparent" : `${color}22`,
          padding: "2px 8px", borderRadius: 99,
          opacity: isEmpty ? 0.5 : 1,
        }}
      >
        {isEmpty ? "—" : `×${count}`}
      </div>

      {/* Strength dots */}
      <div style={{ display: "flex", gap: 3 }}>
        {[1, 2, 3, 4].map(i => (
          <div
            key={i}
            style={{
              width: 6, height: 6, borderRadius: "50%",
              background: i <= dots ? color : "var(--border)",
              opacity: i <= dots ? 1 : 0.35,
              transition: "all var(--transition)",
            }}
          />
        ))}
      </div>
    </div>
  );
}

// ─────────────────────────────────────────────────────────────
// MatrixGrid — full 3×3 Pythagoras square
// ─────────────────────────────────────────────────────────────
function MatrixGrid({ matrixGrid }) {
  // Pythagoras square layout: rows top→bottom = [7,8,9], [4,5,6], [1,2,3]
  const rows = [[7, 8, 9], [4, 5, 6], [1, 2, 3]];

  return (
    <div>
      {/* Row labels */}
      <div
        style={{
          display: "flex", justifyContent: "space-between",
          marginBottom: 6, padding: "0 4px",
        }}
      >
        {["Mind", "Soul", "Body"].map(lbl => (
          <span
            key={lbl}
            style={{
              fontSize: 10, fontWeight: 700, fontFamily: "var(--font-display)",
              color: "var(--text-muted)", textTransform: "uppercase",
              letterSpacing: "0.08em", flex: 1, textAlign: "center",
            }}
          >
            {lbl}
          </span>
        ))}
      </div>

      <div style={{ display: "flex", flexDirection: "column", gap: 8 }}>
        {rows.map((row, rowIdx) => (
          <div key={rowIdx} style={{ display: "grid", gridTemplateColumns: "1fr 1fr 1fr", gap: 8 }}>
            {row.map(num => (
              <MatrixCell key={num} num={num} count={matrixGrid[num]} />
            ))}
          </div>
        ))}
      </div>

      {/* Column labels */}
      <div
        style={{
          display: "flex", justifyContent: "space-between",
          marginTop: 6, padding: "0 4px",
        }}
      >
        {["Past", "Present", "Future"].map(lbl => (
          <span
            key={lbl}
            style={{
              fontSize: 10, fontWeight: 700, fontFamily: "var(--font-display)",
              color: "var(--text-muted)", textTransform: "uppercase",
              letterSpacing: "0.08em", flex: 1, textAlign: "center",
            }}
          >
            {lbl}
          </span>
        ))}
      </div>
    </div>
  );
}

// ─────────────────────────────────────────────────────────────
// NumberBadge — displays a numerology number with colour ring
// ─────────────────────────────────────────────────────────────
function NumberBadge({ num, size = 48 }) {
  const meaning = NUMBER_MEANINGS[num];
  const color   = meaning?.color || "var(--accent)";
  const bg      = meaning?.bg    || "var(--accent-light)";

  return (
    <div
      style={{
        width: size, height: size, borderRadius: "50%",
        background: bg, border: `2.5px solid ${color}55`,
        display: "flex", alignItems: "center", justifyContent: "center",
        flexShrink: 0,
      }}
    >
      <span
        style={{
          fontFamily: "var(--font-display)", fontWeight: 800,
          fontSize: size * 0.42, color,
          lineHeight: 1,
        }}
      >
        {num}
      </span>
    </div>
  );
}

// ─────────────────────────────────────────────────────────────
// CoreNumberRow — one line in the numbers overview
// ─────────────────────────────────────────────────────────────
function CoreNumberRow({ label, num, sub, icon }) {
  const meaning = NUMBER_MEANINGS[num];
  return (
    <div
      style={{
        display: "flex", alignItems: "center", gap: 14,
        padding: "14px 0",
        borderBottom: "1px solid var(--border)",
      }}
    >
      <NumberBadge num={num} size={44} />
      <div style={{ flex: 1, minWidth: 0 }}>
        <div style={{ display: "flex", alignItems: "center", gap: 8, marginBottom: 2 }}>
          <span
            style={{
              fontFamily: "var(--font-display)", fontWeight: 700,
              fontSize: 13, color: "var(--text-secondary)",
            }}
          >
            {icon} {label}
          </span>
        </div>
        <div style={{ display: "flex", alignItems: "baseline", gap: 8 }}>
          <span
            style={{
              fontFamily: "var(--font-display)", fontWeight: 800,
              fontSize: 16, color: meaning?.color || "var(--accent)",
            }}
          >
            {num}
          </span>
          <span
            style={{
              fontFamily: "var(--font-display)", fontWeight: 600,
              fontSize: 14, color: "var(--text-primary)",
            }}
          >
            {meaning?.title || ""}
          </span>
        </div>
        {sub && (
          <div style={{ fontSize: 12, color: "var(--text-muted)", marginTop: 2 }}>{sub}</div>
        )}
      </div>
    </div>
  );
}

// ─────────────────────────────────────────────────────────────
// StrengthBar — visual energy level indicator
// ─────────────────────────────────────────────────────────────
function StrengthBar({ count, color }) {
  const max   = 4;
  const level = Math.min(count, max);
  return (
    <div style={{ display: "flex", gap: 3 }}>
      {Array.from({ length: max }).map((_, i) => (
        <div
          key={i}
          style={{
            flex: 1, height: 6, borderRadius: 3,
            background: i < level ? color : "var(--border)",
            transition: "background var(--transition)",
          }}
        />
      ))}
    </div>
  );
}

// ─────────────────────────────────────────────────────────────
// ActionBar
// ─────────────────────────────────────────────────────────────
function ActionBar({ onCopy, onPrint, onReset, copied }) {
  return (
    <div style={{ display: "flex", gap: 8, flexWrap: "wrap", paddingTop: 14 }}>
      <button
        type="button" className="btn btn-secondary"
        style={{ fontSize: 13, padding: "9px 14px" }}
        onClick={onCopy}
      >
        {copied ? "✓ Copied!" : "📋 Copy Summary"}
      </button>
      <button
        type="button" className="btn btn-secondary"
        style={{ fontSize: 13, padding: "9px 14px" }}
        onClick={onPrint}
      >
        📄 Save as PDF
      </button>
      <button
        type="button" className="btn btn-ghost"
        style={{ fontSize: 13, padding: "9px 14px", marginLeft: "auto" }}
        onClick={onReset}
      >
        ↺ New Reading
      </button>
    </div>
  );
}

// ─────────────────────────────────────────────────────────────
// NumbersTab — all core numerology numbers at a glance
// ─────────────────────────────────────────────────────────────
function NumbersTab({ result, name, dob, onReset }) {
  const [copied, setCopied] = useState(false);

  const summary = `✦ Destiny Matrix Reading for ${name} (${dob})\n\n` +
    `Life Path: ${result.lifePath} — ${NUMBER_MEANINGS[result.lifePath]?.title}\n` +
    `Destiny: ${result.destiny} — ${NUMBER_MEANINGS[result.destiny]?.title}\n` +
    `Soul Urge: ${result.soulUrge} — ${NUMBER_MEANINGS[result.soulUrge]?.title}\n` +
    `Personality: ${result.personality} — ${NUMBER_MEANINGS[result.personality]?.title}\n` +
    `Birthday: ${result.birthday}\n` +
    `Maturity: ${result.maturity}\n` +
    `Lucky Numbers: ${result.luckyNumbers.join(", ")}\n\n` +
    `Calculated at tolz.org — Free Destiny Matrix Calculator`;

  const handleCopy = async () => {
    await copyText(summary);
    setCopied(true);
    setTimeout(() => setCopied(false), 2500);
  };

  return (
    <div style={{ display: "flex", flexDirection: "column", gap: 14 }}>
      {/* Primary numbers */}
      <div style={S.card}>
        <p style={S.sectionTitle}>Primary Numbers</p>
        <div>
          {[
            { label: "Life Path Number",      num: result.lifePath,   icon: "⭐", sub: "Your core life purpose and overarching theme" },
            { label: "Destiny / Expression",  num: result.destiny,    icon: "🎯", sub: "What you are destined to become and achieve" },
            { label: "Soul Urge / Heart's Desire", num: result.soulUrge, icon: "💙", sub: "Your deepest inner motivation and desire" },
            { label: "Personality Number",    num: result.personality,icon: "🎭", sub: "How others perceive you in the world" },
          ].map((item, i, arr) => (
            <div key={item.label} style={i === arr.length - 1 ? { borderBottom: "none" } : {}}>
              <CoreNumberRow {...item} />
            </div>
          ))}
        </div>
      </div>

      {/* Secondary numbers */}
      <div style={S.card}>
        <p style={S.sectionTitle}>Secondary Numbers</p>
        <div>
          {[
            { label: "Birthday Number", num: result.birthday, icon: "🎂", sub: "A special talent or gift from your birth day" },
            { label: "Maturity Number", num: result.maturity, icon: "🌙", sub: "Energies that develop strongly after age 35–40" },
          ].map((item, i) => (
            <div key={item.label} style={i === 1 ? { borderBottom: "none" } : {}}>
              <CoreNumberRow {...item} />
            </div>
          ))}
        </div>
      </div>

      {/* Lucky numbers */}
      <div style={{ ...S.card, background: "#f0fdf4", border: "1.5px solid #bbf7d0" }}>
        <p style={{ ...S.sectionTitle, color: "#15803d" }}>Lucky Numbers</p>
        <div style={{ display: "flex", gap: 10, flexWrap: "wrap" }}>
          {result.luckyNumbers.map(n => (
            <div
              key={n}
              style={{
                width: 44, height: 44, borderRadius: "50%",
                background: "#dcfce7", border: "2px solid #86efac",
                display: "flex", alignItems: "center", justifyContent: "center",
                fontFamily: "var(--font-display)", fontWeight: 800,
                fontSize: 18, color: "#16a34a",
              }}
            >
              {n}
            </div>
          ))}
        </div>
        <p style={{ fontSize: 12, color: "#15803d", marginTop: 10 }}>
          These numbers carry especially supportive energy for you.
        </p>
      </div>

      {/* Karmic info */}
      {(result.karmicDebt.length > 0 || result.karmicLessons.length > 0) && (
        <div style={S.card}>
          <p style={S.sectionTitle}>Karmic Profile</p>

          {result.karmicDebt.length > 0 && (
            <div style={{ marginBottom: result.karmicLessons.length > 0 ? 16 : 0 }}>
              <p style={{ fontSize: 12, fontWeight: 700, fontFamily: "var(--font-display)", color: "#d97706", marginBottom: 8 }}>
                ⚡ Karmic Debt Numbers
              </p>
              <div style={{ display: "flex", gap: 8, flexWrap: "wrap" }}>
                {result.karmicDebt.map(n => (
                  <span
                    key={n}
                    style={{
                      padding: "4px 12px", borderRadius: 99, fontSize: 13, fontWeight: 700,
                      fontFamily: "var(--font-display)", background: "#fffbeb",
                      border: "1.5px solid #fde68a", color: "#d97706",
                    }}
                  >
                    {n}
                  </span>
                ))}
              </div>
            </div>
          )}

          {result.karmicLessons.length > 0 && (
            <div>
              <p style={{ fontSize: 12, fontWeight: 700, fontFamily: "var(--font-display)", color: "#8b5cf6", marginBottom: 8 }}>
                📚 Karmic Lessons (missing from name)
              </p>
              <div style={{ display: "flex", gap: 8, flexWrap: "wrap" }}>
                {result.karmicLessons.map(n => (
                  <span
                    key={n}
                    style={{
                      padding: "4px 12px", borderRadius: 99, fontSize: 13, fontWeight: 700,
                      fontFamily: "var(--font-display)", background: "#f3f0ff",
                      border: "1.5px solid #ddd6fe", color: "#7c3aed",
                    }}
                  >
                    {n}
                  </span>
                ))}
              </div>
            </div>
          )}
        </div>
      )}

      <div style={{ ...S.card, paddingTop: 4, paddingBottom: 4, borderTop: "1px solid var(--border)" }}>
        <ActionBar
          copied={copied}
          onCopy={handleCopy}
          onPrint={() => printMatrixPdf(name, dob, result)}
          onReset={onReset}
        />
      </div>
    </div>
  );
}

// ─────────────────────────────────────────────────────────────
// MatrixTab — Pythagoras square + energy analysis
// ─────────────────────────────────────────────────────────────
function MatrixTab({ result, name, dob, onReset }) {
  const [copied, setCopied] = useState(false);

  const summary = `Pythagoras Matrix for ${name} (${dob})\n\n` +
    result.energyStrength.map(e => `${e.num}: ${"●".repeat(e.count)}${"○".repeat(Math.max(0, 4 - e.count))} (${e.label})`).join("\n") +
    `\n\nMissing: ${result.missingNums.join(", ") || "None"}\n` +
    `Repeated: ${result.repeatedNums.map(r => `${r.num}×${r.count}`).join(", ") || "None"}\n\n` +
    `Calculated at tolz.org`;

  const handleCopy = async () => {
    await copyText(summary);
    setCopied(true);
    setTimeout(() => setCopied(false), 2500);
  };

  return (
    <div style={{ display: "flex", flexDirection: "column", gap: 14 }}>
      {/* The grid */}
      <div style={S.card}>
        <p style={S.sectionTitle}>Pythagoras Destiny Square</p>
        <MatrixGrid matrixGrid={result.matrixGrid} />
        <p style={{ fontSize: 11, color: "var(--text-muted)", marginTop: 14, textAlign: "center", lineHeight: 1.5 }}>
          Each cell shows how many times that digit appears in your birth date. The strength dots indicate energy intensity.
        </p>
      </div>

      {/* Energy analysis */}
      <div style={S.card}>
        <p style={S.sectionTitle}>Energy Strength Analysis</p>
        <div style={{ display: "flex", flexDirection: "column", gap: 10 }}>
          {result.energyStrength.map(({ num, count, label }) => {
            const color = DIGIT_COLORS[num];
            const meaning = NUMBER_MEANINGS[num];
            return (
              <div key={num} style={{ display: "flex", alignItems: "center", gap: 12 }}>
                <div
                  style={{
                    width: 32, height: 32, borderRadius: 8, flexShrink: 0,
                    background: count === 0 ? "var(--bg-muted)" : `${color}15`,
                    border: `1.5px solid ${count === 0 ? "var(--border)" : color + "44"}`,
                    display: "flex", alignItems: "center", justifyContent: "center",
                    fontFamily: "var(--font-display)", fontWeight: 800, fontSize: 14,
                    color: count === 0 ? "var(--text-muted)" : color,
                  }}
                >
                  {num}
                </div>
                <div style={{ flex: 1, minWidth: 0 }}>
                  <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: 4 }}>
                    <span style={{ fontSize: 12, fontWeight: 700, fontFamily: "var(--font-display)", color: "var(--text-primary)" }}>
                      {meaning?.title || `Number ${num}`}
                    </span>
                    <span
                      style={{
                        fontSize: 11, fontWeight: 600, fontFamily: "var(--font-display)",
                        color: count === 0 ? "var(--text-muted)" : color,
                        background: count === 0 ? "var(--bg-muted)" : `${color}15`,
                        padding: "1px 8px", borderRadius: 99,
                      }}
                    >
                      {label}
                    </span>
                  </div>
                  <StrengthBar count={count} color={count === 0 ? "var(--border)" : color} />
                </div>
              </div>
            );
          })}
        </div>
      </div>

      {/* Missing and repeated */}
      <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: 10 }}>
        <div
          style={{
            ...S.card,
            background: result.missingNums.length > 0 ? "#fff5f5" : "#f0fdf4",
            border: `1.5px solid ${result.missingNums.length > 0 ? "#fecdcd" : "#bbf7d0"}`,
          }}
        >
          <p
            style={{
              fontSize: 12, fontWeight: 700, fontFamily: "var(--font-display)",
              color: result.missingNums.length > 0 ? "#dc2626" : "#16a34a",
              marginBottom: 10,
            }}
          >
            {result.missingNums.length > 0 ? "⬜ Missing" : "✓ No Missing"}
          </p>
          {result.missingNums.length > 0 ? (
            <div style={{ display: "flex", gap: 6, flexWrap: "wrap" }}>
              {result.missingNums.map(n => (
                <span
                  key={n}
                  style={{
                    width: 28, height: 28, borderRadius: 6,
                    background: "white", border: "1.5px dashed #fca5a5",
                    display: "flex", alignItems: "center", justifyContent: "center",
                    fontFamily: "var(--font-display)", fontWeight: 700,
                    fontSize: 13, color: "#dc2626",
                  }}
                >
                  {n}
                </span>
              ))}
            </div>
          ) : (
            <p style={{ fontSize: 12, color: "#16a34a" }}>All digits present!</p>
          )}
        </div>

        <div
          style={{
            ...S.card,
            background: result.repeatedNums.length > 0 ? "#f5f3ff" : "#f8fafc",
            border: `1.5px solid ${result.repeatedNums.length > 0 ? "#ddd6fe" : "var(--border)"}`,
          }}
        >
          <p
            style={{
              fontSize: 12, fontWeight: 700, fontFamily: "var(--font-display)",
              color: result.repeatedNums.length > 0 ? "#7c3aed" : "var(--text-muted)",
              marginBottom: 10,
            }}
          >
            🔁 Repeated
          </p>
          {result.repeatedNums.length > 0 ? (
            <div style={{ display: "flex", gap: 6, flexWrap: "wrap" }}>
              {result.repeatedNums.map(({ num, count }) => (
                <div key={num} style={{ textAlign: "center" }}>
                  <span
                    style={{
                      width: 28, height: 28, borderRadius: 6,
                      background: `${DIGIT_COLORS[num]}15`,
                      border: `1.5px solid ${DIGIT_COLORS[num]}44`,
                      display: "flex", alignItems: "center", justifyContent: "center",
                      fontFamily: "var(--font-display)", fontWeight: 700,
                      fontSize: 13, color: DIGIT_COLORS[num],
                    }}
                  >
                    {num}
                  </span>
                  <span style={{ fontSize: 10, color: "var(--text-muted)", fontFamily: "var(--font-display)" }}>×{count}</span>
                </div>
              ))}
            </div>
          ) : (
            <p style={{ fontSize: 12, color: "var(--text-muted)" }}>No repeated digits</p>
          )}
        </div>
      </div>

      <div style={{ ...S.card, paddingTop: 4, paddingBottom: 4 }}>
        <ActionBar
          copied={copied}
          onCopy={handleCopy}
          onPrint={() => printMatrixPdf(name, dob, result)}
          onReset={onReset}
        />
      </div>
    </div>
  );
}

// ─────────────────────────────────────────────────────────────
// ReadingTab — deep interpretation of core numbers
// ─────────────────────────────────────────────────────────────
function ReadingTab({ result, name, dob, onReset }) {
  const [copied, setCopied] = useState(false);
  const lp    = NUMBER_MEANINGS[result.lifePath];
  const dest  = NUMBER_MEANINGS[result.destiny];
  const soul  = NUMBER_MEANINGS[result.soulUrge];
  const pers  = NUMBER_MEANINGS[result.personality];

  const summary =
    `Reading for ${name} — Life Path ${result.lifePath}: ${lp?.title}\n\n` +
    `${lp?.description}\n\nStrengths: ${lp?.strengths?.join(", ")}\n` +
    `Growth Areas: ${lp?.weaknesses?.join(", ")}\n\n` +
    `Destiny (${result.destiny}): ${DESTINY_EXTRAS[result.destiny]}\n` +
    `Soul Urge (${result.soulUrge}): ${SOUL_MEANINGS[result.soulUrge]}\n\n` +
    `Calculated at tolz.org`;

  const handleCopy = async () => {
    await copyText(summary);
    setCopied(true);
    setTimeout(() => setCopied(false), 2500);
  };

  const KeywordPill = ({ word, color }) => (
    <span
      style={{
        padding: "3px 10px", borderRadius: 99, fontSize: 12, fontWeight: 600,
        fontFamily: "var(--font-display)", background: `${color}15`,
        color, border: `1px solid ${color}33`,
      }}
    >
      {word}
    </span>
  );

  return (
    <div style={{ display: "flex", flexDirection: "column", gap: 14 }}>
      {/* Life Path — the most important number */}
      <div
        style={{
          ...S.card,
          background: lp?.bg || "var(--bg-white)",
          border: `2px solid ${lp?.color || "var(--accent)"}33`,
        }}
      >
        <div style={{ display: "flex", alignItems: "center", gap: 14, marginBottom: 16 }}>
          <NumberBadge num={result.lifePath} size={52} />
          <div>
            <p style={{ fontSize: 11, fontWeight: 700, fontFamily: "var(--font-display)", color: lp?.color, textTransform: "uppercase", letterSpacing: "0.08em", marginBottom: 2 }}>
              Life Path Number {result.lifePath}
            </p>
            <p style={{ fontFamily: "var(--font-display)", fontWeight: 800, fontSize: 18, color: "var(--text-primary)", letterSpacing: "-0.02em" }}>
              {lp?.title}
            </p>
          </div>
        </div>

        <div style={{ display: "flex", gap: 6, flexWrap: "wrap", marginBottom: 14 }}>
          {lp?.keywords?.map(kw => (
            <KeywordPill key={kw} word={kw} color={lp.color} />
          ))}
        </div>

        <p style={{ fontSize: 14, color: "var(--text-secondary)", lineHeight: 1.65, marginBottom: 16 }}>
          {lp?.description}
        </p>

        <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: 10 }}>
          <div
            style={{
              padding: 14, borderRadius: "var(--radius-md)",
              background: "rgba(255,255,255,0.7)",
              border: "1px solid rgba(0,0,0,0.06)",
            }}
          >
            <p style={{ fontSize: 11, fontWeight: 700, fontFamily: "var(--font-display)", color: "#16a34a", textTransform: "uppercase", letterSpacing: "0.06em", marginBottom: 8 }}>
              ✦ Strengths
            </p>
            <ul style={{ listStyle: "none", display: "flex", flexDirection: "column", gap: 4 }}>
              {lp?.strengths?.map(s => (
                <li key={s} style={{ fontSize: 12, color: "var(--text-secondary)", lineHeight: 1.5 }}>
                  · {s}
                </li>
              ))}
            </ul>
          </div>
          <div
            style={{
              padding: 14, borderRadius: "var(--radius-md)",
              background: "rgba(255,255,255,0.7)",
              border: "1px solid rgba(0,0,0,0.06)",
            }}
          >
            <p style={{ fontSize: 11, fontWeight: 700, fontFamily: "var(--font-display)", color: "#d97706", textTransform: "uppercase", letterSpacing: "0.06em", marginBottom: 8 }}>
              ◈ Growth Areas
            </p>
            <ul style={{ listStyle: "none", display: "flex", flexDirection: "column", gap: 4 }}>
              {lp?.weaknesses?.map(w => (
                <li key={w} style={{ fontSize: 12, color: "var(--text-secondary)", lineHeight: 1.5 }}>
                  · {w}
                </li>
              ))}
            </ul>
          </div>
        </div>
      </div>

      {/* Destiny Number */}
      <div style={{ ...S.card }}>
        <div style={{ display: "flex", alignItems: "center", gap: 12, marginBottom: 12 }}>
          <NumberBadge num={result.destiny} size={40} />
          <div>
            <p style={{ fontSize: 11, fontWeight: 700, fontFamily: "var(--font-display)", color: dest?.color, textTransform: "uppercase", letterSpacing: "0.06em" }}>
              Destiny Number {result.destiny}
            </p>
            <p style={{ fontFamily: "var(--font-display)", fontWeight: 700, fontSize: 15, color: "var(--text-primary)" }}>
              {dest?.title}
            </p>
          </div>
        </div>
        <p style={{ fontSize: 13, color: "var(--text-secondary)", lineHeight: 1.6 }}>
          {DESTINY_EXTRAS[result.destiny]}
        </p>
      </div>

      {/* Soul Urge */}
      <div style={{ ...S.card, background: "#fdf2f8", border: "1px solid #fbcfe8" }}>
        <div style={{ display: "flex", alignItems: "center", gap: 12, marginBottom: 12 }}>
          <NumberBadge num={result.soulUrge} size={40} />
          <div>
            <p style={{ fontSize: 11, fontWeight: 700, fontFamily: "var(--font-display)", color: soul?.color, textTransform: "uppercase", letterSpacing: "0.06em" }}>
              Soul Urge Number {result.soulUrge}
            </p>
            <p style={{ fontFamily: "var(--font-display)", fontWeight: 700, fontSize: 15, color: "var(--text-primary)" }}>
              {soul?.title}
            </p>
          </div>
        </div>
        <p style={{ fontSize: 13, color: "var(--text-secondary)", lineHeight: 1.6 }}>
          💙 {SOUL_MEANINGS[result.soulUrge]}
        </p>
      </div>

      {/* Personality */}
      <div style={S.card}>
        <div style={{ display: "flex", alignItems: "center", gap: 12, marginBottom: 10 }}>
          <NumberBadge num={result.personality} size={40} />
          <div>
            <p style={{ fontSize: 11, fontWeight: 700, fontFamily: "var(--font-display)", color: pers?.color, textTransform: "uppercase", letterSpacing: "0.06em" }}>
              Personality Number {result.personality}
            </p>
            <p style={{ fontFamily: "var(--font-display)", fontWeight: 700, fontSize: 15, color: "var(--text-primary)" }}>
              {pers?.title}
            </p>
          </div>
        </div>
        <p style={{ fontSize: 13, color: "var(--text-secondary)", lineHeight: 1.6 }}>
          🎭 This is the mask you show the world — the first impression others get of you. {pers?.description?.split(".")[0]}.
        </p>
      </div>

      <div style={{ ...S.card, paddingTop: 4, paddingBottom: 4 }}>
        <ActionBar
          copied={copied}
          onCopy={handleCopy}
          onPrint={() => printMatrixPdf(name, dob, result)}
          onReset={onReset}
        />
      </div>
    </div>
  );
}

// ─────────────────────────────────────────────────────────────
// InsightSection — reusable insight card
// ─────────────────────────────────────────────────────────────
const InsightSection = ({ icon, title, text, accent }) => (
  <div
    style={{
      padding: 16, borderRadius: "var(--radius-md)",
      background: accent + "0d", border: `1px solid ${accent}33`,
      marginBottom: 10,
    }}
  >
    <p style={{ fontSize: 12, fontWeight: 700, fontFamily: "var(--font-display)", color: accent, marginBottom: 8, textTransform: "uppercase", letterSpacing: "0.05em" }}>
      {icon} {title}
    </p>
    <p style={{ fontSize: 13, color: "var(--text-secondary)", lineHeight: 1.65 }}>{text}</p>
  </div>
);

// ─────────────────────────────────────────────────────────────
// InsightsTab — career, relationships, spiritual, karmic
// ─────────────────────────────────────────────────────────────
function InsightsTab({ result, name, dob, onReset }) {
  const [copied, setCopied] = useState(false);
  const lp = NUMBER_MEANINGS[result.lifePath];
  const dest = NUMBER_MEANINGS[result.destiny];
  const soul = NUMBER_MEANINGS[result.soulUrge];

  const summary =
    `Life Insights for ${name} — Life Path ${result.lifePath}\n\n` +
    `Career: ${lp?.career}\n\nRelationships: ${lp?.relationships}\n\n` +
    `Spiritual Path: ${lp?.spiritual}\n\n` +
    (result.karmicDebt.length > 0
      ? `Karmic Debt: ${result.karmicDebt.map(n => KARMIC_DEBT_MEANINGS[n]?.title).join(", ")}\n\n`
      : "") +
    `Calculated at tolz.org`;

  const handleCopy = async () => {
    await copyText(summary);
    setCopied(true);
    setTimeout(() => setCopied(false), 2500);
  };

  return (
    <div style={{ display: "flex", flexDirection: "column", gap: 14 }}>
      {/* Career */}
      <div style={S.card}>
        <p style={S.sectionTitle}>Career & Purpose</p>
        <InsightSection
          icon="💼" title="Your Career Path" accent="#3b7bfc"
          text={`Based on your Life Path ${result.lifePath}: ${lp?.career}`}
        />
        <InsightSection
          icon="🎯" title="Destiny Purpose" accent="#8b5cf6"
          text={DESTINY_EXTRAS[result.destiny] || ""}
        />
      </div>

      {/* Relationships */}
      <div style={S.card}>
        <p style={S.sectionTitle}>Love & Relationships</p>
        <InsightSection
          icon="❤️" title="How You Love" accent="#ec4899"
          text={`Life Path ${result.lifePath}: ${lp?.relationships}`}
        />
        <InsightSection
          icon="💙" title="Your Heart's Desire" accent="#06b6d4"
          text={SOUL_MEANINGS[result.soulUrge] || ""}
        />
      </div>

      {/* Spiritual */}
      <div style={S.card}>
        <p style={S.sectionTitle}>Spiritual Path</p>
        <InsightSection
          icon="✨" title="Your Soul Journey" accent="#d97706"
          text={`Life Path ${result.lifePath}: ${lp?.spiritual}`}
        />
        {NUMBER_MEANINGS[result.maturity] && (
          <InsightSection
            icon="🌙" title={`Maturity Number ${result.maturity} — Later Life`} accent="#6366f1"
            text={`After age 35–40, the energy of ${NUMBER_MEANINGS[result.maturity]?.title} becomes prominent. ${NUMBER_MEANINGS[result.maturity]?.description?.split(".")[0]}.`}
          />
        )}
      </div>

      {/* Karmic Debt */}
      {result.karmicDebt.length > 0 && (
        <div style={{ ...S.card, background: "#fffbeb", border: "1.5px solid #fde68a" }}>
          <p style={{ ...S.sectionTitle, color: "#d97706" }}>Karmic Debt Guidance</p>
          {result.karmicDebt.map(n => {
            const debt = KARMIC_DEBT_MEANINGS[n];
            if (!debt) return null;
            return (
              <div key={n} style={{ marginBottom: 14 }}>
                <p style={{ fontFamily: "var(--font-display)", fontWeight: 700, fontSize: 14, color: "#92400e", marginBottom: 6 }}>
                  ⚡ {debt.title}
                </p>
                <p style={{ fontSize: 13, color: "#78350f", lineHeight: 1.6, marginBottom: 8 }}>{debt.description}</p>
                <div style={{ padding: "10px 14px", borderRadius: "var(--radius-md)", background: "white", border: "1px solid #fde68a" }}>
                  <p style={{ fontSize: 13, color: "#92400e", lineHeight: 1.6, fontWeight: 500 }}>
                    💡 Guidance: {debt.guidance}
                  </p>
                </div>
              </div>
            );
          })}
        </div>
      )}

      {/* Karmic Lessons */}
      {result.karmicLessons.length > 0 && (
        <div style={{ ...S.card, background: "#f5f3ff", border: "1.5px solid #ddd6fe" }}>
          <p style={{ ...S.sectionTitle, color: "#7c3aed" }}>Karmic Lessons</p>
          <p style={{ fontSize: 13, color: "#5b21b6", marginBottom: 12, lineHeight: 1.6 }}>
            The following numbers are missing from your name. These represent areas where you carry lessons from past experiences.
          </p>
          {result.karmicLessons.map(n => (
            <div key={n} style={{ display: "flex", gap: 12, marginBottom: 10, alignItems: "flex-start" }}>
              <div
                style={{
                  width: 32, height: 32, borderRadius: 8, flexShrink: 0,
                  background: `${DIGIT_COLORS[n]}15`, border: `1.5px solid ${DIGIT_COLORS[n]}44`,
                  display: "flex", alignItems: "center", justifyContent: "center",
                  fontFamily: "var(--font-display)", fontWeight: 800, fontSize: 14,
                  color: DIGIT_COLORS[n],
                }}
              >
                {n}
              </div>
              <p style={{ fontSize: 13, color: "#5b21b6", lineHeight: 1.6, flex: 1 }}>
                {KARMIC_LESSON_MEANINGS[n]}
              </p>
            </div>
          ))}
        </div>
      )}

      <div style={{ ...S.card, paddingTop: 4, paddingBottom: 4 }}>
        <ActionBar
          copied={copied}
          onCopy={handleCopy}
          onPrint={() => printMatrixPdf(name, dob, result)}
          onReset={onReset}
        />
      </div>
    </div>
  );
}

// ─────────────────────────────────────────────────────────────
// InputForm — name + date of birth
// ─────────────────────────────────────────────────────────────
function InputForm({ onCalculate }) {
  const [name,  setName]  = useState("");
  const [day,   setDay]   = useState("");
  const [month, setMonth] = useState("");
  const [year,  setYear]  = useState("");
  const [errors, setErrors] = useState({});

  const validate = useCallback(() => {
    const e = {};
    const n = name.trim();
    if (!n || n.length < 2) {
      e.name = "Please enter your full name (at least first and last).";
    } else if (!/^[a-zA-Z\s''-]+$/.test(n)) {
      e.name = "Name should contain letters only.";
    } else if (n.length > 100) {
      e.name = "Name is too long (max 100 characters).";
    }

    const d = Number(day);
    const m = Number(month);
    const y = Number(year);
    if (!day || isNaN(d) || d < 1 || d > 31) e.day = "Day must be 1–31.";
    if (!month || isNaN(m) || m < 1 || m > 12) e.month = "Month must be 1–12.";
    if (!year || isNaN(y) || y < 1900 || y > CURRENT_YEAR) e.year = `Year must be 1900–${CURRENT_YEAR}.`;

    if (!e.day && !e.month && !e.year) {
      const dateObj = new Date(y, m - 1, d);
      if (dateObj.getMonth() !== m - 1 || dateObj.getDate() !== d) {
        e.day = `${d}/${m}/${y} is not a valid date.`;
      } else if (dateObj > new Date()) {
        e.year = "Birth date cannot be in the future.";
      }
    }
    return e;
  }, [name, day, month, year]);

  const handleCalculate = () => {
    const e = validate();
    if (Object.keys(e).length > 0) { setErrors(e); return; }
    setErrors({});
    const result = calculateDestinyMatrix(name.trim(), Number(day), Number(month), Number(year));
    const dob    = `${String(day).padStart(2,"0")}/${String(month).padStart(2,"0")}/${year}`;
    onCalculate(result, name.trim(), dob);
  };

  const handleKey = (e) => { if (e.key === "Enter") handleCalculate(); };

  return (
    <div style={{ display: "flex", flexDirection: "column", gap: 16 }}>
      {/* Intro card */}
      <div
        style={{
          padding: "20px", borderRadius: "var(--radius-lg)",
          background: "linear-gradient(135deg, #eef2ff 0%, #f3f0ff 100%)",
          border: "1.5px solid #c7d2fe",
        }}
      >
        <p style={{ fontFamily: "var(--font-display)", fontWeight: 800, fontSize: 15, color: "#3730a3", marginBottom: 6 }}>
          ✦ Discover Your Destiny Matrix
        </p>
        <p style={{ fontSize: 13, color: "#4338ca", lineHeight: 1.6 }}>
          Based on the ancient Pythagorean numerology system, your Destiny Matrix reveals your life path, soul purpose, personality energies, and karmic patterns — all calculated instantly from your name and birth date.
        </p>
      </div>

      {/* Form */}
      <div style={S.card}>
        <p style={S.sectionTitle}>Your Information</p>
        <div style={{ display: "flex", flexDirection: "column", gap: 14 }}>
          {/* Name */}
          <div>
            <label style={S.label}>Full Name (as on birth certificate)</label>
            <input
              className="input"
              type="text"
              placeholder="e.g. Emily Rose Johnson"
              value={name}
              maxLength={100}
              onChange={e => { setName(e.target.value); setErrors(prev => ({ ...prev, name: undefined })); }}
              onKeyDown={handleKey}
              style={errors.name ? { borderColor: "var(--error)" } : {}}
              autoComplete="name"
            />
            {errors.name && <p style={S.errText}>{errors.name}</p>}
            <p style={{ fontSize: 11, color: "var(--text-muted)", marginTop: 4 }}>
              Used to calculate Destiny, Soul Urge, and Personality numbers.
            </p>
          </div>

          {/* Date of Birth */}
          <div>
            <label style={S.label}>Date of Birth</label>
            <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr 2fr", gap: 8 }}>
              <div>
                <input
                  className="input"
                  type="number" min="1" max="31"
                  placeholder="DD"
                  value={day}
                  onChange={e => { setDay(e.target.value); setErrors(prev => ({ ...prev, day: undefined })); }}
                  onKeyDown={handleKey}
                  style={errors.day ? { borderColor: "var(--error)" } : {}}
                />
                {errors.day && <p style={S.errText}>{errors.day}</p>}
              </div>
              <div>
                <input
                  className="input"
                  type="number" min="1" max="12"
                  placeholder="MM"
                  value={month}
                  onChange={e => { setMonth(e.target.value); setErrors(prev => ({ ...prev, month: undefined })); }}
                  onKeyDown={handleKey}
                  style={errors.month ? { borderColor: "var(--error)" } : {}}
                />
                {errors.month && <p style={S.errText}>{errors.month}</p>}
              </div>
              <div>
                <input
                  className="input"
                  type="number" min="1900" max={CURRENT_YEAR}
                  placeholder="YYYY"
                  value={year}
                  onChange={e => { setYear(e.target.value); setErrors(prev => ({ ...prev, year: undefined })); }}
                  onKeyDown={handleKey}
                  style={errors.year ? { borderColor: "var(--error)" } : {}}
                />
                {errors.year && <p style={S.errText}>{errors.year}</p>}
              </div>
            </div>
          </div>
        </div>
      </div>

      <button
        type="button"
        className="btn btn-primary"
        style={{ width: "100%", padding: "14px", fontSize: 15 }}
        onClick={handleCalculate}
      >
        ✦ Calculate My Destiny Matrix
      </button>

      {/* Trust badges */}
      <div style={{ display: "flex", gap: 8, flexWrap: "wrap", justifyContent: "center" }}>
        {["🔒 Private", "⚡ Instant", "💾 Not Stored", "✓ Free Forever"].map(b => (
          <span
            key={b}
            style={{
              fontSize: 11, fontWeight: 600, fontFamily: "var(--font-display)",
              color: "var(--text-muted)", background: "var(--bg-muted)",
              padding: "3px 10px", borderRadius: 99, border: "1px solid var(--border)",
            }}
          >
            {b}
          </span>
        ))}
      </div>

      <p style={{ fontSize: 12, color: "var(--text-muted)", textAlign: "center", lineHeight: 1.5 }}>
        Numerology is a reflective tool for personal insight, not predictive science. Results are for self-exploration only.
      </p>
    </div>
  );
}

// ─────────────────────────────────────────────────────────────
// Main component
// ─────────────────────────────────────────────────────────────
export default function DestinyMatrixTool() {
  const [phase,  setPhase]  = useState("idle"); // idle | done
  const [result, setResult] = useState(null);
  const [name,   setName]   = useState("");
  const [dob,    setDob]    = useState("");
  const [activeTab, setActiveTab] = useState("numbers");

  useEffect(() => {
    const prev = document.title;
    document.title = "Free Destiny Matrix Calculator — Numerology Reading | Tolz";
    return () => { document.title = prev; };
  }, []);

  const handleCalculate = useCallback((res, n, d) => {
    setResult(res);
    setName(n);
    setDob(d);
    setActiveTab("numbers");
    setPhase("done");
  }, []);

  const handleReset = useCallback(() => {
    setPhase("idle");
    setResult(null);
    setName("");
    setDob("");
  }, []);

  if (phase === "idle") {
    return (
      <div className="animate-fadeUp">
        <InputForm onCalculate={handleCalculate} />
      </div>
    );
  }

  const lp = NUMBER_MEANINGS[result.lifePath];

  return (
    <div className="animate-fadeUp" style={{ display: "flex", flexDirection: "column", gap: 16 }}>
      {/* Result header */}
      <div
        style={{
          padding: "20px",
          borderRadius: "var(--radius-lg)",
          background: `linear-gradient(135deg, ${lp?.bg || "#eff6ff"} 0%, #f3f0ff 100%)`,
          border: `1.5px solid ${lp?.color || "#3b7bfc"}33`,
        }}
      >
        <div style={{ display: "flex", alignItems: "center", gap: 14 }}>
          <NumberBadge num={result.lifePath} size={52} />
          <div>
            <p style={{ fontSize: 11, fontWeight: 700, fontFamily: "var(--font-display)", color: lp?.color, textTransform: "uppercase", letterSpacing: "0.08em", marginBottom: 2 }}>
              Destiny Matrix Reading
            </p>
            <p style={{ fontFamily: "var(--font-display)", fontWeight: 800, fontSize: 17, color: "var(--text-primary)", letterSpacing: "-0.02em", marginBottom: 2 }}>
              {name}
            </p>
            <p style={{ fontSize: 12, color: "var(--text-muted)", fontFamily: "var(--font-display)" }}>
              Born {dob} · Life Path {result.lifePath}: {lp?.title}
            </p>
          </div>
        </div>
      </div>

      {/* Tab navigation */}
      <div
        style={{
          display: "flex", gap: 6, overflowX: "auto", paddingBottom: 2,
          scrollbarWidth: "none", msOverflowStyle: "none",
        }}
      >
        {TABS.map(tab => (
          <button
            key={tab.id}
            type="button"
            onClick={() => setActiveTab(tab.id)}
            style={{
              display: "flex", alignItems: "center", gap: 6, flexShrink: 0,
              padding: "9px 16px", borderRadius: 99, fontSize: 13, fontWeight: 600,
              fontFamily: "var(--font-display)", cursor: "pointer",
              border: `1.5px solid ${activeTab === tab.id ? "var(--accent)" : "var(--border)"}`,
              background: activeTab === tab.id ? "var(--accent)" : "var(--bg-white)",
              color: activeTab === tab.id ? "#fff" : "var(--text-secondary)",
              transition: "all var(--transition)",
              boxShadow: activeTab === tab.id ? "0 2px 8px rgba(59,123,252,0.25)" : "none",
            }}
          >
            <span style={{ fontSize: 15 }}>{tab.icon}</span>
            {tab.label}
          </button>
        ))}
      </div>

      {/* Tab content */}
      {activeTab === "numbers"  && <NumbersTab  result={result} name={name} dob={dob} onReset={handleReset} />}
      {activeTab === "matrix"   && <MatrixTab   result={result} name={name} dob={dob} onReset={handleReset} />}
      {activeTab === "reading"  && <ReadingTab  result={result} name={name} dob={dob} onReset={handleReset} />}
      {activeTab === "insights" && <InsightsTab result={result} name={name} dob={dob} onReset={handleReset} />}
    </div>
  );
}
