// Single source of truth for all calculator categories and their tools.
// Navbar, category pages, breadcrumbs, and search all read from here.

export const CALCULATOR_CATEGORIES = [
  {
    id: "health",
    name: "Health Calculators",
    slug: "health",
    path: "/calculators/health",
    tagline: "BMI, calories, sleep cycles & more",
    description:
      "Free health calculators for BMI, daily calories, macros, sleep cycles, and nutrition. No signup required.",
    icon: "🏥",
    iconBg: "#f0fdf4",
    iconColor: "#22c55e",
    calculators: [
      {
        id: "calorie-tracker",
        label: "Calorie Tracker & Calculator",
        slug: "calorie-tracker",
        tagline: "BMI, TDEE, Macros, Water & Meal Planner",
        description:
          "Calculate your BMI, daily calorie needs (TDEE), macro breakdown, water intake and get healthy meal suggestions — all in one free tool.",
        icon: "🥗",
        iconBg: "#f0fdf4",
        iconColor: "#22c55e",
        path: "/calculators/health/calorie-tracker",
        legacyPath: "/tools/calorie-tracker",
        keywords: ["calorie", "bmi", "tdee", "macros", "nutrition", "diet", "weight loss"],
        available: true,
        badge: "New",
        badgeType: "new",
      },
      {
        id: "sleep-calculator",
        label: "Sleep Calculator",
        slug: "sleep-calculator",
        tagline: "Optimal sleep & wake-up times based on sleep cycles",
        description:
          "Find the best time to go to sleep or wake up based on 90-minute sleep cycles. Wake up refreshed, not groggy.",
        icon: "🌙",
        iconBg: "#eef2ff",
        iconColor: "#6366f1",
        path: "/calculators/health/sleep-calculator",
        legacyPath: "/tools/sleep-calculator",
        keywords: ["sleep", "wake up", "sleep cycle", "rest", "insomnia", "REM"],
        available: true,
        badge: "New",
        badgeType: "new",
      },
    ],
  },
  {
    id: "construction",
    name: "Construction Calculators",
    slug: "construction",
    path: "/calculators/construction",
    tagline: "Square footage, cubic yards, board feet, aluminum weight & more",
    description:
      "Free construction calculators — converters for square footage, cubic yards, board feet, paint coverage, and material weight calculators for aluminum, steel, and more.",
    icon: "🏗️",
    iconBg: "#fff7ed",
    iconColor: "#f59e0b",
    groups: [
      {
        id: "construction-converters",
        name: "Construction Converters",
        icon: "🔨",
        calculators: [
          {
            id: "square-footage-calculator",
            label: "Square Footage Calculator",
            slug: "square-footage",
            tagline: "Area for any shape — floor, roof, land",
            description:
              "Calculate square footage for 10 shapes: rectangle, square, circle, triangle, trapezoid, ellipse, semi-circle, L-shape, ring, and custom polygon. Supports all unit systems.",
            icon: "📐",
            iconBg: "#eff6ff",
            iconColor: "#3b7bfc",
            path: "/calculators/construction/square-footage",
            legacyPath: "/tools/square-footage-calculator",
            keywords: ["square footage", "area", "floor", "roof", "land", "square feet"],
            available: true,
            badge: "New",
            badgeType: "new",
          },
          {
            id: "square-yards-calculator",
            label: "Square Yards Calculator",
            slug: "square-yards",
            tagline: "Sod, carpet, tile, flooring & landscaping",
            description:
              "Calculate area in square yards for 10 shapes. Built-in material estimator for sod, carpet, tile, mulch, gravel, and artificial grass.",
            icon: "🌿",
            iconBg: "#f0fdf4",
            iconColor: "#16a34a",
            path: "/calculators/construction/square-yards",
            legacyPath: "/tools/square-yards-calculator",
            keywords: ["square yards", "sod", "carpet", "tile", "flooring", "landscaping"],
            available: true,
            badge: "New",
            badgeType: "new",
          },
          {
            id: "cubic-yard-calculator",
            label: "Cubic Yard Calculator",
            slug: "cubic-yard",
            tagline: "Concrete, gravel, sand, soil & more",
            description:
              "Calculate volume in cubic yards for concrete, gravel, sand, soil, mulch and fill dirt. Instant results with material weight estimates.",
            icon: "📐",
            iconBg: "#f0fdf4",
            iconColor: "#16a34a",
            path: "/calculators/construction/cubic-yard",
            legacyPath: "/tools/cubic-yard-calculator",
            keywords: ["cubic yard", "concrete", "gravel", "sand", "soil", "mulch", "volume"],
            available: true,
            badge: "New",
            badgeType: "new",
          },
          {
            id: "sqft-to-cubic-yards",
            label: "Sq Ft to Cubic Yards Calculator",
            slug: "sqft-to-cubic-yards",
            tagline: "Convert area + depth to cubic yards instantly",
            description:
              "Convert square feet and depth into cubic yards instantly. Supports material weight estimation for concrete, gravel, sand, topsoil, and mulch.",
            icon: "🧱",
            iconBg: "#f0fdf4",
            iconColor: "#16a34a",
            path: "/calculators/construction/sqft-to-cubic-yards",
            legacyPath: "/tools/sqft-to-cubic-yards",
            keywords: ["sq ft to cubic yards", "square feet", "depth", "volume conversion"],
            available: true,
            badge: "New",
            badgeType: "new",
          },
          {
            id: "gallons-calculator",
            label: "Gallons per Sq Ft Calculator",
            slug: "gallons",
            tagline: "Paint, sealers, epoxy & coating coverage",
            description:
              "Calculate gallons per square foot, total gallons needed, and coverage area for paint, primer, epoxy, concrete sealers, and waterproofing.",
            icon: "🪣",
            iconBg: "#eff6ff",
            iconColor: "#3b7bfc",
            path: "/calculators/construction/gallons",
            legacyPath: "/tools/gallons-calculator",
            keywords: ["gallons", "paint", "coverage", "sealer", "epoxy", "coating"],
            available: true,
            badge: "New",
            badgeType: "new",
          },
          {
            id: "board-foot-calculator",
            label: "Board Foot Calculator",
            slug: "board-foot",
            tagline: "Calculate lumber volume in board feet",
            description:
              "Instantly calculate board feet for any lumber size. Supports inches, mm, cm, feet and meters. Enter thickness, width, length and quantity.",
            icon: "🪵",
            iconBg: "#fef3c7",
            iconColor: "#d97706",
            path: "/calculators/construction/board-foot",
            legacyPath: "/tools/board-foot-calculator",
            keywords: ["board foot", "lumber", "wood", "timber", "board feet"],
            available: true,
            badge: "New",
            badgeType: "new",
          },
          {
            id: "size-to-weight-calculator",
            label: "Size to Weight Calculator",
            slug: "size-to-weight",
            tagline: "Weight of steel, aluminum, concrete & more",
            description:
              "Calculate the weight of any rectangular solid from its dimensions and material density. Supports 20+ materials and all major unit systems.",
            icon: "⚖️",
            iconBg: "#fef3c7",
            iconColor: "#d97706",
            path: "/calculators/construction/size-to-weight",
            legacyPath: "/tools/size-to-weight-calculator",
            keywords: ["weight", "steel", "aluminum", "concrete", "density", "material"],
            available: true,
            badge: "New",
            badgeType: "new",
          },
        ],
      },
      {
        id: "construction-materials",
        name: "Construction Materials Calculators",
        icon: "🧱",
        calculators: [
          {
            id: "baluster-calculator",
            label: "Baluster Calculator",
            slug: "baluster",
            tagline: "Baluster count, spacing & building code compliance",
            description:
              "Calculate the exact number of balusters needed for straight and stair railings. Enforces the 4-inch sphere rule (IRC/IBC), supports 3 layout methods, and includes price estimation per baluster, pack, or box.",
            icon: "🪟",
            iconBg: "#fef3c7",
            iconColor: "#d97706",
            path: "/calculators/construction/baluster",
            keywords: [
              "baluster calculator", "baluster spacing", "railing calculator", "deck railing",
              "4-inch sphere rule", "IRC baluster", "spindle spacing", "stair railing calculator",
              "baluster count", "building code railing",
            ],
            available: true,
            badge: "New",
            badgeType: "new",
          },
          {
            id: "rebar-calculator",
            label: "Rebar Calculator",
            slug: "rebar",
            tagline: "Weight, length & cost for reinforcing steel",
            description:
              "Calculate rebar weight, total length, and material cost for concrete slabs, foundations, footings, walls, columns, and beams. Supports metric and US bar sizes, 3 calculation modes, and instant price estimation.",
            icon: "🪨",
            iconBg: "#fef3c7",
            iconColor: "#d97706",
            path: "/calculators/construction/rebar",
            keywords: [
              "rebar", "reinforcing steel", "rebar weight", "rebar calculator",
              "steel bar", "concrete reinforcement", "deformed bar", "ASTM A615",
            ],
            available: true,
            badge: "New",
            badgeType: "new",
          },
          {
            id: "rip-rap-calculator",
            label: "Rip Rap Calculator",
            slug: "rip-rap",
            tagline: "Rock size (D₅₀), volume & weight for rip rap",
            description:
              "Calculate the required median rock diameter (D₅₀) using the Isbash equation, or estimate rip rap volume, weight, and cost from area and depth. Supports metric and imperial units.",
            icon: "🪨",
            iconBg: "#f0f9ff",
            iconColor: "#0369a1",
            path: "/calculators/construction/rip-rap",
            keywords: [
              "rip rap calculator", "riprap", "D50", "rock size", "Isbash equation",
              "rip rap volume", "rip rap weight", "bank protection", "erosion control",
              "streambank", "channel lining", "rip rap depth", "rock armoring",
            ],
            available: true,
            badge: "New",
            badgeType: "new",
          },
          {
            id: "river-rock-calculator",
            label: "River Rock Calculator",
            slug: "river-rock",
            tagline: "Volume, weight & cost for river rock coverage",
            description:
              "Calculate how much river rock you need to cover any area. Enter length, width, and depth to get volume and weight. Supports 10 rock types with preset bulk densities, plus wastage and cost estimation.",
            icon: "🪨",
            iconBg: "#f0fdf4",
            iconColor: "#16a34a",
            path: "/calculators/construction/river-rock",
            keywords: [
              "river rock calculator", "river rock coverage", "river rock volume",
              "river rock weight", "landscaping rock", "gravel calculator",
              "pea gravel", "rock coverage calculator", "how much river rock",
            ],
            available: true,
            badge: "New",
            badgeType: "new",
          },
          {
            id: "brick-calculator",
            label: "Brick Calculator",
            slug: "brick",
            tagline: "Bricks needed, mortar materials & cost estimator",
            description:
              "Calculate the exact number of bricks for single or double walls using the standard area formula. Includes mortar material breakdown (cement, sand, water) and total cost estimation.",
            icon: "🧱",
            iconBg: "#fff7ed",
            iconColor: "#c2410c",
            path: "/calculators/construction/brick",
            keywords: [
              "brick calculator", "how many bricks", "bricks needed", "brick wall calculator",
              "mortar calculator", "brick cost", "single wall", "double wall", "masonry calculator",
            ],
            available: true,
            badge: "New",
            badgeType: "new",
          },
          {
            id: "aluminum-weight-calculator",
            label: "Aluminum Weight Calculator",
            slug: "aluminum-weight",
            tagline: "Weight by shape, alloy & dimensions",
            description:
              "Calculate the weight of aluminum bars, tubes, pipes, sheets, angles, channels, I-beams and more. Supports 12 alloys, 15 shapes, all unit systems, and instant price estimation.",
            icon: "⚖️",
            iconBg: "#f0f9ff",
            iconColor: "#0284c7",
            path: "/calculators/construction/aluminum-weight",
            legacyPath: "/tools/aluminum-weight-calculator",
            keywords: [
              "aluminum weight", "aluminium weight", "alloy density", "6061", "6063",
              "metal weight calculator", "bar weight", "tube weight", "sheet weight",
            ],
            available: true,
            badge: "New",
            badgeType: "new",
          },
          {
            id: "retaining-wall-calculator",
            label: "Retaining Wall Calculator",
            slug: "retaining-wall",
            tagline: "Material estimator for concrete, CMU, segmental & stone walls",
            description:
              "Estimate materials and costs for poured concrete, CMU block, segmental, mortared stone, and dry-stack retaining walls. Includes footing, drainage, backfill, and conceptual rebar estimates. For material quantity estimation only — not a structural design tool.",
            icon: "🧱",
            iconBg: "#fef3c7",
            iconColor: "#d97706",
            path: "/calculators/construction/retaining-wall",
            keywords: [
              "retaining wall calculator", "retaining wall materials", "concrete retaining wall",
              "CMU retaining wall", "segmental retaining wall", "stone retaining wall",
              "retaining wall cost", "retaining wall estimate", "block retaining wall",
            ],
            available: true,
            badge: "New",
            badgeType: "new",
          },
          {
            id: "decking-calculator",
            label: "Decking Calculator",
            slug: "decking",
            tagline: "Boards, fasteners & cost estimator for your deck",
            description:
              "Calculate how many decking boards you need, plus screws/nails or hidden clips, and total decking cost. Supports square-profile decking tiles and a 10% waste factor.",
            icon: "🪵",
            iconBg: "#fef3c7",
            iconColor: "#d97706",
            path: "/calculators/construction/decking",
            keywords: [
              "decking calculator", "deck boards calculator", "how many deck boards",
              "decking fasteners", "deck screws calculator", "hidden clips decking",
              "deck cost calculator", "composite decking calculator",
            ],
            available: true,
            badge: "New",
            badgeType: "new",
          },
          {
            id: "rolling-offset-calculator",
            label: "Rolling Offset Calculator",
            slug: "rolling-offset",
            tagline: "True offset, travel & run for pipe fitting",
            description:
              "Calculate the true offset, travel, and run for a rolling pipe offset from the horizontal (roll) and vertical (set) distances. Supports 22½°, 45°, 60°, 90°, and custom fitting bend angles.",
            icon: "📐",
            iconBg: "#eff6ff",
            iconColor: "#1d4ed8",
            path: "/calculators/construction/rolling-offset",
            keywords: [
              "rolling offset calculator", "pipe offset calculator", "true offset",
              "travel and run", "fitting bend angle", "pipefitting calculator",
              "45 degree offset", "22.5 degree offset", "pipe fitting travel",
            ],
            available: true,
            badge: "New",
            badgeType: "new",
          },
          {
            id: "diy-shed-cost-calculator",
            label: "DIY Shed Cost Calculator",
            slug: "diy-shed-cost",
            tagline: "Floor, wall & roof area plus material cost estimator",
            description:
              "Calculate the floor, wall, and roof area of a DIY shed and estimate the total material cost. Supports slanted, flat, and gable roof types with rafter length and overhang.",
            icon: "🏚️",
            iconBg: "#fef3c7",
            iconColor: "#d97706",
            path: "/calculators/construction/diy-shed-cost",
            keywords: [
              "diy shed cost calculator", "shed cost calculator", "shed building cost",
              "shed roof area", "shed wall area", "rafter length calculator",
              "gable roof shed", "slanted roof shed", "flat roof shed", "shed material cost",
            ],
            available: true,
            badge: "New",
            badgeType: "new",
          },
          {
            id: "sag-calculator",
            label: "SAG Calculator",
            slug: "sag",
            tagline: "Radius of curvature, diameter & sagitta solver",
            description:
              "Calculate the sagitta (SAG), radius of curvature, or diameter of a circular arc — enter any two values and the third is solved automatically. Useful for arches, curved roofs, and cable sag.",
            icon: "📏",
            iconBg: "#eff6ff",
            iconColor: "#1d4ed8",
            path: "/calculators/construction/sag",
            keywords: [
              "sag calculator", "sagitta calculator", "radius of curvature",
              "arc sag", "chord sag", "circular arc calculator", "arch calculator",
              "cable sag", "curved roof sag",
            ],
            available: true,
            badge: "New",
            badgeType: "new",
          },
          {
            id: "board-and-batten-calculator",
            label: "Board and Batten Calculator",
            slug: "board-and-batten",
            tagline: "Boards, battens, trim, fasteners & paint estimator",
            description:
              "Calculate board and batten siding material quantities. Supports multiple walls, openings, 7 board profiles, full North American lumber database, layout engine, trim estimator, fastener estimator, and paint/stain estimator.",
            icon: "🪵",
            iconBg: "#fef3c7",
            iconColor: "#d97706",
            path: "/calculators/construction/board-and-batten",
            keywords: [
              "board and batten", "board and batten calculator", "siding calculator",
              "batten spacing", "board siding", "exterior siding", "lumber estimator",
              "board batten siding", "T&G siding", "shiplap calculator", "trim estimator",
            ],
            available: true,
            badge: "New",
            badgeType: "new",
          },
          {
            id: "drywall-calculator",
            label: "Drywall Calculator",
            slug: "drywall",
            tagline: "Panels, doors, windows & cost estimator",
            description:
              "Calculate how much drywall you need from room dimensions, sloped-wall areas, doors, and windows. Supports 9 standard metric panel sizes plus instant cost estimation.",
            icon: "🧱",
            iconBg: "#eff6ff",
            iconColor: "#1d4ed8",
            path: "/calculators/construction/drywall",
            keywords: [
              "drywall calculator", "sheetrock calculator", "how much drywall",
              "drywall panels", "drywall sheets", "gypsum board calculator",
              "drywall cost calculator", "room surface area", "drywall estimator",
            ],
            available: true,
            badge: "New",
            badgeType: "new",
          },
          {
            id: "sand-calculator",
            label: "Sand Calculator",
            slug: "sand",
            tagline: "Volume, weight & cost for sand fill",
            description:
              "Calculate how much sand you need from length, width, and depth. Get the volume and weight needed based on density, plus instant cost estimation by weight or by volume.",
            icon: "🏖️",
            iconBg: "#fff7ed",
            iconColor: "#d97706",
            path: "/calculators/construction/sand",
            keywords: [
              "sand calculator", "how much sand", "sand volume", "sand weight",
              "sand cost calculator", "sand density", "sand bags calculator",
              "fill sand calculator", "sand fill",
            ],
            available: true,
            badge: "New",
            badgeType: "new",
          },
          {
            id: "fire-glass-calculator",
            label: "Fire Glass Calculator",
            slug: "fire-glass",
            tagline: "Volume & weight for rectangular, round & more fire pits",
            description:
              "Calculate how much fire glass you need for rectangular, square, round, triangular, or trapezoidal fire pits. Supports reflective and recycled glass density presets, plus a custom density option.",
            icon: "🔥",
            iconBg: "#fff7ed",
            iconColor: "#ea580c",
            path: "/calculators/construction/fire-glass",
            keywords: [
              "fire glass calculator", "fire pit glass calculator", "how much fire glass",
              "fire glass volume", "fire glass weight", "reflective fire glass",
              "recycled fire glass", "fire pit calculator",
            ],
            available: true,
            badge: "New",
            badgeType: "new",
          },
          {
            id: "glass-weight-calculator",
            label: "Glass Weight Calculator",
            slug: "glass-weight",
            tagline: "Weight by glass type, shape & dimensions",
            description:
              "Calculate the weight of a glass sheet or piece from its type, shape, and dimensions. Supports 19 glass types (annealed, tempered, laminated, and more) with reference densities, 8 shapes including rectangular, circular, and round rod, plus a quantity multiplier.",
            icon: "🪟",
            iconBg: "#eff6ff",
            iconColor: "#1d4ed8",
            path: "/calculators/construction/glass-weight",
            keywords: [
              "glass weight calculator", "how much does glass weigh", "glass weight",
              "glass density calculator", "tempered glass weight", "laminated glass weight",
              "annealed glass weight", "window glass weight", "glass sheet weight calculator",
            ],
            available: true,
            badge: "New",
            badgeType: "new",
          },
          {
            id: "sealant-calculator",
            label: "Sealant Calculator",
            slug: "sealant",
            tagline: "Volume, packages & cost for caulk and sealant joints",
            description:
              "Calculate how much sealant you need from joint length, width, and depth. Supports wastage, 10 standard cartridge/sausage/pail package sizes plus a custom tube volume, and instant cost estimation.",
            icon: "🧴",
            iconBg: "#eff6ff",
            iconColor: "#1d4ed8",
            path: "/calculators/construction/sealant",
            keywords: [
              "sealant calculator", "caulk calculator", "how much sealant",
              "sealant volume", "sealant cartridges", "sealant cost calculator",
              "caulk cartridge calculator", "sausage sealant", "joint sealant",
            ],
            available: true,
            badge: "New",
            badgeType: "new",
          },
          {
            id: "framing-calculator",
            label: "Framing Calculator",
            slug: "framing",
            tagline: "Studs needed & cost for wall framing",
            description:
              "Calculate how many wall studs you need from wall length and on-center (OC) spacing, plus estimated waste and total cost. Standard 16″, 19.2″, and 24″ OC spacings supported.",
            icon: "🪵",
            iconBg: "#fef3c7",
            iconColor: "#d97706",
            path: "/calculators/construction/framing",
            keywords: [
              "framing calculator", "stud calculator", "how many studs",
              "wall framing calculator", "OC spacing", "on-center spacing",
              "stud cost calculator", "16 inch OC", "24 inch OC", "wall stud count",
            ],
            available: true,
            badge: "New",
            badgeType: "new",
          },
          {
            id: "sonotube-calculator",
            label: "Sonotube Calculator",
            slug: "sonotube",
            tagline: "Concrete volume, bags & cost for tube forms",
            description:
              "Calculate concrete volume and weight for round Sonotube® forms from diameter, height, and quantity. Supports pre-mixed bag counts or a cement/sand/gravel mix ratio breakdown, plus instant cost estimation.",
            icon: "🧱",
            iconBg: "#f0f9ff",
            iconColor: "#0369a1",
            path: "/calculators/construction/sonotube",
            keywords: [
              "sonotube calculator", "concrete tube calculator", "concrete form calculator",
              "how much concrete", "concrete pier calculator", "concrete footing calculator",
              "concrete bags needed", "cement sand gravel ratio", "round column concrete",
            ],
            available: true,
            badge: "New",
            badgeType: "new",
          },
          {
            id: "french-drain-calculator",
            label: "French Drain Calculator",
            slug: "french-drain",
            tagline: "Trench volume, pipe, gravel & cost for drainage",
            description:
              "Calculate trench volume, drain pipe quantity, and gravel needed for a French drain from trench width, depth, and length. Supports Schedule 40 and SDR35 pipe, optional fabric filter, and instant cost estimation.",
            icon: "🚰",
            iconBg: "#f0f9ff",
            iconColor: "#0369a1",
            path: "/calculators/construction/french-drain",
            keywords: [
              "french drain calculator", "drain pipe calculator", "trench volume calculator",
              "gravel needed calculator", "perforated pipe calculator", "drainage calculator",
              "geotextile fabric calculator", "yard drainage", "foundation drain calculator",
            ],
            available: true,
            badge: "New",
            badgeType: "new",
          },
        ],
      },
    ],
  },
  {
    id: "everyday-life",
    name: "Everyday Life Calculators",
    slug: "everyday-life",
    path: "/calculators/everyday-life",
    tagline: "Anniversaries, numerology & personal milestones",
    description:
      "Free everyday calculators for anniversaries, numerology, life path numbers, destiny matrix, and personal milestones.",
    icon: "🌅",
    iconBg: "#fff0f5",
    iconColor: "#e11d48",
    calculators: [
      {
        id: "anniversary-calculator",
        label: "Anniversary Calculator",
        slug: "anniversary",
        tagline: "Exact dates, countdowns, milestones & gifts",
        description:
          "Calculate exact anniversary time in years, months, weeks and days for weddings, relationships, work and more — with live countdown, milestone tracker, traditional & modern gift guide, timeline, statistics, and calendar export (.ics).",
        icon: "💑",
        iconBg: "#fff0f5",
        iconColor: "#e11d48",
        path: "/calculators/everyday-life/anniversary",
        legacyPath: "/tools/anniversary-calculator",
        keywords: ["anniversary", "wedding anniversary calculator", "relationship anniversary calculator", "days together calculator", "years together calculator", "milestone", "countdown", "calendar"],
        available: true,
        badge: "New",
        badgeType: "new",
      },
      {
        id: "destiny-matrix",
        label: "Destiny Matrix Calculator",
        slug: "destiny-matrix",
        tagline: "Life Path, Numerology Chart & Karmic Reading",
        description:
          "Discover your Life Path, Destiny, Soul Urge and Personality numbers. Get your Pythagoras Matrix, karmic lessons, and full numerology reading.",
        icon: "✦",
        iconBg: "#eef2ff",
        iconColor: "#6366f1",
        path: "/calculators/everyday-life/destiny-matrix",
        legacyPath: "/tools/destiny-matrix",
        keywords: ["destiny matrix", "numerology", "life path", "karmic", "pythagoras"],
        available: true,
        badge: "New",
        badgeType: "new",
      },
    ],
  },
  {
    id: "financial",
    name: "Financial Calculators",
    slug: "financial",
    path: "/calculators/financial",
    tagline: "Mortgage payments, amortization & loan payoff",
    description:
      "Free financial calculators — mortgage payment estimator with taxes, insurance, PMI, extra payments, and a full amortization schedule.",
    icon: "💰",
    iconBg: "#f0fdf4",
    iconColor: "#16a34a",
    calculators: [
      {
        id: "mortgage-calculator",
        label: "Mortgage Calculator",
        slug: "mortgage-calculator",
        tagline: "Monthly payment, taxes, PMI, extra payments & amortization",
        description:
          "Calculate your monthly mortgage payment including property taxes, home insurance, PMI, HOA fees, and other costs. Model extra payments and biweekly payoff, and view a full monthly or annual amortization schedule.",
        icon: "🏠",
        iconBg: "#f0fdf4",
        iconColor: "#16a34a",
        path: "/calculators/financial/mortgage-calculator",
        legacyPath: "/tools/mortgage-calculator",
        keywords: [
          "mortgage calculator", "monthly mortgage payment", "amortization schedule",
          "mortgage payoff calculator", "PMI calculator", "extra payment mortgage calculator",
          "biweekly mortgage calculator", "home loan calculator",
        ],
        available: true,
        badge: "New",
        badgeType: "new",
      },
      {
        id: "loan-calculator",
        label: "Loan Calculator",
        slug: "loan-calculator",
        tagline: "Amortized loans, deferred payment loans & bond pricing",
        description:
          "Calculate amortized loan payments with any compound and pay-back frequency, deferred payment loans due in full at maturity, and bond present values from a known face value — with a full period-by-period schedule table.",
        icon: "💵",
        iconBg: "#f0fdf4",
        iconColor: "#16a34a",
        path: "/calculators/financial/loan-calculator",
        legacyPath: "/tools/loan-calculator",
        keywords: [
          "loan calculator", "amortized loan calculator", "loan payment calculator",
          "deferred payment loan", "bond calculator", "bond present value calculator",
          "loan amortization schedule", "loan interest calculator",
        ],
        available: true,
        badge: "New",
        badgeType: "new",
      },
    ],
  },
  {
    id: "garden",
    name: "Garden Calculators",
    slug: "garden",
    path: "/calculators/garden",
    tagline: "Grow a Garden plant values, pet XP, egg hatch & more",
    description:
      "Free calculators for the Grow a Garden Roblox game — plant/crop value with mutations, pet XP growth time, egg hatch speed, pet weight by age, and pet ability stats.",
    icon: "🌾",
    iconBg: "#f0fdf4",
    iconColor: "#22c55e",
    calculators: [
      {
        id: "grow-a-garden-calculator",
        label: "Grow A Garden Calculator",
        slug: "grow-a-garden-calculator",
        tagline: "Plant value, mutations, pet XP, egg hatch & pet ability",
        description:
          "Calculate Grow a Garden plant/crop values with weight and mutations, pet XP growth time, egg hatch speed, pet weight by age, and pet ability stats — all in one free calculator.",
        icon: "🌾",
        iconBg: "#f0fdf4",
        iconColor: "#22c55e",
        path: "/calculators/garden/grow-a-garden-calculator",
        legacyPath: "/tools/grow-a-garden-calculator",
        keywords: ["grow a garden calculator", "grow a garden value calculator", "grow a garden mutations", "grow a garden pet xp", "grow a garden egg hatch", "roblox grow a garden"],
        available: true,
        badge: "New",
        badgeType: "new",
      },
    ],
  },
];

export function getCategoryBySlug(slug) {
  return CALCULATOR_CATEGORIES.find((c) => c.slug === slug) || null;
}

export function getCategoryCalculators(category) {
  if (category.calculators) return category.calculators;
  if (category.groups) return category.groups.flatMap((g) => g.calculators);
  return [];
}

export function getCalculatorBySlug(categorySlug, calcSlug) {
  const category = getCategoryBySlug(categorySlug);
  if (!category) return null;
  return getCategoryCalculators(category).find((c) => c.slug === calcSlug) || null;
}

export function getAllCalculators() {
  return CALCULATOR_CATEGORIES.flatMap((c) =>
    getCategoryCalculators(c).map((calc) => ({
      ...calc,
      categoryId: c.id,
      categoryName: c.name,
      categoryPath: c.path,
    }))
  );
}
