// Export helpers for Sentence Counter — TXT/CSV/JSON use the same
// Blob + URL.createObjectURL + <a download> pattern already used by the
// Anniversary Calculator's .ics export elsewhere in this project. "PDF"
// export uses the browser's native print-to-PDF (no client-side PDF
// library exists anywhere in this codebase yet, so this avoids adding one).

function downloadBlob(content, filename, mime) {
  const blob = new Blob([content], { type: `${mime};charset=utf-8` });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

function csvEscape(value) {
  let s = String(value ?? "");
  // Neutralize CSV/formula injection: a sentence typed by the user could
  // start with =, +, -, or @, which spreadsheet apps treat as a formula.
  if (/^[=+\-@]/.test(s)) s = `'${s}`;
  if (/[",\n]/.test(s)) return `"${s.replace(/"/g, '""')}"`;
  return s;
}

export function exportSentencesTxt(analysis) {
  const lines = analysis.sentences.map((s) => `${s.index}. ${s.text}`);
  downloadBlob(lines.join("\n\n"), "sentence-counter-sentences.txt", "text/plain");
}

export function exportSentencesCsv(analysis) {
  const header = ["Sentence Number", "Sentence", "Word Count", "Character Count", "Estimated Reading Time (sec)"];
  const rows = analysis.sentences.map((s) => [
    s.index,
    s.text,
    s.words,
    s.chars,
    Math.round((s.words / 225) * 60),
  ]);
  const csv = [header, ...rows].map((row) => row.map(csvEscape).join(",")).join("\n");
  downloadBlob(csv, "sentence-counter-sentences.csv", "text/csv");
}

export function exportAnalysisJson(analysis) {
  const payload = {
    counts: analysis.counts,
    averages: analysis.averages,
    readability: analysis.readability,
    vocabulary: analysis.vocabulary,
    complexity: {
      ...analysis.complexity,
      longestSentence: analysis.complexity.longestSentence?.text ?? null,
      shortestSentence: analysis.complexity.shortestSentence?.text ?? null,
    },
    distribution: analysis.distribution,
    sentences: analysis.sentences,
  };
  downloadBlob(JSON.stringify(payload, null, 2), "sentence-counter-analysis.json", "application/json");
}

export function exportStatsTxt(analysis) {
  const { counts, averages, readability } = analysis;
  const lines = [
    "SENTENCE COUNTER — STATISTICS",
    "",
    `Sentences: ${counts.sentences}`,
    `Paragraphs: ${counts.paragraphs}`,
    `Words: ${counts.words}`,
    `Characters (with spaces): ${counts.chars}`,
    `Characters (no spaces): ${counts.charsNoSpaces}`,
    `Lines: ${counts.lines}`,
    `Non-empty lines: ${counts.nonEmptyLines}`,
    "",
    `Average words per sentence: ${averages.wordsPerSentence}`,
    `Average characters per sentence: ${averages.charsPerSentence}`,
    `Average sentences per paragraph: ${averages.sentencesPerParagraph}`,
    `Average words per paragraph: ${averages.wordsPerParagraph}`,
    `Sentence density (per 100 words): ${averages.sentenceDensity}`,
  ];
  if (readability) {
    lines.push(
      "",
      `Flesch Reading Ease: ${readability.flesch.score} (${readability.flesch.level})`,
      `Flesch-Kincaid Grade: ${readability.fkGrade.score} (${readability.fkGrade.label})`,
      `Gunning Fog Index: ${readability.fog.score} (${readability.fog.label})`,
      `SMOG Index: ${readability.smog.score} (${readability.smog.label})`,
      `Coleman-Liau Index: ${readability.colemanLiau.score} (${readability.colemanLiau.label})`,
      `Automated Readability Index: ${readability.ari.score} (${readability.ari.label})`,
    );
  }
  downloadBlob(lines.join("\n"), "sentence-counter-statistics.txt", "text/plain");
}

export function printAnalysis(analysis) {
  const { counts, averages, readability } = analysis;
  const win = window.open("", "_blank", "width=800,height=900");
  if (!win) return;

  const row = (label, value) => `<tr><td>${label}</td><td>${value}</td></tr>`;

  win.document.write(`<!doctype html>
<html>
<head>
<meta charset="utf-8">
<title>Sentence Counter — Statistics</title>
<style>
  body { font-family: -apple-system, Segoe UI, Arial, sans-serif; color: #111; padding: 32px; }
  h1 { font-size: 20px; margin-bottom: 4px; }
  h2 { font-size: 15px; margin: 24px 0 8px; }
  table { border-collapse: collapse; width: 100%; margin-bottom: 8px; }
  td { padding: 6px 10px; border-bottom: 1px solid #e5e5e5; font-size: 13px; }
  td:first-child { color: #555; }
  td:last-child { text-align: right; font-weight: 600; }
</style>
</head>
<body>
  <h1>Sentence Counter — Statistics</h1>
  <p style="color:#777;font-size:12px;">Generated by Tolz.org</p>
  <h2>Text Statistics</h2>
  <table>
    ${row("Sentences", counts.sentences)}
    ${row("Paragraphs", counts.paragraphs)}
    ${row("Words", counts.words)}
    ${row("Characters (with spaces)", counts.chars)}
    ${row("Characters (no spaces)", counts.charsNoSpaces)}
    ${row("Lines", counts.lines)}
    ${row("Average words per sentence", averages.wordsPerSentence)}
    ${row("Average sentences per paragraph", averages.sentencesPerParagraph)}
    ${row("Sentence density (per 100 words)", averages.sentenceDensity)}
  </table>
  ${readability ? `
  <h2>Readability</h2>
  <table>
    ${row("Flesch Reading Ease", `${readability.flesch.score} (${readability.flesch.level})`)}
    ${row("Flesch-Kincaid Grade", `${readability.fkGrade.score} (${readability.fkGrade.label})`)}
    ${row("Gunning Fog Index", `${readability.fog.score} (${readability.fog.label})`)}
    ${row("SMOG Index", `${readability.smog.score} (${readability.smog.label})`)}
    ${row("Coleman-Liau Index", `${readability.colemanLiau.score} (${readability.colemanLiau.label})`)}
    ${row("Automated Readability Index", `${readability.ari.score} (${readability.ari.label})`)}
  </table>` : ""}
</body>
</html>`);
  win.document.close();
  win.focus();
  setTimeout(() => win.print(), 300);
}
