// Central tool registry — add new tools here, they auto-appear everywhere

export const CATEGORIES = [
  { id: "all",       label: "All Tools" },
  { id: "image",     label: "Image" },
  { id: "pdf",       label: "PDF" },
  { id: "converter", label: "Converters" },
  { id: "health",    label: "Health" },
  { id: "utility",   label: "Calculators", subCategories: [
    { id: "health-calc",       label: "Health Calculators",          path: "/calculators/health" },
    { id: "everyday",          label: "Everyday Life Calculators",   path: "/calculators/everyday-life" },
    { id: "construction-calc", label: "Construction Calculators",    path: "/calculators/construction" },
    { id: "garden-calc",       label: "Garden Calculators",          path: "/calculators/garden" },
    { id: "financial-calc",    label: "Financial Calculators",       path: "/calculators/financial" },
  ]},
  { id: "url-tools",  label: "URL Tools" },
  { id: "text-tools",   label: "Text Tools" },
  { id: "design-tools", label: "Design Tools" },
  { id: "gaming-tools", label: "Gaming Tools" },
  { id: "naming-tools", label: "Naming Tools" },
  { id: "excel-tools", label: "Excel Tools" },
];

export const TOOLS = [
  {
    id: "image-compressor",
    label: "Image Compressor",
    tagline: "Reduce image size without quality loss",
    description: "Compress JPEG, PNG, and WebP images by up to 80% while keeping them visually perfect. Batch compress up to 10 images at once.",
    icon: "🖼",
    iconBg: "#f3f0ff",
    iconColor: "#8b5cf6",
    category: "image",
    badge: "New",
    badgeType: "new",
    path: "/tools/image-compressor",
    available: true,
    keywords: ["compress image", "reduce image size", "shrink photo", "optimize image", "jpeg compressor", "png compressor", "reduce file size"],
  },
  {
    id: "id-photo-generator",
    label: "ID Photo Generator (Print Studio)",
    tagline: "Passport, visa & ID photo print sheets",
    description: "Crop your photo to official passport, visa, ID, or studio photo templates, lay out multiple copies on a print sheet with correct margins and safe/cut/bleed guides, and export a print-ready PDF, PNG, or JPEG.",
    icon: "🪪",
    iconBg: "#f0f9ff",
    iconColor: "#0369a1",
    category: "image",
    subCategory: "print-studio",
    badge: "New",
    badgeType: "new",
    path: "/tools/id-photo-generator",
    available: true,
    keywords: ["remove background", "background remover", "transparent background", "passport photo", "visa photo", "id photo maker", "photo print sheet"],
  },
  {
    id: "image-converter",
    label: "Image Converter",
    tagline: "JPG, PNG, HEIC, PDF, OCR & more",
    description: "Convert images to JPG, PNG, PDF, extract text via OCR, and more — 8 tools in one. Free, fast, no signup.",
    icon: "🔄",
    iconBg: "#fef3c7",
    iconColor: "#d97706",
    category: "image",
    badge: "New",
    badgeType: "new",
    path: "/tools/image-converter",
    available: true,
    keywords: ["convert image", "jpg to png", "png to jpg", "heic to jpg", "image to pdf", "ocr", "extract text from image"],
  },
  {
    id: "pdf-merge",
    label: "Merge PDF",
    tagline: "Combine multiple PDFs into one",
    description: "Upload multiple PDFs, drag to reorder, and merge them into a single file instantly. Free, fast, no signup.",
    icon: "📄",
    iconBg: "#eff6ff",
    iconColor: "#3b7bfc",
    category: "pdf",
    badge: "New",
    badgeType: "new",
    path: "/tools/pdf-merge",
    available: true,
    keywords: ["pdf merge", "merge pdf", "combine pdf", "join pdf", "pdf merger", "pdf combiner"],
  },
  {
    id: "pdf-compress",
    label: "Compress PDF",
    tagline: "Reduce PDF file size",
    description: "Reduce file size while optimizing for maximal PDF quality. Easy, fast, and free.",
    icon: "📦",
    iconBg: "#eff6ff",
    iconColor: "#3b7bfc",
    category: "pdf",
    badge: "New",
    badgeType: "new",
    path: "/tools/pdf-compress",
    available: true,
    keywords: ["compress pdf", "reduce pdf size", "shrink pdf", "pdf compressor", "pdf file size"],
  },
  {
    id: "pdf-split",
    label: "Split PDF",
    tagline: "Separate PDF pages",
    description: "Separate one page or a whole set for easy conversion into independent PDF files.",
    icon: "✂️",
    iconBg: "#eff6ff",
    iconColor: "#3b7bfc",
    category: "pdf",
    badge: "New",
    badgeType: "new",
    path: "/tools/pdf-split",
    available: true,
    keywords: ["split pdf", "separate pdf pages", "extract pdf pages", "pdf splitter", "divide pdf"],
  },
  {
    id: "pdf-to-word",
    label: "PDF to Word",
    tagline: "Convert PDF to editable DOCX",
    description: "Convert PDF files to editable Word documents (.docx). Preserves text, paragraphs, and structure. Batch convert up to 20 PDFs. Free, fast, no signup.",
    icon: "📝",
    iconBg: "#e0f2fe",
    iconColor: "#0284c7",
    category: "pdf",
    badge: "New",
    badgeType: "new",
    path: "/tools/pdf-to-word",
    available: true,
    keywords: ["pdf to word", "pdf to docx", "convert pdf to word", "pdf to doc", "editable pdf"],
  },
  {
    id: "calorie-tracker",
    label: "Calorie Tracker & Calculator",
    tagline: "BMI, TDEE, Macros, Water & Meal Planner",
    description: "Calculate your BMI, daily calorie needs (TDEE), macro breakdown, water intake and get healthy meal suggestions — all in one free tool.",
    icon: "🥗",
    iconBg: "#f0fdf4",
    iconColor: "#22c55e",
    category: "utility",
    subCategory: "health-calc",
    badge: "New",
    badgeType: "new",
    path: "/tools/calorie-tracker",
    available: true,
  },
  {
    id: "sleep-calculator",
    label: "Sleep Calculator",
    tagline: "Optimal sleep & wake-up times based on sleep cycles",
    description: "Find the best time to go to sleep or wake up based on 90-minute sleep cycles. Get personalized schedules for 4, 5, or 6 cycles — wake up refreshed, not groggy.",
    icon: "🌙",
    iconBg: "#eef2ff",
    iconColor: "#6366f1",
    category: "utility",
    subCategory: "health-calc",
    badge: "New",
    badgeType: "new",
    path: "/tools/sleep-calculator",
    available: true,
  },
  {
    id: "destiny-matrix",
    label: "Destiny Matrix Calculator",
    tagline: "Life Path, Numerology Chart & Karmic Reading",
    description: "Discover your Life Path, Destiny, Soul Urge and Personality numbers. Get your Pythagoras Matrix, karmic lessons, energy analysis and full numerology reading — instantly free.",
    icon: "✦",
    iconBg: "#eef2ff",
    iconColor: "#6366f1",
    category: "utility",
    subCategory: "everyday",
    badge: "New",
    badgeType: "new",
    path: "/tools/destiny-matrix",
    available: true,
  },
  {
    id: "url-shortener",
    label: "URL Shortener",
    tagline: "Shorten any long link instantly",
    description: "Create short, clean, shareable links from any URL in seconds. Custom aliases, expiration, QR codes — no signup required.",
    icon: "🔗",
    iconBg: "#f0fdf4",
    iconColor: "#22c55e",
    category: "url-tools",
    badge: "New",
    badgeType: "new",
    path: "/tools/url-shortener",
    available: true,
    keywords: ["url shortener", "shorten link", "short url", "link shortener", "custom alias"],
  },
  {
    id: "word-counter",
    label: "Word Counter",
    tagline: "Words, characters, sentences & reading time",
    description: "Instantly count words, characters, sentences, paragraphs, and estimate reading time. Supports .txt and .md file upload. No signup required.",
    icon: "📝",
    iconBg: "#fefce8",
    iconColor: "#ca8a04",
    category: "text-tools",
    badge: "New",
    badgeType: "new",
    path: "/tools/word-counter",
    available: true,
    keywords: ["word counter", "word count", "character count", "count words", "text length"],
  },
  {
    id: "sentence-counter",
    label: "Sentence Counter",
    tagline: "Sentence, paragraph & readability analysis",
    description: "Count sentences and paragraphs, analyze readability (Flesch, Fog, SMOG & more), and get sentence-length insights in real time. No signup required.",
    icon: "🔤",
    iconBg: "#eff6ff",
    iconColor: "#3b7bfc",
    category: "text-tools",
    badge: "New",
    badgeType: "new",
    path: "/tools/sentence-counter",
    available: true,
    keywords: ["sentence counter", "count sentences", "readability score", "flesch reading ease", "sentence length"],
  },
  {
    id: "word-finder",
    label: "Word Finder",
    tagline: "Unscramble letters and solve word games",
    description: "Find words by starting letters, ending letters, included letters, or a fill-in-the-blanks pattern. Free word finder for Scrabble, Words With Friends, crosswords, and Wordle. No signup required.",
    icon: "🔎",
    iconBg: "#eef6ff",
    iconColor: "#2f7fe0",
    category: "text-tools",
    badge: "New",
    badgeType: "new",
    path: "/tools/word-finder",
    available: true,
    keywords: ["word finder", "unscramble letters", "word unscrambler", "scrabble word finder", "words with friends helper", "wordle solver", "fill in the blanks word finder"],
  },
  {
    id: "qr-generator",
    label: "QR Generator",
    tagline: "URLs, text, WiFi, email, phone — instantly",
    description: "Generate customizable QR codes for any URL, text, email, phone, or WiFi credentials. Download as PNG or SVG. No signup required.",
    icon: "⬛",
    iconBg: "#f0fdf4",
    iconColor: "#16a34a",
    category: "url-tools",
    badge: "New",
    badgeType: "new",
    path: "/tools/qr-generator",
    available: true,
    keywords: ["qr code", "qr code generator", "generate qr code", "wifi qr code", "make qr code"],
  },
  {
    id: "unit-converter",
    label: "Unit Converter",
    tagline: "Length, weight, temperature, data & more",
    description: "Convert 12 unit categories instantly — length, weight, temperature, area, volume, speed, time, data, energy, pressure, angle and frequency. Real-time bidirectional conversion.",
    icon: "⚖️",
    iconBg: "#fff7ed",
    iconColor: "#f59e0b",
    category: "converter",
    badge: "New",
    badgeType: "new",
    path: "/tools/unit-converter",
    available: true,
    keywords: ["unit converter", "convert units", "length converter", "temperature converter", "metric to imperial"],
  },
  {
    id: "color-picker",
    label: "Color Picker",
    tagline: "HEX, RGB, HSL · palettes · WCAG contrast",
    description: "Pick colors visually, convert between HEX, RGB and HSL, generate complementary palettes, check WCAG accessibility contrast, and save session favorites — all in-browser, no upload.",
    icon: "🎨",
    iconBg: "#f3f0ff",
    iconColor: "#7c3aed",
    category: "design-tools",
    badge: "New",
    badgeType: "new",
    path: "/tools/color-picker",
    available: true,
    keywords: ["color picker", "hex to rgb", "color palette generator", "contrast checker", "eyedropper"],
  },
  {
    id: "anniversary-calculator",
    label: "Anniversary Calculator",
    tagline: "Exact dates, countdowns, milestones & gifts",
    description: "Calculate exact anniversary time in years, months, weeks and days for weddings, relationships, work and more — with live countdown, milestone tracker, traditional & modern gift guide, timeline, statistics, and calendar export (.ics).",
    icon: "💑",
    iconBg: "#fff0f5",
    iconColor: "#e11d48",
    category: "utility",
    subCategory: "everyday",
    badge: "New",
    badgeType: "new",
    path: "/tools/anniversary-calculator",
    available: true,
  },
  {
    id: "square-yards-calculator",
    label: "Square Yards Calculator",
    tagline: "Sod, carpet, tile, flooring & landscaping",
    description: "Calculate area in square yards for 10 shapes: rectangle, square, circle, triangle, trapezoid, ellipse, semi-circle, L-shape, ring, and custom. Built-in material estimator for sod, carpet, tile, mulch, gravel, and artificial grass.",
    icon: "🌿",
    iconBg: "#f0fdf4",
    iconColor: "#16a34a",
    category: "utility",
    subCategory: "construction-calc",
    badge: "New",
    badgeType: "new",
    path: "/tools/square-yards-calculator",
    available: true,
  },
  {
    id: "square-footage-calculator",
    label: "Square Footage Calculator",
    tagline: "Area for any shape — floor, roof, land",
    description: "Calculate square footage for 10 shapes: rectangle, square, circle, triangle, trapezoid, ellipse, semi-circle, L-shape, ring, and custom polygon. Supports all unit systems with instant results.",
    icon: "📐",
    iconBg: "#eff6ff",
    iconColor: "#3b7bfc",
    category: "utility",
    subCategory: "construction-calc",
    badge: "New",
    badgeType: "new",
    path: "/tools/square-footage-calculator",
    available: true,
  },
  {
    id: "gallons-calculator",
    label: "Gallons per Sq Ft Calculator",
    tagline: "Paint, sealers, epoxy & coating coverage",
    description: "Calculate gallons per square foot, total gallons needed, and coverage area for paint, primer, epoxy, concrete sealers, waterproofing, and more. Supports US gal, imperial gal, liters, and all major units.",
    icon: "🪣",
    iconBg: "#eff6ff",
    iconColor: "#3b7bfc",
    category: "utility",
    subCategory: "construction-calc",
    badge: "New",
    badgeType: "new",
    path: "/tools/gallons-calculator",
    available: true,
  },
  {
    id: "cubic-yard-calculator",
    label: "Cubic Yard Calculator",
    tagline: "Concrete, gravel, sand, soil & more",
    description: "Calculate volume in cubic yards for concrete, gravel, sand, soil, mulch and fill dirt. Supports feet, inches, yards, meters and centimeters. Instant results with material weight estimates.",
    icon: "📐",
    iconBg: "#f0fdf4",
    iconColor: "#16a34a",
    category: "utility",
    subCategory: "construction-calc",
    badge: "New",
    badgeType: "new",
    path: "/tools/cubic-yard-calculator",
    available: true,
  },
  {
    id: "sqft-to-cubic-yards",
    label: "Sq Ft to Cubic Yards Calculator",
    tagline: "Concrete, gravel, sand, soil & more",
    description: "Convert square feet and depth into cubic yards instantly. Supports Length×Width or direct area entry, 10 volume output units, material weight estimator (concrete, gravel, sand, topsoil, mulch). No Calculate button — instant results.",
    icon: "🧱",
    iconBg: "#f0fdf4",
    iconColor: "#16a34a",
    category: "utility",
    subCategory: "construction-calc",
    badge: "New",
    badgeType: "new",
    path: "/tools/sqft-to-cubic-yards",
    available: true,
  },
  {
    id: "size-to-weight-calculator",
    label: "Size to Weight Calculator",
    tagline: "Weight of steel, aluminum, concrete & more",
    description: "Calculate the weight of any rectangular solid from its dimensions and material density. Supports 20+ materials (steel, aluminum, concrete, wood, plastics), all major unit systems, and instant results.",
    icon: "⚖️",
    iconBg: "#fef3c7",
    iconColor: "#d97706",
    category: "utility",
    subCategory: "construction-calc",
    badge: "New",
    badgeType: "new",
    path: "/tools/size-to-weight-calculator",
    available: true,
  },
  {
    id: "baluster-calculator",
    label: "Baluster Calculator",
    tagline: "Baluster count, spacing & building code compliance",
    description:
      "Calculate the exact number of balusters for straight or stair railings. Enforces the 4-inch sphere rule (IRC/IBC), supports Equal End Margins, Fixed Offsets, and Centered layouts. Includes instant price estimation per baluster, pack, or box.",
    icon: "🪟",
    iconBg: "#fef3c7",
    iconColor: "#d97706",
    category: "utility",
    subCategory: "construction-materials",
    badge: "New",
    badgeType: "new",
    path: "/calculators/construction/baluster",
    available: true,
  },
  {
    id: "river-rock-calculator",
    label: "River Rock Calculator",
    tagline: "Volume, weight & cost for river rock coverage",
    description:
      "Calculate how much river rock you need to cover any area. Enter length, width, and depth to get volume and weight. Supports 10 rock types with preset bulk densities, plus wastage and cost estimation.",
    icon: "🪨",
    iconBg: "#f0fdf4",
    iconColor: "#16a34a",
    category: "utility",
    subCategory: "construction-materials",
    badge: "New",
    badgeType: "new",
    path: "/calculators/construction/river-rock",
    available: true,
  },
  {
    id: "brick-calculator",
    label: "Brick Calculator",
    tagline: "Bricks needed, mortar materials & cost estimator",
    description:
      "Calculate the exact number of bricks for single or double walls using the standard area formula. Includes mortar material breakdown (cement, sand, water) and total cost estimation.",
    icon: "🧱",
    iconBg: "#fff7ed",
    iconColor: "#c2410c",
    category: "utility",
    subCategory: "construction-materials",
    badge: "New",
    badgeType: "new",
    path: "/calculators/construction/brick",
    available: true,
  },
  {
    id: "rip-rap-calculator",
    label: "Rip Rap Calculator",
    tagline: "Rock size (D₅₀), volume & weight for rip rap",
    description:
      "Calculate the required median rock diameter (D₅₀) using the Isbash equation, or estimate rip rap volume, weight, and cost from area and depth. Supports metric and imperial units.",
    icon: "🪨",
    iconBg: "#f0f9ff",
    iconColor: "#0369a1",
    category: "utility",
    subCategory: "construction-materials",
    badge: "New",
    badgeType: "new",
    path: "/calculators/construction/rip-rap",
    available: true,
  },
  {
    id: "rebar-calculator",
    label: "Rebar Calculator",
    tagline: "Weight, length & cost for reinforcing steel",
    description:
      "Calculate rebar weight, total length, and material cost for concrete slabs, foundations, footings, walls, columns, and beams. Supports metric and US bar sizes, 3 calculation modes, and instant price estimation.",
    icon: "🪨",
    iconBg: "#fef3c7",
    iconColor: "#d97706",
    category: "utility",
    subCategory: "construction-materials",
    badge: "New",
    badgeType: "new",
    path: "/calculators/construction/rebar",
    available: true,
  },
  {
    id: "aluminum-weight-calculator",
    label: "Aluminum Weight Calculator",
    tagline: "Weight by shape, alloy & dimensions",
    description:
      "Calculate the weight of aluminum bars, tubes, pipes, sheets, angles, channels, I-beams and more. Supports 12 alloys, 15 shapes, all unit systems, and instant price estimation.",
    icon: "⚖️",
    iconBg: "#f0f9ff",
    iconColor: "#0284c7",
    category: "utility",
    subCategory: "construction-materials",
    badge: "New",
    badgeType: "new",
    path: "/calculators/construction/aluminum-weight",
    available: true,
  },
  {
    id: "retaining-wall-calculator",
    label: "Retaining Wall Calculator",
    tagline: "Material estimator for concrete, CMU, segmental & stone walls",
    description:
      "Estimate materials and costs for poured concrete, CMU block, segmental, mortared stone, and dry-stack retaining walls. Includes footing, drainage, backfill, and conceptual rebar estimates. For material quantity estimation only — not a structural design tool.",
    icon: "🧱",
    iconBg: "#fef3c7",
    iconColor: "#d97706",
    category: "utility",
    subCategory: "construction-materials",
    badge: "New",
    badgeType: "new",
    path: "/calculators/construction/retaining-wall",
    available: true,
  },
  {
    id: "decking-calculator",
    label: "Decking Calculator",
    tagline: "Boards, fasteners & cost estimator for your deck",
    description:
      "Calculate how many decking boards you need, plus screws/nails or hidden clips, and total decking cost. Supports square-profile decking tiles and a 10% waste factor.",
    icon: "🪵",
    iconBg: "#fef3c7",
    iconColor: "#d97706",
    category: "utility",
    subCategory: "construction-materials",
    badge: "New",
    badgeType: "new",
    path: "/calculators/construction/decking",
    available: true,
  },
  {
    id: "rolling-offset-calculator",
    label: "Rolling Offset Calculator",
    tagline: "True offset, travel & run for pipe fitting",
    description:
      "Calculate the true offset, travel, and run for a rolling pipe offset from the horizontal (roll) and vertical (set) distances. Supports 22½°, 45°, 60°, 90°, and custom fitting bend angles.",
    icon: "📐",
    iconBg: "#eff6ff",
    iconColor: "#1d4ed8",
    category: "utility",
    subCategory: "construction-materials",
    badge: "New",
    badgeType: "new",
    path: "/calculators/construction/rolling-offset",
    available: true,
  },
  {
    id: "diy-shed-cost-calculator",
    label: "DIY Shed Cost Calculator",
    tagline: "Floor, wall & roof area plus material cost estimator",
    description:
      "Calculate the floor, wall, and roof area of a DIY shed and estimate the total material cost. Supports slanted, flat, and gable roof types with rafter length and overhang.",
    icon: "🏚️",
    iconBg: "#fef3c7",
    iconColor: "#d97706",
    category: "utility",
    subCategory: "construction-materials",
    badge: "New",
    badgeType: "new",
    path: "/calculators/construction/diy-shed-cost",
    available: true,
  },
  {
    id: "sag-calculator",
    label: "SAG Calculator",
    tagline: "Radius of curvature, diameter & sagitta solver",
    description:
      "Calculate the sagitta (SAG), radius of curvature, or diameter of a circular arc — enter any two values and the third is solved automatically. Useful for arches, curved roofs, and cable sag.",
    icon: "📏",
    iconBg: "#eff6ff",
    iconColor: "#1d4ed8",
    category: "utility",
    subCategory: "construction-materials",
    badge: "New",
    badgeType: "new",
    path: "/calculators/construction/sag",
    available: true,
  },
  {
    id: "board-and-batten-calculator",
    label: "Board and Batten Calculator",
    tagline: "Boards, battens, trim, fasteners & paint estimator",
    description:
      "Calculate board and batten siding material quantities. Supports multiple walls, openings, 7 board profiles, full North American lumber database, layout engine, trim estimator, fastener estimator, and paint/stain estimator.",
    icon: "🪵",
    iconBg: "#fef3c7",
    iconColor: "#d97706",
    category: "utility",
    subCategory: "construction-materials",
    badge: "New",
    badgeType: "new",
    path: "/calculators/construction/board-and-batten",
    available: true,
  },
  {
    id: "drywall-calculator",
    label: "Drywall Calculator",
    tagline: "Panels, doors, windows & cost estimator",
    description:
      "Calculate how much drywall you need from room dimensions, sloped-wall areas, doors, and windows. Supports 9 standard metric panel sizes plus instant cost estimation.",
    icon: "🧱",
    iconBg: "#eff6ff",
    iconColor: "#1d4ed8",
    category: "utility",
    subCategory: "construction-materials",
    badge: "New",
    badgeType: "new",
    path: "/calculators/construction/drywall",
    available: true,
  },
  {
    id: "sand-calculator",
    label: "Sand Calculator",
    tagline: "Volume, weight & cost for sand fill",
    description:
      "Calculate how much sand you need from length, width, and depth. Get the volume and weight needed based on density, plus instant cost estimation by weight or by volume.",
    icon: "🏖️",
    iconBg: "#fff7ed",
    iconColor: "#d97706",
    category: "utility",
    subCategory: "construction-materials",
    badge: "New",
    badgeType: "new",
    path: "/calculators/construction/sand",
    available: true,
  },
  {
    id: "fire-glass-calculator",
    label: "Fire Glass Calculator",
    tagline: "Volume & weight for rectangular, round & more fire pits",
    description:
      "Calculate how much fire glass you need for rectangular, square, round, triangular, or trapezoidal fire pits. Supports reflective and recycled glass density presets, plus a custom density option.",
    icon: "🔥",
    iconBg: "#fff7ed",
    iconColor: "#ea580c",
    category: "utility",
    subCategory: "construction-materials",
    badge: "New",
    badgeType: "new",
    path: "/calculators/construction/fire-glass",
    available: true,
  },
  {
    id: "glass-weight-calculator",
    label: "Glass Weight Calculator",
    tagline: "Weight by glass type, shape & dimensions",
    description:
      "Calculate the weight of a glass sheet or piece from its type, shape, and dimensions. Supports 19 glass types (annealed, tempered, laminated, and more) with reference densities, 8 shapes including rectangular, circular, and round rod, plus a quantity multiplier.",
    icon: "🪟",
    iconBg: "#eff6ff",
    iconColor: "#1d4ed8",
    category: "utility",
    subCategory: "construction-materials",
    badge: "New",
    badgeType: "new",
    path: "/calculators/construction/glass-weight",
    available: true,
  },
  {
    id: "sealant-calculator",
    label: "Sealant Calculator",
    tagline: "Volume, packages & cost for caulk and sealant joints",
    description:
      "Calculate how much sealant you need from joint length, width, and depth. Supports wastage, 10 standard cartridge/sausage/pail package sizes plus a custom tube volume, and instant cost estimation.",
    icon: "🧴",
    iconBg: "#eff6ff",
    iconColor: "#1d4ed8",
    category: "utility",
    subCategory: "construction-materials",
    badge: "New",
    badgeType: "new",
    path: "/calculators/construction/sealant",
    available: true,
  },
  {
    id: "framing-calculator",
    label: "Framing Calculator",
    tagline: "Studs needed & cost for wall framing",
    description:
      "Calculate how many wall studs you need from wall length and on-center (OC) spacing, plus estimated waste and total cost. Standard 16″, 19.2″, and 24″ OC spacings supported.",
    icon: "🪵",
    iconBg: "#fef3c7",
    iconColor: "#d97706",
    category: "utility",
    subCategory: "construction-materials",
    badge: "New",
    badgeType: "new",
    path: "/calculators/construction/framing",
    available: true,
  },
  {
    id: "sonotube-calculator",
    label: "Sonotube Calculator",
    tagline: "Concrete volume, bags & cost for tube forms",
    description:
      "Calculate concrete volume and weight for round Sonotube® forms from diameter, height, and quantity. Supports pre-mixed bag counts or a cement/sand/gravel mix ratio breakdown, plus instant cost estimation.",
    icon: "🧱",
    iconBg: "#f0f9ff",
    iconColor: "#0369a1",
    category: "utility",
    subCategory: "construction-materials",
    badge: "New",
    badgeType: "new",
    path: "/calculators/construction/sonotube",
    available: true,
  },
  {
    id: "french-drain-calculator",
    label: "French Drain Calculator",
    tagline: "Trench volume, pipe, gravel & cost for drainage",
    description:
      "Calculate trench volume, drain pipe quantity, and gravel needed for a French drain from trench width, depth, and length. Supports Schedule 40 and SDR35 pipe, optional fabric filter, and instant cost estimation.",
    icon: "🚰",
    iconBg: "#f0f9ff",
    iconColor: "#0369a1",
    category: "utility",
    subCategory: "construction-materials",
    badge: "New",
    badgeType: "new",
    path: "/calculators/construction/french-drain",
    available: true,
  },
  {
    id: "board-foot-calculator",
    label: "Board Foot Calculator",
    tagline: "Calculate lumber volume in board feet",
    description: "Instantly calculate board feet for any lumber size. Supports inches, mm, cm, feet and meters. Enter thickness, width, length and quantity to get per-piece and total board feet.",
    icon: "🪵",
    iconBg: "#fef3c7",
    iconColor: "#d97706",
    category: "utility",
    subCategory: "construction-calc",
    badge: "New",
    badgeType: "new",
    path: "/tools/board-foot-calculator",
    available: true,
  },
  {
    id: "cps-tester",
    label: "CPS Tester",
    tagline: "Test your clicks per second — free, accurate, instant",
    description: "Measure your real clicking speed with an accurate CPS (Clicks Per Second) tester. Choose a preset duration or a custom one up to 5 minutes, see Peak CPS and click-interval stats, and track your personal best. No signup required.",
    icon: "🖱️",
    iconBg: "#fff0f0",
    iconColor: "#ff5a5f",
    category: "gaming-tools",
    badge: "New",
    badgeType: "new",
    path: "/tools/cps-tester",
    available: true,
    keywords: [
      "cps test", "clicks per second test", "click speed test", "cps tester",
      "mouse click test", "minecraft cps test", "how many clicks per second",
    ],
  },
  {
    id: "japanese-name-generator",
    label: "Japanese Name Generator",
    tagline: "Real Japanese names with Kanji, readings, and meanings",
    description: "Generate, search, and browse real Japanese girl names, boy names, and surnames A-Z with Kanji, Hiragana readings, and Hepburn romaji. Search by meaning, convert your name to Katakana, compare names, and save favorites. Free, no signup.",
    icon: "🎎",
    iconBg: "#fff0f5",
    iconColor: "#e0578a",
    category: "naming-tools",
    badge: "New",
    badgeType: "new",
    path: "/tools/japanese-name-generator",
    available: true,
    keywords: [
      "japanese name generator", "japanese girl names", "japanese boy names", "japanese surnames",
      "japanese last names", "kanji name generator", "my name in japanese", "japanese name meaning",
    ],
  },
  {
    id: "grow-a-garden-calculator",
    label: "Grow A Garden Calculator",
    tagline: "Plant value, mutations, pet XP, egg hatch & pet ability",
    description: "Calculate Grow a Garden plant/crop values with weight and mutations, pet XP growth time, egg hatch speed, pet weight by age, and pet ability stats — all in one free calculator.",
    icon: "🌾",
    iconBg: "#f0fdf4",
    iconColor: "#22c55e",
    category: "utility",
    subCategory: "garden-calc",
    badge: "New",
    badgeType: "new",
    path: "/tools/grow-a-garden-calculator",
    available: true,
    keywords: [
      "grow a garden calculator", "grow a garden value calculator", "grow a garden mutations",
      "grow a garden pet xp", "grow a garden egg hatch", "roblox grow a garden",
    ],
  },
  {
    id: "split-excel",
    label: "Split Excel",
    tagline: "Split a spreadsheet into smaller files by row count",
    description: "Split a large Excel (XLS or XLSX) spreadsheet into several smaller files by row count. Free, no signup, no upload — runs entirely in your browser.",
    icon: "✂️",
    iconBg: "#f0fdf4",
    iconColor: "#16a34a",
    category: "excel-tools",
    badge: "New",
    badgeType: "new",
    path: "/tools/split-excel",
    available: true,
    keywords: ["split excel", "split xlsx", "split spreadsheet", "excel splitter", "divide excel file", "excel row splitter"],
  },
  {
    id: "mortgage-calculator",
    label: "Mortgage Calculator",
    tagline: "Monthly payment, taxes, PMI, extra payments & amortization",
    description: "Calculate your monthly mortgage payment including property taxes, home insurance, PMI, HOA fees, and other costs. Model extra payments and biweekly payoff, and view a full amortization schedule.",
    icon: "🏠",
    iconBg: "#f0fdf4",
    iconColor: "#16a34a",
    category: "utility",
    subCategory: "financial-calc",
    badge: "New",
    badgeType: "new",
    path: "/tools/mortgage-calculator",
    available: true,
    keywords: [
      "mortgage calculator", "monthly mortgage payment", "amortization schedule",
      "mortgage payoff calculator", "PMI calculator", "extra payment mortgage calculator",
      "biweekly mortgage calculator", "home loan calculator",
    ],
  },
  {
    id: "loan-calculator",
    label: "Loan Calculator",
    tagline: "Amortized loans, deferred payment loans & bond pricing",
    description: "Calculate amortized loan payments with any compound and pay-back frequency, deferred payment loans due in full at maturity, and bond present values from a known face value — with a full period-by-period schedule table.",
    icon: "💵",
    iconBg: "#f0fdf4",
    iconColor: "#16a34a",
    category: "utility",
    subCategory: "financial-calc",
    badge: "New",
    badgeType: "new",
    path: "/tools/loan-calculator",
    available: true,
    keywords: [
      "loan calculator", "amortized loan calculator", "loan payment calculator",
      "deferred payment loan", "bond calculator", "bond present value calculator",
      "loan amortization schedule", "loan interest calculator",
    ],
  },
  {
    id: "auto-loan-calculator",
    label: "Auto Loan Calculator",
    tagline: "Monthly car payment, sales tax, trade-in & fees",
    description: "Calculate your monthly auto loan payment including sales tax, trade-in credit, cash incentives, and title/registration fees. Solve for price or payment, and view a full amortization schedule.",
    icon: "🚗",
    iconBg: "#f0fdf4",
    iconColor: "#16a34a",
    category: "utility",
    subCategory: "financial-calc",
    badge: "New",
    badgeType: "new",
    path: "/tools/auto-loan-calculator",
    available: true,
    keywords: [
      "auto loan calculator", "car loan calculator", "car payment calculator",
      "auto loan payment", "vehicle loan calculator", "car loan sales tax calculator",
      "trade-in loan calculator", "car finance calculator",
    ],
  },
  {
    id: "interest-calculator",
    label: "Interest Calculator",
    tagline: "Compound interest, contributions & inflation-adjusted growth",
    description: "Calculate compound interest growth on a lump-sum investment plus annual and monthly contributions, with any compounding frequency, tax rate, and inflation adjustment. View a full annual or monthly accumulation schedule.",
    icon: "📈",
    iconBg: "#f0fdf4",
    iconColor: "#16a34a",
    category: "utility",
    subCategory: "financial-calc",
    badge: "New",
    badgeType: "new",
    path: "/tools/interest-calculator",
    available: true,
    keywords: [
      "interest calculator", "compound interest calculator", "investment growth calculator",
      "savings calculator", "annual contribution calculator", "accumulation schedule",
      "inflation adjusted return calculator", "compound growth calculator",
    ],
  },
  {
    id: "payment-calculator",
    label: "Payment Calculator",
    tagline: "Monthly payment or loan payoff time",
    description: "Calculate the monthly payment for a fixed-term loan, or the time it takes to pay off a loan with a fixed monthly payment. View a full annual or monthly amortization schedule.",
    icon: "💳",
    iconBg: "#f0fdf4",
    iconColor: "#16a34a",
    category: "utility",
    subCategory: "financial-calc",
    badge: "New",
    badgeType: "new",
    path: "/tools/payment-calculator",
    available: true,
    keywords: [
      "payment calculator", "loan payment calculator", "fixed payment calculator",
      "loan payoff calculator", "monthly payment calculator", "amortization schedule",
      "loan payoff time calculator", "debt payoff calculator",
    ],
  },
  {
    id: "retirement-calculator",
    label: "Retirement Calculator",
    tagline: "How much you need to retire, and how to get there",
    description: "Estimate how much you need to retire, build a savings plan to get there, project a sustainable withdrawal amount, and see how long your savings can last.",
    icon: "🏖️",
    iconBg: "#f0fdf4",
    iconColor: "#16a34a",
    category: "utility",
    subCategory: "financial-calc",
    badge: "New",
    badgeType: "new",
    path: "/tools/retirement-calculator",
    available: true,
    keywords: [
      "retirement calculator", "retirement savings calculator", "how much to retire calculator",
      "retirement planning calculator", "retirement withdrawal calculator", "retirement savings plan",
      "how long will my money last calculator", "nest egg calculator",
    ],
  },
  {
    id: "amortization-calculator",
    label: "Amortization Calculator",
    tagline: "Monthly payment, payoff schedule, and extra-payment savings",
    description: "Calculate your loan's monthly payment, total interest, and a full amortization schedule. See how extra monthly, yearly, or one-time payments can shorten your payoff time and save interest.",
    icon: "📆",
    iconBg: "#f0fdf4",
    iconColor: "#16a34a",
    category: "utility",
    subCategory: "financial-calc",
    badge: "New",
    badgeType: "new",
    path: "/tools/amortization-calculator",
    available: true,
    keywords: [
      "amortization calculator", "loan amortization schedule", "monthly payment calculator",
      "extra payment calculator", "loan payoff calculator", "amortization schedule",
      "interest savings calculator", "mortgage amortization",
    ],
  },
  {
    id: "investment-calculator",
    label: "Investment Calculator",
    tagline: "End amount, return rate, contribution, and more",
    description: "Project how an investment will grow, or solve backward from a target for the contribution, return rate, starting amount, or time needed to reach it.",
    icon: "📈",
    iconBg: "#f0fdf4",
    iconColor: "#16a34a",
    category: "utility",
    subCategory: "financial-calc",
    badge: "New",
    badgeType: "new",
    path: "/tools/investment-calculator",
    available: true,
    keywords: [
      "investment calculator", "compound growth calculator", "investment return calculator",
      "investment goal calculator", "future value calculator", "accumulation schedule",
      "how much to invest calculator", "investment growth calculator",
    ],
  },
];

export function getToolById(id) {
  return TOOLS.find((t) => t.id === id) || null;
}

export function getToolsByCategory(categoryId) {
  if (categoryId === "all") return TOOLS;
  return TOOLS.filter((t) => t.category === categoryId);
}

export function getAvailableTools() {
  return TOOLS.filter((t) => t.available);
}
