// Central tool registry — add new tools here, they auto-appear everywhere

export const CATEGORIES = [
  { id: "all",       label: "All Tools" },
  { id: "image",     label: "Image" },
  { id: "pdf",       label: "PDF" },
  { id: "converter", label: "Converters" },
  { id: "health",    label: "Health" },
  { id: "utility",   label: "Calculators", subCategories: [
    { id: "health-calc",       label: "Health Calculators" },
    { id: "everyday",          label: "Everyday Life Calculator" },
    { id: "construction-calc", label: "Construction Converters 👷" },
  ]},
  { id: "url-tools",  label: "URL Tools" },
  { id: "text-tools",   label: "Text Tools" },
  { id: "design-tools", label: "Design Tools" },
];

export const TOOLS = [
  {
    id: "image-compressor",
    label: "Image Compressor",
    tagline: "Reduce image size without quality loss",
    description: "Compress JPEG, PNG, and WebP images by up to 80% while keeping them visually perfect. Batch compress up to 10 images at once.",
    icon: "🖼",
    iconBg: "#f3f0ff",
    iconColor: "#8b5cf6",
    category: "image",
    badge: "New",
    badgeType: "new",
    path: "/tools/image-compressor",
    available: true,
  },
  {
    id: "image-converter",
    label: "Image Converter",
    tagline: "JPG, PNG, HEIC, PDF, OCR & more",
    description: "Convert images to JPG, PNG, PDF, extract text via OCR, and more — 8 tools in one. Free, fast, no signup.",
    icon: "🔄",
    iconBg: "#fef3c7",
    iconColor: "#d97706",
    category: "image",
    badge: "New",
    badgeType: "new",
    path: "/tools/image-converter",
    available: true,
  },
  {
    id: "pdf-merge",
    label: "Merge PDF",
    tagline: "Combine multiple PDFs into one",
    description: "Upload multiple PDFs, drag to reorder, and merge them into a single file instantly. Free, fast, no signup.",
    icon: "📄",
    iconBg: "#eff6ff",
    iconColor: "#3b7bfc",
    category: "pdf",
    badge: "New",
    badgeType: "new",
    path: "/tools/pdf-merge",
    available: true,
  },
  {
    id: "pdf-compress",
    label: "Compress PDF",
    tagline: "Reduce PDF file size",
    description: "Reduce file size while optimizing for maximal PDF quality. Easy, fast, and free.",
    icon: "📦",
    iconBg: "#eff6ff",
    iconColor: "#3b7bfc",
    category: "pdf",
    badge: "New",
    badgeType: "new",
    path: "/tools/pdf-compress",
    available: true,
  },
  {
    id: "pdf-split",
    label: "Split PDF",
    tagline: "Separate PDF pages",
    description: "Separate one page or a whole set for easy conversion into independent PDF files.",
    icon: "✂️",
    iconBg: "#eff6ff",
    iconColor: "#3b7bfc",
    category: "pdf",
    badge: "New",
    badgeType: "new",
    path: "/tools/pdf-split",
    available: true,
  },
  {
    id: "pdf-to-word",
    label: "PDF to Word",
    tagline: "Convert PDF to editable DOCX",
    description: "Convert PDF files to editable Word documents (.docx). Preserves text, paragraphs, and structure. Batch convert up to 20 PDFs. Free, fast, no signup.",
    icon: "📝",
    iconBg: "#e0f2fe",
    iconColor: "#0284c7",
    category: "pdf",
    badge: "New",
    badgeType: "new",
    path: "/tools/pdf-to-word",
    available: true,
  },
  {
    id: "calorie-tracker",
    label: "Calorie Tracker & Calculator",
    tagline: "BMI, TDEE, Macros, Water & Meal Planner",
    description: "Calculate your BMI, daily calorie needs (TDEE), macro breakdown, water intake and get healthy meal suggestions — all in one free tool.",
    icon: "🥗",
    iconBg: "#f0fdf4",
    iconColor: "#22c55e",
    category: "utility",
    subCategory: "health-calc",
    badge: "New",
    badgeType: "new",
    path: "/tools/calorie-tracker",
    available: true,
  },
  {
    id: "sleep-calculator",
    label: "Sleep Calculator",
    tagline: "Optimal sleep & wake-up times based on sleep cycles",
    description: "Find the best time to go to sleep or wake up based on 90-minute sleep cycles. Get personalized schedules for 4, 5, or 6 cycles — wake up refreshed, not groggy.",
    icon: "🌙",
    iconBg: "#eef2ff",
    iconColor: "#6366f1",
    category: "utility",
    subCategory: "health-calc",
    badge: "New",
    badgeType: "new",
    path: "/tools/sleep-calculator",
    available: true,
  },
  {
    id: "destiny-matrix",
    label: "Destiny Matrix Calculator",
    tagline: "Life Path, Numerology Chart & Karmic Reading",
    description: "Discover your Life Path, Destiny, Soul Urge and Personality numbers. Get your Pythagoras Matrix, karmic lessons, energy analysis and full numerology reading — instantly free.",
    icon: "✦",
    iconBg: "#eef2ff",
    iconColor: "#6366f1",
    category: "utility",
    subCategory: "everyday",
    badge: "New",
    badgeType: "new",
    path: "/tools/destiny-matrix",
    available: true,
  },
  {
    id: "url-shortener",
    label: "URL Shortener",
    tagline: "Shorten any long link instantly",
    description: "Create short, clean, shareable links from any URL in seconds. Custom aliases, expiration, QR codes — no signup required.",
    icon: "🔗",
    iconBg: "#f0fdf4",
    iconColor: "#22c55e",
    category: "url-tools",
    badge: "New",
    badgeType: "new",
    path: "/tools/url-shortener",
    available: true,
  },
  {
    id: "ai-summarizer",
    label: "AI Summarizer",
    tagline: "Summarize any text with AI",
    description: "Quickly generate concise summaries from articles, paragraphs, and essays.",
    icon: "🤖",
    iconBg: "#ecfeff",
    iconColor: "#06b6d4",
    category: "ai",
    badge: "Soon",
    badgeType: "muted",
    path: "/tools/ai-summarizer",
    available: false,
  },
  {
    id: "word-counter",
    label: "Word Counter",
    tagline: "Words, characters, sentences & reading time",
    description: "Instantly count words, characters, sentences, paragraphs, and estimate reading time. Supports .txt and .md file upload. No signup required.",
    icon: "📝",
    iconBg: "#fefce8",
    iconColor: "#ca8a04",
    category: "text-tools",
    badge: "New",
    badgeType: "new",
    path: "/tools/word-counter",
    available: true,
  },
  {
    id: "qr-generator",
    label: "QR Generator",
    tagline: "URLs, text, WiFi, email, phone — instantly",
    description: "Generate customizable QR codes for any URL, text, email, phone, or WiFi credentials. Download as PNG or SVG. No signup required.",
    icon: "⬛",
    iconBg: "#f0fdf4",
    iconColor: "#16a34a",
    category: "url-tools",
    badge: "New",
    badgeType: "new",
    path: "/tools/qr-generator",
    available: true,
  },
  {
    id: "unit-converter",
    label: "Unit Converter",
    tagline: "Length, weight, temperature, data & more",
    description: "Convert 12 unit categories instantly — length, weight, temperature, area, volume, speed, time, data, energy, pressure, angle and frequency. Real-time bidirectional conversion.",
    icon: "⚖️",
    iconBg: "#fff7ed",
    iconColor: "#f59e0b",
    category: "converter",
    badge: "New",
    badgeType: "new",
    path: "/tools/unit-converter",
    available: true,
  },
  {
    id: "color-picker",
    label: "Color Picker",
    tagline: "HEX, RGB, HSL · palettes · WCAG contrast",
    description: "Pick colors visually, convert between HEX, RGB and HSL, generate complementary palettes, check WCAG accessibility contrast, and save session favorites — all in-browser, no upload.",
    icon: "🎨",
    iconBg: "#f3f0ff",
    iconColor: "#7c3aed",
    category: "design-tools",
    badge: "New",
    badgeType: "new",
    path: "/tools/color-picker",
    available: true,
  },
  {
    id: "anniversary-calculator",
    label: "Anniversary Calculator",
    tagline: "Milestones, countdowns & calendar export",
    description: "Track relationship or event anniversaries with a live countdown, elapsed time breakdown, milestone tracker, traditional anniversary names, and one-click calendar export (.ics).",
    icon: "💑",
    iconBg: "#fff0f5",
    iconColor: "#e11d48",
    category: "utility",
    subCategory: "everyday",
    badge: "New",
    badgeType: "new",
    path: "/tools/anniversary-calculator",
    available: true,
  },
  {
    id: "square-yards-calculator",
    label: "Square Yards Calculator",
    tagline: "Sod, carpet, tile, flooring & landscaping",
    description: "Calculate area in square yards for 10 shapes: rectangle, square, circle, triangle, trapezoid, ellipse, semi-circle, L-shape, ring, and custom. Built-in material estimator for sod, carpet, tile, mulch, gravel, and artificial grass.",
    icon: "🌿",
    iconBg: "#f0fdf4",
    iconColor: "#16a34a",
    category: "utility",
    subCategory: "construction-calc",
    badge: "New",
    badgeType: "new",
    path: "/tools/square-yards-calculator",
    available: true,
  },
  {
    id: "square-footage-calculator",
    label: "Square Footage Calculator",
    tagline: "Area for any shape — floor, roof, land",
    description: "Calculate square footage for 10 shapes: rectangle, square, circle, triangle, trapezoid, ellipse, semi-circle, L-shape, ring, and custom polygon. Supports all unit systems with instant results.",
    icon: "📐",
    iconBg: "#eff6ff",
    iconColor: "#3b7bfc",
    category: "utility",
    subCategory: "construction-calc",
    badge: "New",
    badgeType: "new",
    path: "/tools/square-footage-calculator",
    available: true,
  },
  {
    id: "gallons-calculator",
    label: "Gallons per Sq Ft Calculator",
    tagline: "Paint, sealers, epoxy & coating coverage",
    description: "Calculate gallons per square foot, total gallons needed, and coverage area for paint, primer, epoxy, concrete sealers, waterproofing, and more. Supports US gal, imperial gal, liters, and all major units.",
    icon: "🪣",
    iconBg: "#eff6ff",
    iconColor: "#3b7bfc",
    category: "utility",
    subCategory: "construction-calc",
    badge: "New",
    badgeType: "new",
    path: "/tools/gallons-calculator",
    available: true,
  },
  {
    id: "cubic-yard-calculator",
    label: "Cubic Yard Calculator",
    tagline: "Concrete, gravel, sand, soil & more",
    description: "Calculate volume in cubic yards for concrete, gravel, sand, soil, mulch and fill dirt. Supports feet, inches, yards, meters and centimeters. Instant results with material weight estimates.",
    icon: "📐",
    iconBg: "#f0fdf4",
    iconColor: "#16a34a",
    category: "utility",
    subCategory: "construction-calc",
    badge: "New",
    badgeType: "new",
    path: "/tools/cubic-yard-calculator",
    available: true,
  },
  {
    id: "sqft-to-cubic-yards",
    label: "Sq Ft to Cubic Yards Calculator",
    tagline: "Concrete, gravel, sand, soil & more",
    description: "Convert square feet and depth into cubic yards instantly. Supports Length×Width or direct area entry, 10 volume output units, material weight estimator (concrete, gravel, sand, topsoil, mulch). No Calculate button — instant results.",
    icon: "🧱",
    iconBg: "#f0fdf4",
    iconColor: "#16a34a",
    category: "utility",
    subCategory: "construction-calc",
    badge: "New",
    badgeType: "new",
    path: "/tools/sqft-to-cubic-yards",
    available: true,
  },
  {
    id: "size-to-weight-calculator",
    label: "Size to Weight Calculator",
    tagline: "Weight of steel, aluminum, concrete & more",
    description: "Calculate the weight of any rectangular solid from its dimensions and material density. Supports 20+ materials (steel, aluminum, concrete, wood, plastics), all major unit systems, and instant results.",
    icon: "⚖️",
    iconBg: "#fef3c7",
    iconColor: "#d97706",
    category: "utility",
    subCategory: "construction-calc",
    badge: "New",
    badgeType: "new",
    path: "/tools/size-to-weight-calculator",
    available: true,
  },
  {
    id: "board-foot-calculator",
    label: "Board Foot Calculator",
    tagline: "Calculate lumber volume in board feet",
    description: "Instantly calculate board feet for any lumber size. Supports inches, mm, cm, feet and meters. Enter thickness, width, length and quantity to get per-piece and total board feet.",
    icon: "🪵",
    iconBg: "#fef3c7",
    iconColor: "#d97706",
    category: "utility",
    subCategory: "construction-calc",
    badge: "New",
    badgeType: "new",
    path: "/tools/board-foot-calculator",
    available: true,
  },
];

export function getToolById(id) {
  return TOOLS.find((t) => t.id === id) || null;
}

export function getToolsByCategory(categoryId) {
  if (categoryId === "all") return TOOLS;
  return TOOLS.filter((t) => t.category === categoryId);
}

export function getAvailableTools() {
  return TOOLS.filter((t) => t.available);
}
