import { useState, useCallback, useMemo, useEffect, useRef } from "react";
import {
  calculateBMI, getBMICategory, getHealthyWeightRange, getBMIHealthMessage,
  calculateBMR, calculateTDEE, calculateMacros, calculateWater,
  kgToLbs, lbsToKg, cmToFtIn, ftInToCm,
  ACTIVITY_LEVELS, WEATHER_OPTIONS, MACRO_MODES, MEAL_SUGGESTIONS,
} from "../../../utils/calorieCalc";

// ─────────────────────────────────────────────────────────────
// Constants
// ─────────────────────────────────────────────────────────────
const TABS = [
  { id: "bmi",    label: "BMI",      icon: "⚖️" },
  { id: "tdee",   label: "Calories", icon: "🔥" },
  { id: "macros", label: "Macros",   icon: "🥩" },
  { id: "water",  label: "Water",    icon: "💧" },
  { id: "meals",  label: "Meals",    icon: "🍽️" },
];

const MEAL_GOALS = [
  { id: "weightLoss",  label: "Weight Loss",  emoji: "📉" },
  { id: "maintenance", label: "Maintenance",  emoji: "⚖️" },
  { id: "muscleGain",  label: "Muscle Gain",  emoji: "💪" },
];

// ─────────────────────────────────────────────────────────────
// Micro-utilities
// ─────────────────────────────────────────────────────────────
async function copyText(text) {
  try {
    await navigator.clipboard.writeText(text);
    return true;
  } catch {
    try {
      const ta = document.createElement("textarea");
      ta.value = text;
      Object.assign(ta.style, { position: "fixed", opacity: "0" });
      document.body.appendChild(ta);
      ta.select();
      document.execCommand("copy");
      document.body.removeChild(ta);
      return true;
    } catch { return false; }
  }
}

async function shareResult(title, text) {
  if (navigator.share) {
    try { await navigator.share({ title, text, url: window.location.href }); return; } catch {}
  }
  await copyText(text);
}

function printPdf(title, sections) {
  const rows = (items) =>
    items.map(it => `<div class="row"><span class="lbl">${it.label}</span><span class="val">${it.value}</span></div>`).join("");
  const html = `<!DOCTYPE html><html><head><meta charset="UTF-8"><title>${title} — Tolz</title>
<style>
  body{font-family:Arial,sans-serif;max-width:580px;margin:0 auto;padding:32px;color:#1a1a2e;}
  h1{font-size:21px;margin-bottom:4px;} .sub{color:#888;font-size:12px;margin-bottom:26px;}
  .sec{border:1px solid #e5e5ea;border-radius:10px;padding:18px;margin-bottom:16px;}
  .sec h2{font-size:13px;font-weight:700;color:#4a4a6a;margin-bottom:10px;text-transform:uppercase;letter-spacing:.05em;}
  .row{display:flex;justify-content:space-between;padding:6px 0;border-bottom:1px solid #f3f3f5;font-size:14px;}
  .row:last-child{border-bottom:none;} .lbl{color:#888;} .val{font-weight:700;}
  .footer{margin-top:28px;text-align:center;font-size:11px;color:#aaa;}
</style></head><body>
<h1>${title}</h1>
<p class="sub">Generated by tolz.org · Free Calorie Calculator · ${new Date().toLocaleDateString()}</p>
${sections.map(s => `<div class="sec"><h2>${s.title}</h2>${rows(s.items)}</div>`).join("")}
<div class="footer">tolz.org — Free Online Tools — No Signup Required</div>
<script>window.onload=()=>window.print();<\/script></body></html>`;
  const w = window.open("", "_blank");
  if (!w) { alert("Please allow popups to download the PDF."); return; }
  w.document.write(html);
  w.document.close();
}

// ─────────────────────────────────────────────────────────────
// Shared style tokens
// ─────────────────────────────────────────────────────────────
const S = {
  label: {
    display: "block", fontSize: 13, fontWeight: 600,
    fontFamily: "var(--font-display)", color: "var(--text-secondary)", marginBottom: 6,
  },
  errText: { fontSize: 12, color: "var(--error)", marginTop: 4, fontFamily: "var(--font-display)" },
  unitBtn: {
    fontSize: 12, fontWeight: 600, fontFamily: "var(--font-display)",
    color: "var(--accent)", background: "var(--accent-light)",
    border: "none", cursor: "pointer", padding: "3px 8px",
    borderRadius: 6, transition: "opacity var(--transition)",
  },
  suffix: {
    position: "absolute", right: 12, top: "50%", transform: "translateY(-50%)",
    fontSize: 13, fontWeight: 600, color: "var(--text-muted)",
    fontFamily: "var(--font-display)", pointerEvents: "none",
  },
  card: {
    background: "var(--bg-white)", border: "1px solid var(--border)",
    borderRadius: "var(--radius-lg)", padding: "20px",
  },
  sectionTitle: {
    fontSize: 14, fontWeight: 700, fontFamily: "var(--font-display)",
    color: "var(--text-secondary)", marginBottom: 16,
    textTransform: "uppercase", letterSpacing: "0.05em",
  },
};

// ─────────────────────────────────────────────────────────────
// AnimatedNumber
// ─────────────────────────────────────────────────────────────
function AnimatedNumber({ value, decimals = 0 }) {
  const [disp, setDisp] = useState(0);
  const raf  = useRef(null);
  const prev = useRef(0);

  useEffect(() => {
    // eslint-disable-next-line react-hooks/set-state-in-effect
    if (value == null) { setDisp(0); prev.current = 0; return; }
    const from = prev.current;
    const to   = value;
    const t0   = performance.now();
    const dur  = 650;
    if (raf.current) cancelAnimationFrame(raf.current);
    const tick = (t) => {
      const p = Math.min((t - t0) / dur, 1);
      const e = 1 - Math.pow(1 - p, 3);
      setDisp(from + (to - from) * e);
      if (p < 1) { raf.current = requestAnimationFrame(tick); } else { prev.current = to; }
    };
    raf.current = requestAnimationFrame(tick);
    return () => { if (raf.current) cancelAnimationFrame(raf.current); };
  }, [value]);

  return <span>{disp.toFixed(decimals)}</span>;
}

// ─────────────────────────────────────────────────────────────
// BMI Gauge
// ─────────────────────────────────────────────────────────────
function BMIGauge({ bmi }) {
  const pct = Math.max(0, Math.min(100, ((bmi - 10) / 30) * 100));
  const segs = [
    { color: "#93c5fd", w: 28.3 },
    { color: "#86efac", w: 21.7 },
    { color: "#fcd34d", w: 16.7 },
    { color: "#fca5a5", w: 33.3 },
  ];
  const labels = ["10", "18.5", "25", "30", "40+"];
  return (
    <div style={{ margin: "18px 0 4px" }}>
      <div style={{ position: "relative" }}>
        <div style={{ display: "flex", height: 10, borderRadius: 99, overflow: "hidden" }}>
          {segs.map((s, i) => <div key={i} style={{ width: `${s.w}%`, background: s.color }} />)}
        </div>
        <div style={{
          position: "absolute", left: `${pct}%`, top: -4,
          transform: "translateX(-50%)",
          width: 4, height: 18, background: "var(--text-primary)",
          borderRadius: 2, transition: "left 0.65s cubic-bezier(0.22,1,0.36,1)",
        }} />
      </div>
      <div style={{ display: "flex", justifyContent: "space-between", marginTop: 6,
        fontSize: 10, color: "var(--text-muted)", fontFamily: "var(--font-display)" }}>
        {labels.map(l => <span key={l}>{l}</span>)}
      </div>
    </div>
  );
}

// ─────────────────────────────────────────────────────────────
// Macro progress bar
// ─────────────────────────────────────────────────────────────
function MacroBar({ label, grams, cals, pct, color }) {
  return (
    <div style={{ display: "flex", flexDirection: "column", gap: 6 }}>
      <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center" }}>
        <div style={{ display: "flex", alignItems: "center", gap: 8 }}>
          <div style={{ width: 10, height: 10, borderRadius: "50%", background: color, flexShrink: 0 }} />
          <span style={{ fontSize: 14, fontWeight: 600, fontFamily: "var(--font-display)", color: "var(--text-primary)" }}>
            {label}
          </span>
        </div>
        <div style={{ display: "flex", gap: 10, alignItems: "center" }}>
          <span style={{ fontSize: 14, fontWeight: 700, color: "var(--text-primary)", fontFamily: "var(--font-display)" }}>
            {grams}g
          </span>
          <span style={{ fontSize: 12, color: "var(--text-muted)", fontFamily: "var(--font-display)" }}>
            {cals} kcal
          </span>
          <span style={{ fontSize: 12, fontWeight: 600, color, background: `${color}22`,
            padding: "2px 7px", borderRadius: 99, fontFamily: "var(--font-display)" }}>
            {pct}%
          </span>
        </div>
      </div>
      <div style={{ height: 8, background: "var(--bg-muted)", borderRadius: 99, overflow: "hidden" }}>
        <div style={{
          height: "100%", width: `${pct}%`, background: color,
          borderRadius: 99, transition: "width 0.65s cubic-bezier(0.22,1,0.36,1)",
        }} />
      </div>
    </div>
  );
}

// ─────────────────────────────────────────────────────────────
// Shared form inputs
// ─────────────────────────────────────────────────────────────
function GenderToggle({ value, onChange }) {
  return (
    <div>
      <label style={S.label}>Gender</label>
      <div style={{ display: "flex", gap: 8 }}>
        {[["male", "♂ Male"], ["female", "♀ Female"]].map(([g, lbl]) => (
          <button key={g} type="button" onClick={() => onChange("gender", g)}
            style={{
              flex: 1, padding: "10px 12px", borderRadius: "var(--radius-md)", cursor: "pointer",
              border: `1.5px solid ${value === g ? "var(--accent)" : "var(--border)"}`,
              background: value === g ? "var(--accent-light)" : "var(--bg-white)",
              color: value === g ? "var(--accent)" : "var(--text-secondary)",
              fontFamily: "var(--font-display)", fontWeight: 600, fontSize: 14,
              transition: "all var(--transition)",
            }}>
            {lbl}
          </button>
        ))}
      </div>
    </div>
  );
}

function AgeInput({ form, onChange, err }) {
  return (
    <div>
      <label style={S.label}>Age</label>
      <input className="input" type="number" min="1" max="120" placeholder="e.g. 25"
        value={form.age} onChange={e => onChange("age", e.target.value)}
        style={err ? { borderColor: "var(--error)" } : {}} />
      {err && <p style={S.errText}>{err}</p>}
    </div>
  );
}

function HeightInput({ form, onChange, err }) {
  const isFtIn = form.heightUnit === "ftin";
  const toggle = () => {
    const next = isFtIn ? "cm" : "ftin";
    if (next === "ftin" && form.heightCm) {
      const { feet, inches } = cmToFtIn(Number(form.heightCm));
      onChange("heightFt", String(feet));
      onChange("heightIn", String(inches));
    } else if (next === "cm" && (form.heightFt || form.heightIn)) {
      onChange("heightCm", String(ftInToCm(Number(form.heightFt || 0), Number(form.heightIn || 0))));
    }
    onChange("heightUnit", next);
  };
  const errStyle = err ? { borderColor: "var(--error)" } : {};
  return (
    <div>
      <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: 6 }}>
        <label style={{ ...S.label, marginBottom: 0 }}>Height</label>
        <button type="button" onClick={toggle} style={S.unitBtn}>{isFtIn ? "→ cm" : "→ ft/in"}</button>
      </div>
      {isFtIn ? (
        <div style={{ display: "flex", gap: 8 }}>
          {[["heightFt", "ft", "1", "8", "5"], ["heightIn", "in", "0", "11", "10"]].map(
            ([key, unit, min, max, ph]) => (
              <div key={key} style={{ flex: 1, position: "relative" }}>
                <input className="input" type="number" min={min} max={max} placeholder={ph}
                  value={form[key]} onChange={e => onChange(key, e.target.value)}
                  style={{ paddingRight: 36, ...errStyle }} />
                <span style={S.suffix}>{unit}</span>
              </div>
            )
          )}
        </div>
      ) : (
        <div style={{ position: "relative" }}>
          <input className="input" type="number" min="50" max="300" placeholder="e.g. 170"
            value={form.heightCm} onChange={e => onChange("heightCm", e.target.value)}
            style={{ paddingRight: 48, ...errStyle }} />
          <span style={S.suffix}>cm</span>
        </div>
      )}
      {err && <p style={S.errText}>{err}</p>}
    </div>
  );
}

function WeightInput({ form, onChange, err, showLabel = true }) {
  const isLbs = form.weightUnit === "lbs";
  const toggle = () => {
    const next = isLbs ? "kg" : "lbs";
    if (form.weight) {
      const v = next === "lbs" ? kgToLbs(Number(form.weight)) : lbsToKg(Number(form.weight));
      onChange("weight", String(v));
    }
    onChange("weightUnit", next);
  };
  return (
    <div>
      <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: 6 }}>
        {showLabel && <label style={{ ...S.label, marginBottom: 0 }}>Weight</label>}
        {!showLabel && <span />}
        <button type="button" onClick={toggle} style={S.unitBtn}>{isLbs ? "→ kg" : "→ lbs"}</button>
      </div>
      <div style={{ position: "relative" }}>
        <input className="input" type="number" min="1"
          max={isLbs ? "1320" : "600"} step="0.1"
          placeholder={isLbs ? "e.g. 154" : "e.g. 70"}
          value={form.weight} onChange={e => onChange("weight", e.target.value)}
          style={{ paddingRight: 48, ...(err ? { borderColor: "var(--error)" } : {}) }} />
        <span style={S.suffix}>{form.weightUnit}</span>
      </div>
      {err && <p style={S.errText}>{err}</p>}
    </div>
  );
}

function ActivitySelect({ value, onChange }) {
  return (
    <div>
      <label style={S.label}>Activity Level</label>
      <select className="input" value={value} onChange={e => onChange("activityLevel", e.target.value)}
        style={{ cursor: "pointer" }}>
        {ACTIVITY_LEVELS.map(a => (
          <option key={a.id} value={a.id}>{a.label} — {a.desc}</option>
        ))}
      </select>
    </div>
  );
}

// ─────────────────────────────────────────────────────────────
// Action buttons bar
// ─────────────────────────────────────────────────────────────
function ActionBar({ onCopy, onShare, onPdf, onReset, copied }) {
  return (
    <div style={{ display: "flex", gap: 8, flexWrap: "wrap", marginTop: 4 }}>
      <button type="button" className="btn btn-secondary" style={{ fontSize: 13, padding: "9px 14px" }}
        onClick={onCopy}>
        {copied ? "✓ Copied!" : "📋 Copy"}
      </button>
      <button type="button" className="btn btn-secondary" style={{ fontSize: 13, padding: "9px 14px" }}
        onClick={onShare}>
        📤 Share
      </button>
      <button type="button" className="btn btn-secondary" style={{ fontSize: 13, padding: "9px 14px" }}
        onClick={onPdf}>
        📄 Save PDF
      </button>
      <button type="button" className="btn btn-ghost" style={{ fontSize: 13, padding: "9px 14px", marginLeft: "auto" }}
        onClick={onReset}>
        ↺ Reset
      </button>
    </div>
  );
}

// ─────────────────────────────────────────────────────────────
// BMI Tab
// ─────────────────────────────────────────────────────────────
function BMITab({ form, onChange }) {
  const [result, setResult] = useState(null);
  const [errors, setErrors] = useState({});
  const [copied, setCopied] = useState(false);

  const weightKg = useMemo(() => {
    if (!form.weight) return null;
    return form.weightUnit === "kg" ? Number(form.weight) : lbsToKg(Number(form.weight));
  }, [form.weight, form.weightUnit]);

  const heightCm = useMemo(() => {
    if (form.heightUnit === "cm") return form.heightCm ? Number(form.heightCm) : null;
    return (form.heightFt || form.heightIn)
      ? ftInToCm(Number(form.heightFt || 0), Number(form.heightIn || 0))
      : null;
  }, [form.heightUnit, form.heightCm, form.heightFt, form.heightIn]);

  const validate = () => {
    const e = {};
    const age = Number(form.age);
    if (!form.age || isNaN(age) || age < 1 || age > 120) e.age = "Enter a valid age (1–120).";
    if (!heightCm || heightCm < 50 || heightCm > 300) e.height = "Enter a valid height (50–300 cm).";
    if (!weightKg || weightKg < 10 || weightKg > 600) e.weight = "Enter a valid weight.";
    return e;
  };

  const calculate = () => {
    const e = validate();
    if (Object.keys(e).length) { setErrors(e); return; }
    setErrors({});
    const bmi      = calculateBMI(weightKg, heightCm);
    const category = getBMICategory(bmi);
    const range    = getHealthyWeightRange(heightCm);
    const message  = getBMIHealthMessage(bmi);
    setResult({ bmi, category, range, message });
  };

  const reset = () => { setResult(null); setErrors({}); };

  const getResultText = () => {
    if (!result) return "";
    const { bmi, category, range } = result;
    return `BMI Calculator Results\nBMI Score: ${bmi.toFixed(1)}\nCategory: ${category.label}\nHealthy Weight Range: ${range.minKg}–${range.maxKg} kg (${range.minLbs}–${range.maxLbs} lbs)\n\nCalculated at tolz.org`;
  };

  const handleCopy = async () => {
    await copyText(getResultText());
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div style={{ display: "flex", flexDirection: "column", gap: 16 }}>
      {/* Inputs */}
      <div style={S.card}>
        <p style={S.sectionTitle}>Your Details</p>
        <div style={{ display: "flex", flexDirection: "column", gap: 14 }}>
          <GenderToggle value={form.gender} onChange={onChange} />
          <AgeInput form={form} onChange={onChange} err={errors.age} />
          <HeightInput form={form} onChange={onChange} err={errors.height} />
          <WeightInput form={form} onChange={onChange} err={errors.weight} />
        </div>
      </div>

      <button type="button" className="btn btn-primary" style={{ width: "100%", padding: "13px", fontSize: 15 }}
        onClick={calculate}>
        Calculate BMI
      </button>

      {/* Result */}
      {result && (
        <div className="animate-fadeUp" style={S.card}>
          <p style={S.sectionTitle}>Your BMI Result</p>

          {/* Score + category */}
          <div style={{ display: "flex", alignItems: "center", gap: 16, marginBottom: 4 }}>
            <div>
              <div style={{ fontSize: 48, fontWeight: 800, fontFamily: "var(--font-display)",
                color: result.category.color, lineHeight: 1, letterSpacing: "-0.03em" }}>
                <AnimatedNumber value={result.bmi} decimals={1} />
              </div>
              <div style={{ fontSize: 12, color: "var(--text-muted)", fontFamily: "var(--font-display)", fontWeight: 600, marginTop: 2 }}>
                BMI Score
              </div>
            </div>
            <div style={{
              padding: "8px 16px", borderRadius: "var(--radius-md)",
              background: result.category.bg, border: `1.5px solid ${result.category.color}44`,
            }}>
              <div style={{ fontSize: 16, fontWeight: 700, fontFamily: "var(--font-display)", color: result.category.textColor }}>
                {result.category.label}
              </div>
              <div style={{ fontSize: 12, color: result.category.color, fontFamily: "var(--font-display)", marginTop: 1 }}>
                BMI {result.bmi < 18.5 ? "< 18.5" : result.bmi < 25 ? "18.5–24.9" : result.bmi < 30 ? "25–29.9" : "≥ 30"}
              </div>
            </div>
          </div>

          <BMIGauge bmi={result.bmi} />

          {/* Stats row */}
          <div style={{ display: "flex", gap: 10, marginTop: 16 }}>
            {[
              { label: "Healthy Range (kg)", value: `${result.range.minKg} – ${result.range.maxKg}` },
              { label: "Healthy Range (lbs)", value: `${result.range.minLbs} – ${result.range.maxLbs}` },
            ].map(s => (
              <div key={s.label} style={{
                flex: 1, padding: "12px 14px", borderRadius: "var(--radius-md)",
                background: "var(--bg-muted)", textAlign: "center",
              }}>
                <div style={{ fontSize: 14, fontWeight: 700, fontFamily: "var(--font-display)", color: "var(--text-primary)" }}>
                  {s.value}
                </div>
                <div style={{ fontSize: 11, color: "var(--text-muted)", fontFamily: "var(--font-display)", marginTop: 2 }}>
                  {s.label}
                </div>
              </div>
            ))}
          </div>

          {/* Health message */}
          <div style={{ marginTop: 14, padding: "12px 14px", borderRadius: "var(--radius-md)",
            background: `${result.category.color}11`, border: `1px solid ${result.category.color}33` }}>
            <p style={{ fontSize: 13, color: result.category.textColor, lineHeight: 1.55, fontWeight: 500 }}>
              💡 {result.message}
            </p>
          </div>

          <div style={{ marginTop: 14, paddingTop: 14, borderTop: "1px solid var(--border)" }}>
            <ActionBar
              copied={copied}
              onCopy={handleCopy}
              onShare={() => shareResult("My BMI Results — Tolz", getResultText())}
              onPdf={() => printPdf("BMI Calculator Results", [{
                title: "BMI Details",
                items: [
                  { label: "BMI Score", value: result.bmi.toFixed(1) },
                  { label: "Category", value: result.category.label },
                  { label: "Healthy Range (kg)", value: `${result.range.minKg} – ${result.range.maxKg} kg` },
                  { label: "Healthy Range (lbs)", value: `${result.range.minLbs} – ${result.range.maxLbs} lbs` },
                  { label: "Gender", value: form.gender === "male" ? "Male" : "Female" },
                  { label: "Age", value: `${form.age} years` },
                ],
              }])}
              onReset={reset}
            />
          </div>
        </div>
      )}

      {/* Disclaimer */}
      <p style={{ fontSize: 12, color: "var(--text-muted)", textAlign: "center", lineHeight: 1.5 }}>
        BMI is a screening tool, not a diagnostic measure. Consult a healthcare provider for medical advice.
      </p>
    </div>
  );
}

// ─────────────────────────────────────────────────────────────
// TDEE Tab
// ─────────────────────────────────────────────────────────────
function TDEETab({ form, onChange, onTdeeResult }) {
  const [result, setResult] = useState(null);
  const [errors, setErrors] = useState({});
  const [copied, setCopied] = useState(false);

  const weightKg = useMemo(() => {
    if (!form.weight) return null;
    return form.weightUnit === "kg" ? Number(form.weight) : lbsToKg(Number(form.weight));
  }, [form.weight, form.weightUnit]);

  const heightCm = useMemo(() => {
    if (form.heightUnit === "cm") return form.heightCm ? Number(form.heightCm) : null;
    return (form.heightFt || form.heightIn)
      ? ftInToCm(Number(form.heightFt || 0), Number(form.heightIn || 0))
      : null;
  }, [form.heightUnit, form.heightCm, form.heightFt, form.heightIn]);

  const validate = () => {
    const e = {};
    const age = Number(form.age);
    if (!form.age || isNaN(age) || age < 1 || age > 120) e.age = "Enter a valid age (1–120).";
    if (!heightCm || heightCm < 50 || heightCm > 300) e.height = "Enter a valid height.";
    if (!weightKg || weightKg < 10 || weightKg > 600) e.weight = "Enter a valid weight.";
    return e;
  };

  const calculate = () => {
    const e = validate();
    if (Object.keys(e).length) { setErrors(e); return; }
    setErrors({});
    const bmr         = calculateBMR(form.gender, weightKg, heightCm, Number(form.age));
    const maintenance = calculateTDEE(bmr, form.activityLevel);
    const loss        = maintenance - 500;
    const gain        = maintenance + 500;
    const r = { bmr: Math.round(bmr), maintenance: Math.round(maintenance), loss: Math.round(loss), gain: Math.round(gain) };
    setResult(r);
    onTdeeResult(Math.round(maintenance));
  };

  const reset = () => { setResult(null); setErrors({}); };

  const getResultText = () => result
    ? `Calorie Calculator Results\nBMR: ${result.bmr} kcal/day\nMaintenance: ${result.maintenance} kcal/day\nWeight Loss (−500 kcal): ${result.loss} kcal/day\nWeight Gain (+500 kcal): ${result.gain} kcal/day\n\nCalculated at tolz.org`
    : "";

  const handleCopy = async () => {
    await copyText(getResultText());
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const calCards = result ? [
    { label: "Basal Metabolic Rate", sub: "Calories at rest", value: result.bmr, color: "#8b5cf6", bg: "#f3f0ff" },
    { label: "Maintenance Calories", sub: "To stay the same", value: result.maintenance, color: "#22c55e", bg: "#f0fdf4" },
    { label: "Weight Loss",          sub: "–500 kcal/day",    value: result.loss,        color: "#f59e0b", bg: "#fffbeb" },
    { label: "Weight Gain",          sub: "+500 kcal/day",    value: result.gain,        color: "#3b7bfc", bg: "#eff6ff" },
  ] : [];

  return (
    <div style={{ display: "flex", flexDirection: "column", gap: 16 }}>
      <div style={S.card}>
        <p style={S.sectionTitle}>Your Details</p>
        <div style={{ display: "flex", flexDirection: "column", gap: 14 }}>
          <GenderToggle value={form.gender} onChange={onChange} />
          <AgeInput form={form} onChange={onChange} err={errors.age} />
          <HeightInput form={form} onChange={onChange} err={errors.height} />
          <WeightInput form={form} onChange={onChange} err={errors.weight} />
          <ActivitySelect value={form.activityLevel} onChange={onChange} />
        </div>
      </div>

      <button type="button" className="btn btn-primary" style={{ width: "100%", padding: "13px", fontSize: 15 }}
        onClick={calculate}>
        Calculate Daily Calories
      </button>

      {result && (
        <div className="animate-fadeUp">
          <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: 10, marginBottom: 16 }}>
            {calCards.map(c => (
              <div key={c.label} style={{
                ...S.card, background: c.bg,
                border: `1.5px solid ${c.color}33`,
                textAlign: "center",
              }}>
                <div style={{ fontSize: 28, fontWeight: 800, fontFamily: "var(--font-display)",
                  color: c.color, lineHeight: 1.1, letterSpacing: "-0.03em" }}>
                  <AnimatedNumber value={c.value} />
                </div>
                <div style={{ fontSize: 11, color: c.color, fontFamily: "var(--font-display)",
                  fontWeight: 600, marginTop: 2, opacity: 0.8 }}>kcal/day</div>
                <div style={{ fontSize: 13, fontWeight: 700, fontFamily: "var(--font-display)",
                  color: "var(--text-primary)", marginTop: 6 }}>{c.label}</div>
                <div style={{ fontSize: 11, color: "var(--text-muted)", fontFamily: "var(--font-display)", marginTop: 2 }}>
                  {c.sub}
                </div>
              </div>
            ))}
          </div>

          <div style={{ ...S.card, background: "var(--accent-light)", border: "1.5px solid var(--accent)33" }}>
            <p style={{ fontSize: 13, color: "var(--accent)", fontWeight: 500, lineHeight: 1.55 }}>
              💡 These estimates are based on the <strong>Mifflin-St Jeor Equation</strong>, the most accurate formula for most people.
              A deficit of 500 kcal/day leads to ~0.5 kg loss per week.
            </p>
          </div>

          <div style={{ ...S.card, marginTop: 10 }}>
            <ActionBar
              copied={copied}
              onCopy={handleCopy}
              onShare={() => shareResult("My Calorie Results — Tolz", getResultText())}
              onPdf={() => printPdf("Daily Calorie Results", [{
                title: "Calorie Breakdown",
                items: calCards.map(c => ({ label: c.label, value: `${c.value} kcal/day` })),
              }])}
              onReset={reset}
            />
          </div>
        </div>
      )}

      <p style={{ fontSize: 12, color: "var(--text-muted)", textAlign: "center", lineHeight: 1.5 }}>
        Mifflin-St Jeor Equation. Individual results may vary based on metabolism and other factors.
      </p>
    </div>
  );
}

// ─────────────────────────────────────────────────────────────
// Macros Tab
// ─────────────────────────────────────────────────────────────
function MacrosTab({ form, onChange, tdeeCalories }) {
  const [result, setResult] = useState(null);
  const [calories, setCalories] = useState("");
  const [macroMode, setMacroMode] = useState("balanced");
  const [errors, setErrors] = useState({});
  const [copied, setCopied] = useState(false);

  const useTdee = () => {
    if (tdeeCalories) setCalories(String(tdeeCalories));
  };

  const validate = () => {
    const e = {};
    const c = Number(calories);
    if (!calories || isNaN(c) || c < 500 || c > 10000) e.calories = "Enter a valid daily calorie goal (500–10,000).";
    return e;
  };

  const calculate = () => {
    const e = validate();
    if (Object.keys(e).length) { setErrors(e); return; }
    setErrors({});
    setResult(calculateMacros(Number(calories), macroMode));
  };

  const reset = () => { setResult(null); setErrors({}); setCalories(""); };

  const getResultText = () => result
    ? `Macro Calculator Results\nTotal Calories: ${calories} kcal\nProtein: ${result.protein}g (${result.proteinPct}%)\nCarbohydrates: ${result.carbs}g (${result.carbsPct}%)\nFat: ${result.fat}g (${result.fatPct}%)\n\nCalculated at tolz.org`
    : "";

  const handleCopy = async () => {
    await copyText(getResultText());
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const macroItems = result
    ? [
        { label: "Protein",       grams: result.protein, cals: result.proteinCals, pct: result.proteinPct, color: "#3b7bfc" },
        { label: "Carbohydrates", grams: result.carbs,   cals: result.carbsCals,   pct: result.carbsPct,   color: "#22c55e" },
        { label: "Fat",           grams: result.fat,     cals: result.fatCals,     pct: result.fatPct,     color: "#f59e0b" },
      ]
    : [];

  return (
    <div style={{ display: "flex", flexDirection: "column", gap: 16 }}>
      <div style={S.card}>
        <p style={S.sectionTitle}>Macro Settings</p>
        <div style={{ display: "flex", flexDirection: "column", gap: 14 }}>
          {/* Calories input */}
          <div>
            <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: 6 }}>
              <label style={{ ...S.label, marginBottom: 0 }}>Daily Calorie Goal</label>
              {tdeeCalories && (
                <button type="button" onClick={useTdee} style={S.unitBtn}>
                  Use TDEE ({tdeeCalories} kcal)
                </button>
              )}
            </div>
            <div style={{ position: "relative" }}>
              <input className="input" type="number" min="500" max="10000"
                placeholder="e.g. 2000" value={calories}
                onChange={e => { setCalories(e.target.value); setErrors({}); }}
                style={{ paddingRight: 56, ...(errors.calories ? { borderColor: "var(--error)" } : {}) }} />
              <span style={S.suffix}>kcal</span>
            </div>
            {errors.calories && <p style={S.errText}>{errors.calories}</p>}
          </div>

          {/* Macro mode */}
          <div>
            <label style={S.label}>Macro Profile</label>
            <div style={{ display: "flex", flexDirection: "column", gap: 8 }}>
              {MACRO_MODES.map(m => (
                <button key={m.id} type="button" onClick={() => setMacroMode(m.id)}
                  style={{
                    padding: "11px 14px", borderRadius: "var(--radius-md)", cursor: "pointer",
                    border: `1.5px solid ${macroMode === m.id ? "var(--accent)" : "var(--border)"}`,
                    background: macroMode === m.id ? "var(--accent-light)" : "var(--bg-white)",
                    display: "flex", alignItems: "center", justifyContent: "space-between",
                    transition: "all var(--transition)",
                  }}>
                  <span style={{ fontFamily: "var(--font-display)", fontWeight: 700, fontSize: 14,
                    color: macroMode === m.id ? "var(--accent)" : "var(--text-primary)" }}>
                    {m.label}
                  </span>
                  <span style={{ fontSize: 12, color: macroMode === m.id ? "var(--accent)" : "var(--text-muted)",
                    fontFamily: "var(--font-display)", fontWeight: 600 }}>
                    {m.desc}
                  </span>
                </button>
              ))}
            </div>
          </div>
        </div>
      </div>

      <button type="button" className="btn btn-primary" style={{ width: "100%", padding: "13px", fontSize: 15 }}
        onClick={calculate}>
        Calculate Macros
      </button>

      {result && (
        <div className="animate-fadeUp" style={{ display: "flex", flexDirection: "column", gap: 10 }}>
          <div style={S.card}>
            <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: 16 }}>
              <p style={{ ...S.sectionTitle, marginBottom: 0 }}>Daily Macros</p>
              <span style={{ fontSize: 13, fontWeight: 700, fontFamily: "var(--font-display)",
                color: "var(--text-primary)" }}>
                {calories} kcal total
              </span>
            </div>
            <div style={{ display: "flex", flexDirection: "column", gap: 16 }}>
              {macroItems.map(m => <MacroBar key={m.label} {...m} />)}
            </div>
          </div>

          {/* Quick summary grid */}
          <div style={{ display: "grid", gridTemplateColumns: "repeat(3, 1fr)", gap: 8 }}>
            {macroItems.map(m => (
              <div key={m.label} style={{ ...S.card, textAlign: "center", padding: "14px 10px",
                background: `${m.color}0d`, border: `1.5px solid ${m.color}33` }}>
                <div style={{ fontSize: 22, fontWeight: 800, fontFamily: "var(--font-display)", color: m.color }}>
                  <AnimatedNumber value={m.grams} />
                  <span style={{ fontSize: 14 }}>g</span>
                </div>
                <div style={{ fontSize: 11, color: "var(--text-muted)", fontFamily: "var(--font-display)",
                  fontWeight: 600, marginTop: 3 }}>
                  {m.label}
                </div>
              </div>
            ))}
          </div>

          <div style={S.card}>
            <ActionBar
              copied={copied}
              onCopy={handleCopy}
              onShare={() => shareResult("My Macro Results — Tolz", getResultText())}
              onPdf={() => printPdf("Macro Calculator Results", [{
                title: "Macro Breakdown",
                items: [
                  { label: "Total Calories", value: `${calories} kcal` },
                  ...macroItems.map(m => ({ label: m.label, value: `${m.grams}g (${m.cals} kcal · ${m.pct}%)` })),
                ],
              }])}
              onReset={reset}
            />
          </div>
        </div>
      )}
    </div>
  );
}

// ─────────────────────────────────────────────────────────────
// Water Tab
// ─────────────────────────────────────────────────────────────
function WaterTab({ form, onChange }) {
  const [result, setResult] = useState(null);
  const [errors, setErrors] = useState({});
  const [copied, setCopied] = useState(false);

  const weightKg = useMemo(() => {
    if (!form.weight) return null;
    return form.weightUnit === "kg" ? Number(form.weight) : lbsToKg(Number(form.weight));
  }, [form.weight, form.weightUnit]);

  const calculate = () => {
    const e = {};
    if (!weightKg || weightKg < 10 || weightKg > 600) e.weight = "Enter a valid weight.";
    if (Object.keys(e).length) { setErrors(e); return; }
    setErrors({});
    setResult(calculateWater(weightKg, form.activityLevel, form.weather));
  };

  const reset = () => { setResult(null); setErrors({}); };

  const getResultText = () => result
    ? `Water Intake Calculator\nRecommended Daily Intake: ${result.liters} L (${result.oz} fl oz)\nApprox. ${result.glasses} glasses (250 ml each)\n\nCalculated at tolz.org`
    : "";

  const handleCopy = async () => {
    await copyText(getResultText());
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const waterPct = result ? Math.min(100, (result.liters / 5) * 100) : 0;

  return (
    <div style={{ display: "flex", flexDirection: "column", gap: 16 }}>
      <div style={S.card}>
        <p style={S.sectionTitle}>Your Details</p>
        <div style={{ display: "flex", flexDirection: "column", gap: 14 }}>
          <WeightInput form={form} onChange={onChange} err={errors.weight} />
          <ActivitySelect value={form.activityLevel} onChange={onChange} />
          {/* Weather */}
          <div>
            <label style={S.label}>Climate / Weather</label>
            <div style={{ display: "flex", gap: 8 }}>
              {WEATHER_OPTIONS.map(w => (
                <button key={w.id} type="button" onClick={() => onChange("weather", w.id)}
                  style={{
                    flex: 1, padding: "10px 6px", borderRadius: "var(--radius-md)", cursor: "pointer",
                    border: `1.5px solid ${form.weather === w.id ? "#06b6d4" : "var(--border)"}`,
                    background: form.weather === w.id ? "#ecfeff" : "var(--bg-white)",
                    color: form.weather === w.id ? "#0891b2" : "var(--text-secondary)",
                    fontFamily: "var(--font-display)", fontWeight: 600, fontSize: 13,
                    transition: "all var(--transition)", textAlign: "center",
                  }}>
                  {w.label}
                  <div style={{ fontSize: 11, fontWeight: 400, opacity: 0.75, marginTop: 2 }}>{w.desc}</div>
                </button>
              ))}
            </div>
          </div>
        </div>
      </div>

      <button type="button" className="btn btn-primary" style={{ width: "100%", padding: "13px", fontSize: 15 }}
        onClick={calculate}>
        Calculate Water Intake
      </button>

      {result && (
        <div className="animate-fadeUp" style={{ display: "flex", flexDirection: "column", gap: 10 }}>
          {/* Main result */}
          <div style={{ ...S.card, textAlign: "center", padding: "28px 20px",
            background: "#ecfeff", border: "1.5px solid #06b6d433" }}>
            <div style={{ fontSize: 56, marginBottom: 4 }}>💧</div>
            <div style={{ fontSize: 48, fontWeight: 800, fontFamily: "var(--font-display)",
              color: "#0891b2", lineHeight: 1, letterSpacing: "-0.03em" }}>
              <AnimatedNumber value={result.liters} decimals={1} />
              <span style={{ fontSize: 22, fontWeight: 700 }}> L</span>
            </div>
            <div style={{ fontSize: 15, color: "#0891b2", fontFamily: "var(--font-display)",
              fontWeight: 600, marginTop: 6, opacity: 0.8 }}>
              Recommended daily water intake
            </div>

            {/* Progress bar */}
            <div style={{ marginTop: 18, marginBottom: 8 }}>
              <div style={{ height: 10, background: "#cffafe", borderRadius: 99, overflow: "hidden" }}>
                <div style={{ height: "100%", width: `${waterPct}%`, background: "linear-gradient(90deg,#06b6d4,#0284c7)",
                  borderRadius: 99, transition: "width 0.65s cubic-bezier(0.22,1,0.36,1)" }} />
              </div>
            </div>

            <div style={{ display: "flex", gap: 16, justifyContent: "center", marginTop: 12 }}>
              {[
                { label: "fl oz", value: result.oz },
                { label: "glasses (250ml)", value: result.glasses },
              ].map(s => (
                <div key={s.label} style={{ textAlign: "center" }}>
                  <div style={{ fontSize: 20, fontWeight: 800, fontFamily: "var(--font-display)", color: "#0e7490" }}>
                    <AnimatedNumber value={s.value} />
                  </div>
                  <div style={{ fontSize: 11, color: "#0891b2", fontFamily: "var(--font-display)", fontWeight: 600 }}>
                    {s.label}
                  </div>
                </div>
              ))}
            </div>
          </div>

          <div style={{ ...S.card, background: "#f0fdf4", border: "1px solid #bbf7d0" }}>
            <p style={{ fontSize: 13, color: "#15803d", lineHeight: 1.55 }}>
              💡 Spread your intake evenly throughout the day.
              Drink a glass when you wake up, before each meal, and before bed.
            </p>
          </div>

          <div style={S.card}>
            <ActionBar
              copied={copied}
              onCopy={handleCopy}
              onShare={() => shareResult("My Water Intake — Tolz", getResultText())}
              onPdf={() => printPdf("Water Intake Calculator", [{
                title: "Daily Water Intake",
                items: [
                  { label: "Litres", value: `${result.liters} L` },
                  { label: "Fluid Ounces", value: `${result.oz} fl oz` },
                  { label: "Glasses (250 ml)", value: `${result.glasses} glasses` },
                ],
              }])}
              onReset={reset}
            />
          </div>
        </div>
      )}
    </div>
  );
}

// ─────────────────────────────────────────────────────────────
// Meals Tab
// ─────────────────────────────────────────────────────────────
function MealsTab() {
  const [goal, setGoal] = useState("weightLoss");
  const meals = MEAL_SUGGESTIONS[goal] || [];

  const goalColors = {
    weightLoss:  { bg: "#fff5f5", border: "#fecdcd", color: "#dc2626", pill: "#fee2e2" },
    maintenance: { bg: "#fffbeb", border: "#fde68a", color: "#b45309", pill: "#fef3c7" },
    muscleGain:  { bg: "#f0fdf4", border: "#bbf7d0", color: "#15803d", pill: "#dcfce7" },
  };
  const gc = goalColors[goal];

  return (
    <div style={{ display: "flex", flexDirection: "column", gap: 16 }}>
      {/* Goal selector */}
      <div style={S.card}>
        <p style={S.sectionTitle}>Select Your Goal</p>
        <div style={{ display: "flex", flexDirection: "column", gap: 8 }}>
          {MEAL_GOALS.map(g => (
            <button key={g.id} type="button" onClick={() => setGoal(g.id)}
              style={{
                padding: "12px 16px", borderRadius: "var(--radius-md)", cursor: "pointer",
                border: `1.5px solid ${goal === g.id ? goalColors[g.id].color : "var(--border)"}`,
                background: goal === g.id ? goalColors[g.id].bg : "var(--bg-white)",
                display: "flex", alignItems: "center", gap: 12,
                transition: "all var(--transition)",
              }}>
              <span style={{ fontSize: 20 }}>{g.emoji}</span>
              <span style={{ fontFamily: "var(--font-display)", fontWeight: 700, fontSize: 14,
                color: goal === g.id ? goalColors[g.id].color : "var(--text-primary)" }}>
                {g.label}
              </span>
            </button>
          ))}
        </div>
      </div>

      {/* Meal cards */}
      <div>
        <div style={{ display: "flex", alignItems: "center", gap: 8, marginBottom: 12 }}>
          <div style={{ width: 8, height: 8, borderRadius: "50%", background: gc.color }} />
          <p style={{ fontSize: 13, fontWeight: 700, fontFamily: "var(--font-display)", color: gc.color }}>
            {MEAL_GOALS.find(g => g.id === goal)?.label} Meal Ideas
          </p>
        </div>
        <div style={{ display: "flex", flexDirection: "column", gap: 10 }}>
          {meals.map((meal, i) => (
            <div key={i} className="animate-fadeUp" style={{
              ...S.card, animationDelay: `${i * 50}ms`,
              background: gc.bg, border: `1px solid ${gc.border}`,
            }}>
              <div style={{ display: "flex", alignItems: "center", gap: 12 }}>
                <div style={{ fontSize: 28, flexShrink: 0 }}>{meal.emoji}</div>
                <div style={{ flex: 1, minWidth: 0 }}>
                  <div style={{ fontFamily: "var(--font-display)", fontWeight: 700, fontSize: 14,
                    color: "var(--text-primary)", marginBottom: 4 }}>
                    {meal.name}
                  </div>
                  <div style={{ display: "flex", gap: 6, flexWrap: "wrap" }}>
                    {[
                      { label: `${meal.cal} kcal`, color: gc.color },
                      { label: `P: ${meal.protein}g`, color: "#3b7bfc" },
                      { label: `C: ${meal.carbs}g`,   color: "#22c55e" },
                      { label: `F: ${meal.fat}g`,     color: "#f59e0b" },
                    ].map(tag => (
                      <span key={tag.label} style={{
                        padding: "2px 8px", borderRadius: 99, fontSize: 11,
                        fontWeight: 700, fontFamily: "var(--font-display)",
                        color: tag.color, background: `${tag.color}15`,
                      }}>
                        {tag.label}
                      </span>
                    ))}
                    <span style={{ padding: "2px 8px", borderRadius: 99, fontSize: 11,
                      fontWeight: 600, fontFamily: "var(--font-display)",
                      color: "var(--text-muted)", background: "var(--bg-muted)" }}>
                      ⏱ {meal.time}
                    </span>
                  </div>
                </div>
              </div>
            </div>
          ))}
        </div>
      </div>

      <p style={{ fontSize: 12, color: "var(--text-muted)", textAlign: "center", lineHeight: 1.5 }}>
        Nutritional values are approximate. Actual values may vary based on preparation and portion size.
      </p>
    </div>
  );
}

// ─────────────────────────────────────────────────────────────
// Main Component
// ─────────────────────────────────────────────────────────────
export default function CalorieTrackerTool() {
  const [activeTab, setActiveTab] = useState("bmi");
  const [tdeeCalories, setTdeeCalories] = useState(null);
  const [form, setForm] = useState({
    gender: "male",
    age: "",
    heightUnit: "cm",
    heightCm: "",
    heightFt: "",
    heightIn: "",
    weightUnit: "kg",
    weight: "",
    activityLevel: "sedentary",
    weather: "normal",
  });

  const onChange = useCallback((key, value) => {
    setForm(f => ({ ...f, [key]: value }));
  }, []);

  useEffect(() => {
    const prev = document.title;
    document.title = "Free Calorie Tracker & Calculator – BMI, TDEE & Macros | Tolz";
    return () => { document.title = prev; };
  }, []);

  return (
    <div className="animate-fadeUp" style={{ display: "flex", flexDirection: "column", gap: 20 }}>
      {/* Tab navigation */}
      <div style={{
        display: "flex", gap: 6, overflowX: "auto", paddingBottom: 2,
        scrollbarWidth: "none", msOverflowStyle: "none",
      }}>
        {TABS.map(tab => (
          <button key={tab.id} type="button" onClick={() => setActiveTab(tab.id)}
            style={{
              display: "flex", alignItems: "center", gap: 6, flexShrink: 0,
              padding: "9px 16px", borderRadius: 99, fontSize: 13, fontWeight: 600,
              fontFamily: "var(--font-display)", cursor: "pointer",
              border: `1.5px solid ${activeTab === tab.id ? "var(--accent)" : "var(--border)"}`,
              background: activeTab === tab.id ? "var(--accent)" : "var(--bg-white)",
              color: activeTab === tab.id ? "#fff" : "var(--text-secondary)",
              transition: "all var(--transition)",
              boxShadow: activeTab === tab.id ? "0 2px 8px rgba(59,123,252,0.25)" : "none",
            }}>
            <span style={{ fontSize: 15 }}>{tab.icon}</span>
            {tab.label}
          </button>
        ))}
      </div>

      {/* Tab content */}
      {activeTab === "bmi" && (
        <BMITab form={form} onChange={onChange} />
      )}
      {activeTab === "tdee" && (
        <TDEETab form={form} onChange={onChange} onTdeeResult={setTdeeCalories} />
      )}
      {activeTab === "macros" && (
        <MacrosTab form={form} onChange={onChange} tdeeCalories={tdeeCalories} />
      )}
      {activeTab === "water" && (
        <WaterTab form={form} onChange={onChange} />
      )}
      {activeTab === "meals" && (
        <MealsTab />
      )}
    </div>
  );
}
