import { useState } from "react";
import { Link } from "react-router-dom";
import JsonLd from "../../JsonLd";

const FAQ_ITEMS = [
  {
    q: "Is this Japanese name generator free to use?",
    a: "Yes. The tool is completely free, with no signup, subscription, or hidden charges. Generating, searching, converting, and comparing names are all available without creating an account.",
  },
  {
    q: "Are the names generated by this tool real Japanese names?",
    a: "Yes. The generator pulls from real Japanese girl names, boy names, and surnames rather than inventing random syllable combinations. Each result includes its Kanji, Hiragana reading, and Hepburn romaji spelling.",
  },
  {
    q: "What's the difference between Kanji, Hiragana, and Katakana?",
    a: "Kanji are characters that carry meaning. Hiragana is a phonetic script used mainly for native Japanese words. Katakana is a separate phonetic script used mainly for foreign words and names.",
  },
  {
    q: "Do Japanese names have middle names?",
    a: "No. Japanese naming doesn't include a middle name. A person has a family name and a given name.",
  },
  {
    q: "Which comes first, the family name or the given name?",
    a: "In traditional Japanese order, the family name comes first, followed by the given name — for example, Yamamoto Haruto, not Haruto Yamamoto.",
  },
  {
    q: "Can the same-sounding name be written differently?",
    a: "Yes. Since meaning comes from the Kanji rather than the sound, two people can have identically pronounced names written with completely different Kanji and different meanings.",
  },
  {
    q: "Can I search for a Japanese name by its meaning?",
    a: "Yes, the tool lets you search by meaning so you can look for names tied to specific ideas, like strength, beauty, or nature.",
  },
  {
    q: "How do I convert my own name into Japanese?",
    a: "Use the name-to-Katakana converter in the tool, since Katakana is the script traditionally used to write foreign names in Japanese.",
  },
  {
    q: "What are Japanese name honorifics like san, kun, and chan?",
    a: "Honorifics attach to the end of a name and signal the relationship between speaker and listener. San is a general polite honorific, kun is often used for boys or juniors, chan is used for children or close friends, and sensei is used for teachers and respected figures.",
  },
  {
    q: "What are the most common Japanese surnames?",
    a: "Some of the most common Japanese surnames include Satō, Suzuki, Takahashi, Tanaka, Watanabe, Itō, and Yamamoto, many of which reference nature or geography.",
  },
  {
    q: "Is this generator suitable for naming fictional characters?",
    a: "Yes. Names are based on real Japanese naming data with accurate Kanji and readings, so the results work well for fiction, anime and manga characters, and game development.",
  },
  {
    q: "Does the tool include historical or samurai-style names?",
    a: "Yes, you can browse names and surnames that fit a historical or samurai-era setting, including real clan-linked surnames, alongside modern names for contemporary settings.",
  },
  {
    q: "Do I need to create an account to save favorite names?",
    a: "No. No signup is required to use the favorites feature or any other part of the tool.",
  },
];

const h2Style = {
  fontFamily: "var(--font-display)", fontWeight: 800, fontSize: 17,
  color: "var(--text-primary)", letterSpacing: "-0.02em", marginBottom: 10,
};
const h3Style = {
  fontFamily: "var(--font-display)", fontWeight: 700, fontSize: 14,
  color: "var(--text-primary)", marginTop: 14, marginBottom: 8,
};
const pStyle = { fontSize: 13.5, color: "var(--text-secondary)", lineHeight: 1.7, marginBottom: 10 };
const ulStyle = { ...pStyle, marginBottom: 0, paddingLeft: 18 };
const cardStyle = { padding: "20px 20px" };
const thStyle = {
  textAlign: "left", padding: "8px 10px", fontSize: 12, fontWeight: 700,
  color: "var(--text-muted)", textTransform: "uppercase", letterSpacing: "0.02em",
  borderBottom: "1px solid var(--border)", whiteSpace: "nowrap",
};
const tdStyle = { padding: "8px 10px", fontSize: 13, color: "var(--text-secondary)", borderBottom: "1px solid var(--border)" };
const tdNameStyle = { ...tdStyle, fontWeight: 700, color: "var(--text-primary)", whiteSpace: "nowrap" };
const tdKanjiStyle = { ...tdStyle, whiteSpace: "nowrap" };

function DataTable({ columns, rows }) {
  return (
    <div style={{ overflowX: "auto", marginBottom: 10 }}>
      <table style={{ width: "100%", borderCollapse: "collapse" }}>
        <thead>
          <tr>
            {columns.map((c) => <th key={c} style={thStyle}>{c}</th>)}
          </tr>
        </thead>
        <tbody>
          {rows.map((row, i) => (
            <tr key={i}>
              {row.map((cell, j) => (
                <td key={j} style={j === 0 ? tdNameStyle : j === 1 ? tdKanjiStyle : tdStyle}>{cell}</td>
              ))}
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  );
}

function FaqRow({ item, open, onToggle }) {
  return (
    <div style={{ borderBottom: "1px solid var(--border)" }}>
      <button
        type="button"
        onClick={onToggle}
        aria-expanded={open}
        style={{
          width: "100%", display: "flex", alignItems: "center", justifyContent: "space-between",
          gap: 10, padding: "13px 2px", background: "transparent", border: "none",
          cursor: "pointer", textAlign: "left",
        }}
      >
        <span style={{ fontFamily: "var(--font-display)", fontWeight: 700, fontSize: 13.5, color: "var(--text-primary)" }}>
          {item.q}
        </span>
        <svg width="12" height="12" viewBox="0 0 10 10" fill="none" style={{
          flexShrink: 0, transform: open ? "rotate(180deg)" : "rotate(0deg)", transition: "transform 0.2s",
        }} aria-hidden="true">
          <path d="M1.5 3.5L5 7L8.5 3.5" stroke="var(--text-muted)" strokeWidth="1.6" strokeLinecap="round" strokeLinejoin="round" />
        </svg>
      </button>
      {open && (
        <p style={{ fontSize: 13, color: "var(--text-secondary)", lineHeight: 1.6, margin: "0 0 14px" }}>
          {item.a}
        </p>
      )}
    </div>
  );
}

const SURNAME_ROWS = [
  ["Satō", "佐藤", "\"helper\" + \"wisteria\"", "The most common surname in Japan; the wisteria character links back to the historic Fujiwara clan"],
  ["Suzuki", "鈴木", "\"bell\" + \"tree\"", "Second most common; has roots in Shinto ritual"],
  ["Takahashi", "高橋", "\"tall bridge\"", "Third most common surname"],
  ["Tanaka", "田中", "\"middle of the rice field\"", "A classic farming-village surname"],
  ["Watanabe", "渡辺", "\"crossing place\"", "Traced back to families who worked river or ferry crossings"],
  ["Itō", "伊藤", "\"that\" + \"wisteria\"", "Another surname connected to the Fujiwara lineage"],
  ["Yamamoto", "山本", "\"base of the mountain\"", "A geographic surname"],
  ["Nakamura", "中村", "\"middle village\"", "One of the older common surname types"],
  ["Kobayashi", "小林", "\"small forest\"", "Common nature-based surname"],
  ["Shimizu", "清水", "\"pure water\"", "Common nature-based surname"],
  ["Kimura", "木村", "\"tree village\"", "Common nature-based surname"],
  ["Hayashi", "林", "\"forest\"", "One of the few common surnames written with a single Kanji"],
  ["Yamada", "山田", "\"mountain rice field\"", "Combines two very common geographic elements"],
  ["Sasaki", "佐々木", "\"helper\" (repeated) + \"tree\"", "The small mark 々 shows the first character is repeated"],
  ["Yoshida", "吉田", "\"lucky rice field\"", "A farming-village surname with a positive meaning"],
  ["Matsumoto", "松本", "\"base of the pine\"", "Nature-based surname"],
  ["Inoue", "井上", "\"above the well\"", "Refers to a home's position near the village well"],
  ["Ishikawa", "石川", "\"stone river\"", "Nature-based surname"],
  ["Fujita", "藤田", "\"wisteria field\"", "Another surname tied to the historic Fujiwara name"],
  ["Ogawa", "小川", "\"small river\"", "Simple, common nature-based surname"],
];

const GIRL_MODERN_ROWS = [
  ["Himari", "陽葵", "\"sun\" + \"hollyhock\""],
  ["Ichika", "一花", "\"one flower\""],
  ["Tsumugi", "紬", "\"spun silk\""],
  ["Mei", "芽依", "\"sprout\" + \"rely on\""],
  ["Yua", "結愛", "\"tie together\" + \"love\""],
  ["Yui", "結衣", "\"tie together\" + \"garment\""],
  ["Aoi", "葵", "\"hollyhock\""],
  ["Rin", "凛", "\"dignified, crisp\""],
  ["Riko", "莉子", "\"jasmine\" + \"child\""],
  ["Koharu", "小春", "\"little spring\" (a warm spell in autumn)"],
];

const GIRL_CLASSIC_ROWS = [
  ["Sakura", "桜", "\"cherry blossom\""],
  ["Hana", "花", "\"flower\""],
  ["Yuki", "雪 / 幸", "\"snow\" or \"happiness,\" depending on the Kanji used"],
  ["Akari", "明里", "\"brightness\" + \"village\""],
  ["Misaki", "美咲", "\"beautiful bloom\""],
  ["Emi", "恵美", "\"blessing\" + \"beauty\""],
  ["Haruka", "遥", "\"far-off, distant\""],
  ["Sora", "空", "\"sky\" (used for both girls and boys)"],
  ["Keiko", "恵子", "\"blessed child\""],
  ["Yumiko", "由美子", "\"reason\" + \"beauty\" + \"child\""],
];

const BOY_MODERN_ROWS = [
  ["Haruto", "陽翔", "\"sun\" + \"soar\""],
  ["Ren", "蓮", "\"lotus\""],
  ["Minato", "湊", "\"harbor\""],
  ["Riku", "陸", "\"land\""],
  ["Sōta", "颯太", "\"swift wind\" + \"big\""],
  ["Yūto", "悠人", "\"calm, distant\" + \"person\""],
  ["Sōsuke", "颯介", "\"swift wind\" + \"helper\""],
  ["Kaito", "海斗", "\"sea\" + \"ladle\" (also refers to the Big Dipper)"],
  ["Itsuki", "樹", "\"tree\" (used for both boys and girls)"],
  ["Haruki", "春樹", "\"spring\" + \"tree\""],
];

const BOY_CLASSIC_ROWS = [
  ["Yamato", "大和", "The old, ancient name for Japan itself"],
  ["Daiki", "大輝", "\"great\" + \"radiance\""],
  ["Kenji", "健二", "\"healthy\" + \"second son\""],
  ["Takashi", "隆", "\"noble, prosperous\""],
  ["Hiroshi", "寛", "\"generous, tolerant\""],
  ["Takeshi", "武", "\"warrior\""],
  ["Osamu", "治", "\"discipline, govern\""],
  ["Kiyoshi", "清", "\"pure\""],
  ["Isamu", "勇", "\"courage\""],
  ["Susumu", "進", "\"advance, progress\""],
];

const COOL_NAME_ROWS = [
  ["Jin", "仁", "\"benevolence\"", "One syllable, but carries real philosophical weight"],
  ["Arashi", "嵐", "\"storm\"", "Nature imagery with an edge"],
  ["Kaede", "楓", "\"maple\"", "Elegant and gender-neutral"],
  ["Ryō", "涼", "\"cool, refreshing\"", "Literally means \"cool\""],
  ["Shinobu", "忍", "\"endurance, stealth\"", "The same character used in \"shinobi\" (ninja)"],
  ["Hayate", "疾風", "\"gale, swift wind\"", "Suggests speed"],
  ["Tsubasa", "翼", "\"wings\"", "Aspirational and gender-neutral"],
  ["Rei", "零 / 麗", "\"zero\" or \"lovely,\" depending on the Kanji", "Short, minimal, mysterious"],
  ["Kenshin", "謙信", "\"humble trust\"", "Echoes famous samurai-era figures"],
  ["Akira", "明", "\"bright, clear\"", "Gender-neutral classic with wide pop-culture recognition"],
  ["Raiden", "雷電", "\"thunder and lightning\"", "Big, dramatic sound and meaning"],
  ["Musashi", "武蔵", "An old province name", "Associated with one of Japan's most famous swordsmen"],
  ["Hayato", "隼人", "\"falcon\" + \"person\"", "Suggests speed and sharpness"],
  ["Taiga", "大河", "\"great river\"", "Sounds epic despite being short"],
  ["Homura", "焔", "\"blaze, flame\"", "Fire, captured in a single character"],
  ["Kohaku", "琥珀", "\"amber\"", "Gender-neutral, with a warm, old-fashioned glow"],
  ["Shion", "詩音", "\"poem\" + \"sound\"", "Gender-neutral and melodic"],
];

export default function JapaneseNameFaqSection() {
  const [openIndex, setOpenIndex] = useState(0);

  const faqSchema = {
    "@context": "https://schema.org",
    "@type": "FAQPage",
    mainEntity: FAQ_ITEMS.map((item) => ({
      "@type": "Question",
      name: item.q,
      acceptedAnswer: { "@type": "Answer", text: item.a },
    })),
  };

  return (
    <div style={{ display: "flex", flexDirection: "column", gap: 20 }}>
      <JsonLd data={faqSchema} />

      <div className="card" style={cardStyle}>
        <p style={{ ...pStyle, marginBottom: 0 }}>
          Picking a Japanese name isn't as simple as choosing something that sounds nice. Japanese names
          carry meaning through Kanji characters, follow their own rules for order and pronunciation, and
          look different depending on whether you're naming a girl, a boy, or a whole family. This Japanese
          name generator was built to make that easy. Instead of guessing at spellings or piecing meanings
          together from random websites, you get real names with correct Kanji, Hiragana readings, and
          Hepburn romaji, all in one place, free, with no signup. It's one of the many free tools on{" "}
          <Link to="/" className="inline-home-link">Tolz</Link>, where the focus is on quick, simple
          utilities that just work.
        </p>
      </div>

      <div className="card" style={cardStyle}>
        <h2 style={h2Style}>What This Japanese Name Generator Does</h2>
        <p style={pStyle}>
          This tool generates and lets you browse real Japanese names, not made-up syllables that just
          sound Japanese. Every name comes with three things: its Kanji (the characters normally used to
          write it), its Hiragana reading (how it's actually pronounced, using Japan's native phonetic
          script), and its Hepburn romaji spelling (the standard way to write Japanese sounds using English
          letters). This last one is what most non-Japanese speakers are used to seeing.
        </p>
        <p style={{ ...pStyle, marginBottom: 0 }}>
          You can hit generate for quick, random inspiration, or browse the full A-Z list of Japanese girl
          names, boy names, and surnames when you already know roughly what you're looking for. Some people
          want quick ideas, others want to search carefully for something specific, this tool covers both.
        </p>
      </div>

      <div className="card" style={cardStyle}>
        <h2 style={h2Style}>Why and When You'd Need a Japanese Name Generator</h2>
        <p style={pStyle}>There are plenty of everyday, practical reasons people search for a tool like this:</p>
        <ul style={ulStyle}>
          <li style={{ marginBottom: 8 }}>
            <strong>Naming characters in stories, games, or shows.</strong> Writers, game developers, and
            anyone building a fictional world often need Japanese-sounding names that actually hold up.
            Pairing a believable surname with a believable given name makes a character feel real instead
            of like a random name mash-up.
          </li>
          <li style={{ marginBottom: 8 }}>
            <strong>Learning Japanese.</strong> People studying the language like seeing how their own name
            might sound or be written in Japanese, or just want more practice reading real Kanji and
            Hiragana together.
          </li>
          <li style={{ marginBottom: 8 }}>
            <strong>Picking a personal Japanese name.</strong> Some people choose a Japanese name for anime
            communities, gaming handles, or art aliases, and want to know what it actually means before
            using it, rather than picking something that sounds fine but doesn't make sense in Japanese.
          </li>
          <li style={{ marginBottom: 8 }}>
            <strong>Choosing a baby name.</strong> Parents interested in Japanese naming traditions, whether
            for heritage reasons or just because they like the sound and meaning, use tools like this to
            look at real options instead of trusting random lists online.
          </li>
          <li style={{ marginBottom: 8 }}>
            <strong>Making content about Japan.</strong> YouTubers, streamers, and creators building
            anything Japan-themed need names that hold up if a Japanese-speaking viewer is watching closely.
          </li>
          <li>
            <strong>Comparing a shortlist before deciding.</strong> Whether it's for a character, a project,
            or personal curiosity, putting a few names side by side, Kanji, meaning, and readings together,
            makes deciding much easier than checking each one separately.
          </li>
        </ul>
      </div>

      <div className="card" style={cardStyle}>
        <h2 style={h2Style}>Kanji, Hiragana, and Katakana — What's the Difference</h2>
        <p style={pStyle}>
          Japanese uses three writing systems together, and each one does a different job. Knowing the
          difference is the key to actually understanding a Japanese name, not just copying a spelling.
        </p>
        <p style={pStyle}>
          <strong>Kanji</strong> are characters, mostly borrowed from Chinese, that carry meaning. The
          same-sounding name can be written with completely different Kanji, and each version changes what
          the name actually means. This is why Kanji is really the heart of a Japanese name, the sound is
          only half the story.
        </p>
        <p style={pStyle}>
          <strong>Hiragana</strong> is a phonetic script that shows how a word is pronounced, without
          needing to know thousands of individual Kanji. It's the script most beginners learn first, and
          it's used for native Japanese words and grammar.
        </p>
        <p style={pStyle}>
          <strong>Katakana</strong> is a separate phonetic script, mainly used for foreign words and foreign
          names. If you want to see how your own (non-Japanese) name would typically be written in Japanese,
          Katakana is the correct script, not Kanji or Hiragana.
        </p>
        <p style={pStyle}>
          <strong>Hepburn romaji</strong> is the standard system for writing Japanese sounds with the Latin
          alphabet, the version most English speakers recognize, and the one used on official documents
          like passports.
        </p>
        <p style={{ ...pStyle, marginBottom: 0 }}>
          Seeing all of these together for a name, Kanji, Hiragana, and romaji, gives you the full, accurate
          picture instead of just a romanized guess.
        </p>
      </div>

      <div className="card" style={cardStyle}>
        <h2 style={h2Style}>How Japanese Names Are Structured</h2>
        <p style={pStyle}>
          Japanese names work differently from Western names in a few important ways, and understanding
          this helps explain why a name generator built on real data works better than randomly combining
          sounds.
        </p>
        <ul style={ulStyle}>
          <li style={{ marginBottom: 8 }}>
            <strong>Family name comes first.</strong> In Japan, the order is family name, then given name,
            for example, Yamamoto Haruto, not Haruto Yamamoto. This is the reverse of the typical Western
            order. In English-language contexts, people often flip the order to match Western habits, but
            the original Japanese order always puts the family name first.
          </li>
          <li style={{ marginBottom: 8 }}>
            <strong>There are no middle names.</strong> Japanese naming doesn't include a middle name the
            way many Western naming systems do. A person simply has a family name and a given name.
          </li>
          <li style={{ marginBottom: 8 }}>
            <strong>The same sound can mean different things.</strong> Because meaning lives in the Kanji
            rather than the sound, two people can have names that sound identical but are written, and mean,
            something completely different. A classic example is the name "Yuki," which can be written as
            雪 (meaning "snow") or 幸 (meaning "happiness"), depending on which Kanji the parents chose.
            Parents essentially choose a name twice: once for how it sounds, and once for what it says when
            written down.
          </li>
          <li style={{ marginBottom: 8 }}>
            <strong>Honorifics shape how names are used.</strong> Japanese speakers rarely use someone's
            first name casually the way English speakers might. Instead, honorifics attach to the end of a
            name to show the relationship between speaker and listener, "san" is a general polite honorific,
            "kun" is often used for boys or juniors, "chan" for children or close friends, and "sensei" for
            teachers, doctors, or other respected figures. This matters for anyone writing dialogue between
            Japanese characters, since dropping or using the wrong honorific changes the tone of the whole
            exchange.
          </li>
          <li>
            <strong>Era affects how a name sounds.</strong> A name that was common for a child born in the
            1950s can sound just as old-fashioned today as "Harold" or "Doris" might sound for an American
            teenager. Naming trends shift generation by generation, so it's worth matching a name's era to
            the character or context it's being used for, or mismatching it on purpose, for effect.
          </li>
        </ul>
      </div>

      <div className="card" style={cardStyle}>
        <h2 style={h2Style}>Most Common Japanese Surnames</h2>
        <p style={pStyle}>
          Japanese surnames (myoji) are usually tied to geography or nature, things like mountains, rice
          fields, rivers, and forests, which reflects Japan's farming and rural history. A small number of
          surnames cover a large share of the population. Here are some of the most common ones, along with
          what they mean and a bit of background:
        </p>
        <DataTable columns={["Surname", "Kanji", "Meaning", "Background"]} rows={SURNAME_ROWS} />
      </div>

      <div className="card" style={cardStyle}>
        <h2 style={h2Style}>Popular Japanese Girl Names</h2>
        <p style={pStyle}>
          Girl names in Japan often lean on nature and light, flowers, snow, the sky, though what counts as
          "popular" changes a lot from decade to decade. A name that was everywhere in the 1980s can sound
          very different from what's popular for newborns today.
        </p>
        <h3 style={h3Style}>Modern and currently popular names</h3>
        <DataTable columns={["Name", "Common Kanji", "Meaning"]} rows={GIRL_MODERN_ROWS} />
        <h3 style={h3Style}>Evergreen and classic names</h3>
        <DataTable columns={["Name", "Common Kanji", "Meaning"]} rows={GIRL_CLASSIC_ROWS} />
        <p style={{ ...pStyle, marginBottom: 0 }}>
          Traditional girl names often end in soft sounds like -ko ("child"), -mi ("beauty"), -ka
          ("flower"), or -na ("greens/vegetables"). Names ending in -ko, like Keiko or Yumiko, tend to read
          as old-fashioned today, similar to how "Doris" or "Linda" might sound to English speakers now.
          Newer names tend to be shorter and simpler to pronounce internationally, such as Aoi, Mei, or Rin.
        </p>
      </div>

      <div className="card" style={cardStyle}>
        <h2 style={h2Style}>Popular Japanese Boy Names</h2>
        <p style={pStyle}>
          Boy names in Japan often draw on strength, ambition, and family lineage, and, just like girl
          names, the popular choices shift a lot by generation.
        </p>
        <h3 style={h3Style}>Modern and currently popular names</h3>
        <DataTable columns={["Name", "Common Kanji", "Meaning"]} rows={BOY_MODERN_ROWS} />
      </div>

      <div className="card" style={cardStyle}>
        <h2 style={h2Style}>Classic and Older-Generation Names</h2>
        <DataTable columns={["Name", "Common Kanji", "Meaning"]} rows={BOY_CLASSIC_ROWS} />
        <p style={{ ...pStyle, marginBottom: 0 }}>
          Traditional boy names commonly end in -ro ("son"), -ta ("thick" or "great"), -ki ("tree"), or -shi
          ("aspiration"). Names like Kenji, Takeshi, or Hiroshi carry that older, classic weight today,
          naming a modern teenager Hiroshi is a bit like naming an American teenager Harold. Contemporary
          boy names, such as Riku, Sōta, or Daichi, tend to sound lighter and more current while still
          keeping a clearly Japanese sound.
        </p>
      </div>

      <div className="card" style={cardStyle}>
        <h2 style={h2Style}>Cool and Striking Names for Anime, Manga, and Original Characters</h2>
        <p style={pStyle}>
          "Cool" works differently in Japanese naming than in English. Short, single-Kanji names, sharp
          nature imagery, and names borrowed from history all tend to read as strong or striking.
        </p>
        <DataTable columns={["Name", "Kanji", "Meaning", "Why it feels bold"]} rows={COOL_NAME_ROWS} />
      </div>

      <div className="card" style={cardStyle}>
        <h2 style={h2Style}>Samurai-Era and Historical Japanese Names</h2>
        <p style={pStyle}>
          Feudal Japan, the age of samurai, daimyo (regional lords), and shogun, used naming patterns that
          differ from modern ones. Historical names from periods like the Sengoku, Edo, and Heian eras often
          lean on Kanji tied to strength, honor, or nature, and surnames connected to specific clans and
          territories carried real political weight.
        </p>
        <p style={pStyle}>
          Some real historical clan surnames that still show up in fiction, games, and period dramas include
          Takeda, Oda, Tokugawa, Uesugi, Minamoto, Taira, Hosokawa, Shimazu, and Ikeda. Each of these was a
          real ruling family with its own territory and history, which is why using an authentic clan name
          instantly signals a historical or samurai setting, without needing extra explanation.
        </p>
        <p style={{ ...pStyle, marginBottom: 0 }}>
          For a samurai protagonist, a period drama, a historical novel, or a feudal-era setting, sticking
          to real Kanji meanings and real clan-linked surnames helps avoid anachronism, names that would
          feel out of place for the time period. Pairing a clan-linked surname (like Takeda or Oda) with a
          given name built from strength- or honor-related Kanji (like Takeshi, meaning "warrior," or
          Hideaki, meaning "excellent and bright") is a reliable way to build a historically grounded name.
        </p>
      </div>

      <div className="card" style={cardStyle}>
        <h2 style={h2Style}>Japanese Clan Names for Worldbuilding</h2>
        <p style={pStyle}>
          A clan name identifies a whole family line, not just one person, the shared surname carried across
          generations. Historically, clans such as Takeda, Shimazu, Ikeda, and Hosokawa controlled territory
          and held real political power, and their names still carry a sense of prestige and history today.
        </p>
        <p style={{ ...pStyle, marginBottom: 0 }}>
          For worldbuilding, a shared clan surname is a useful way to build a family tree, a rival house, or
          a faction of related characters without inventing something from scratch. Pairing a real clan
          surname with different given names for each character is an easy way to build a cast that
          instantly reads as connected, and authentically Japanese, without tying the whole story to one
          specific historical period.
        </p>
      </div>

      <div className="card" style={cardStyle}>
        <h2 style={h2Style}>Names for School and Slice-of-Life Settings</h2>
        <p style={{ ...pStyle, marginBottom: 0 }}>
          Not every story needs samurai-era weight. Stories set in modern Japan, high schools, everyday
          life, workplace dramas, call for lighter, more contemporary-sounding names. Names like Yui,
          Sakura, Ryo, and Hana are common, easy to say, and instantly read as modern teenage or young-adult
          characters. These work well for school stories, slice-of-life scripts, or any contemporary
          setting, and pairing a modern given name with any surname from the tool is an easy way to build a
          believable modern cast.
        </p>
      </div>

      <div className="card" style={cardStyle}>
        <h2 style={h2Style}>Searching by Meaning</h2>
        <p style={{ ...pStyle, marginBottom: 0 }}>
          Japanese names are often chosen for what they represent, strength, beauty, nature, or hopes for a
          child's future. This tool lets you search directly by meaning, so instead of scrolling an
          alphabetical list hoping to spot the right one, you can search for something specific, like a name
          meaning "light," "flower," or "victory." This is especially useful for writers assigning
          meaningful names to characters, or for anyone choosing a name with a particular idea in mind.
        </p>
      </div>

      <div className="card" style={cardStyle}>
        <h2 style={h2Style}>Converting Your Name to Katakana</h2>
        <p style={{ ...pStyle, marginBottom: 0 }}>
          Along with generating and browsing names, the tool includes a name-to-Katakana converter. As
          covered above, Katakana is the script used for foreign words and foreign names in Japanese, not
          Kanji or Hiragana, so this feature shows you how your own name would typically be written the way
          it would actually appear in Japan. It's commonly used by language learners, travelers, and anyone
          simply curious how their name looks in Japanese.
        </p>
      </div>

      <div className="card" style={cardStyle}>
        <h2 style={h2Style}>Comparing and Saving Favorite Names</h2>
        <p style={{ ...pStyle, marginBottom: 0 }}>
          When choosing between a few options, for a character, a project, or personal use, the compare
          feature lets you look at names side by side, checking their Kanji, meanings, and readings
          together. This is a lot faster than keeping multiple tabs or notes open. Once you've found names
          you like, you can save them as favorites and come back to your shortlist later without searching
          from scratch again.
        </p>
      </div>

      <div className="card" style={cardStyle}>
        <h2 style={h2Style}>Tips for Choosing a Good Japanese Name</h2>
        <p style={pStyle}>
          A few things are worth knowing whether you're naming a character, picking a personal name, or
          just exploring:
        </p>
        <ul style={ulStyle}>
          <li style={{ marginBottom: 8 }}>
            <strong>The Kanji matter as much as the sound.</strong> A Japanese name works on two levels at
            once, how it sounds, and what it means when written. Anyone who reads Japanese will notice both.
            If a name is meant to carry symbolic weight, that weight lives in the Kanji, not just the
            pronunciation.
          </li>
          <li style={{ marginBottom: 8 }}>
            <strong>Family name comes before given name.</strong> Keep the order in mind in narration,
            dialogue, and especially in scenes where characters move between Japanese and Western settings,
            since the order may shift depending on context.
          </li>
          <li style={{ marginBottom: 8 }}>
            <strong>Honorifics carry social meaning.</strong> Terms like san, kun, chan, and sensei attach
            to names and signal the relationship between two people. Skipping or misusing them changes how
            a line of dialogue reads.
          </li>
          <li style={{ marginBottom: 8 }}>
            <strong>Era shapes how a name feels.</strong> Names from the Meiji and Taisho periods sound very
            different from names given to children today, which tend toward softer sounds and nature-based
            imagery.
          </li>
          <li style={{ marginBottom: 8 }}>
            <strong>Certain endings lean gendered.</strong> Female names often end in -ko, -mi, -ka, or -na,
            while male names often end in -ro, -ta, -ki, or -shi, although modern naming plays with these
            patterns more freely than in the past.
          </li>
          <li>
            <strong>Real Kanji combinations matter.</strong> Unlike invented fantasy names, an authentic
            Japanese name needs to map to real Kanji. Sakura (桜) really does mean "cherry blossom." Haruki
            (春樹) really does combine "spring" and "tree." That real, checkable meaning is what makes
            Japanese names so useful for character development — there's genuine symbolism to draw from, not
            just an invented sound.
          </li>
        </ul>
      </div>

      <div className="card" style={cardStyle}>
        <h2 style={h2Style}>Frequently Asked Questions</h2>
        {FAQ_ITEMS.map((item, i) => (
          <FaqRow key={item.q} item={item} open={openIndex === i} onToggle={() => setOpenIndex(openIndex === i ? -1 : i)} />
        ))}
      </div>
    </div>
  );
}
